### ISSUE TITLE
 Like and dislike buttons shows same colour in dark theme

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/chat.susi.ai#1006]
**Actual Behaviour**

Like and dislike buttons show same colour in dark theme

**Expected Behaviour**

Like button should be green. dislike button should be red.

**Steps to reproduce it**

go to https://chat.susi.ai/

**Screenshots of the issue**

![screenshot_20180107_150758](https://user-images.githubusercontent.com/8947010/34648221-b05522c0-f3bc-11e7-870c-5949ffc19390.png)

![screenshot_20180107_150903](https://user-images.githubusercontent.com/8947010/34648222-b54883f8-f3bc-11e7-9a06-89c647206966.png)

**Comment by ParthS007** [comment]
I am working on this 👍
