### ISSUE TITLE
Designing not matching

### ISSUE THREAD

**Issue by newbazz** [fossasia/chat.susi.ai#1010]
**Actual Behaviour**
![image](https://user-images.githubusercontent.com/25884863/34670847-07288146-f49e-11e7-80c7-0c1678f5a402.png)

Please state here what is currently happening.

It should be blue in white style

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by newbazz** [comment]
Yes i would like to work on this issue.

**Comment by newbazz** [comment]
I am not able to locate the file to edit, can someone help me out.

**Comment by luckykumardev** [comment]
@newbazz  are still working on this issue?

**Comment by mariobehling** [comment]
Needs to be solved in skills cms.
