### ISSUE TITLE
Show images which have responses as image URLs.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#102]
![screenshot from 2017-05-29 12 31 42](https://cloud.githubusercontent.com/assets/11540785/26539589/f2ed5c4e-446a-11e7-8492-73904392db07.png)

![screenshot from 2017-05-29 12 33 26](https://cloud.githubusercontent.com/assets/11540785/26539606/0a2cc78c-446b-11e7-866c-e40452610a1d.png)
Images with jpg, gif,jpeg and all such extensions should show in the chat response.

**Comment by uday96** [comment]
@rishiraj824  Do these types of urls always end with .jpg .jpeg .png extensions?

**Comment by rishiraj824** [comment]
@uday96 Yes, they do. For skills giving us responses with image extensions as URLs.

**Comment by isuruAb** [comment]
anyone working on this ?

**Comment by uday96** [comment]
Working on this. Making a PR :)

**Comment by uday96** [comment]
**Demo link** : http://imagesupport.surge.sh/
Suggest changes :smile:

**Comment by rishiraj824** [comment]
Add the following styles to the images.
```
    width: 95%;
    height: auto;
```
