### ISSUE TITLE
Pre-formatted text in the blog page wraps alot on mobile devices which makes it harder to read it.

### ISSUE THREAD

**Issue by kapillamba4** [fossasia/chat.susi.ai#1020]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/20877996/34733504-9ca0e3a8-f58e-11e7-9e65-93034f53dd33.png)
Code snippets or any pre-formatted text in a blog post wraps when it cannot fit in the pre-defined width. This makes it harder to read the text.

**Expected Behaviour**

Pre-formatted text should allow horizontal scrolling and only wrap on line-breaks, just like [stackoverflow](https://stackoverflow.com) below:
![image](https://user-images.githubusercontent.com/20877996/34733817-b27275b0-f58f-11e7-8c59-62694e474a65.png)

**Steps to reproduce it**

Try to open https://chat.susi.ai/blog on a mobile device

**Would you like to work on the issue?**

Yes

**Comment by Akshat-Jain** [comment]
@kapillamba4 As this issue has been solved, I'm closing the issue. Thanks :-)
