### ISSUE TITLE
Add Code of conduct 

### ISSUE THREAD

**Issue by S2606** [fossasia/chat.susi.ai#1027]
**Actual Behaviour**

Currently there is no code of conduct file in repo

**Expected Behaviour**

There can be one.

**Would you like to work on the issue?**

Yes

**Comment by bhaveshAn** [comment]
Do we really need this.

**Comment by daminisatya** [comment]
We need this. @bhaveshAn

**Comment by daminisatya** [comment]
Please help us add one

**Comment by bhaveshAn** [comment]
I think these will help
* https://github.com/fossasia/chat.susi.ai/blob/master/docs/ACCOUNTING.md
* https://dev.susi.ai/

**Comment by bhaveshAn** [comment]
@S2606 Are you working on it ??

**Comment by palash25** [comment]
@bhaveshAn @daminisatya I would like to work on this if the OP isn't working on this.

Just to be sure the code of conduct should be modelled after this https://coc.fossasia.org/ right?
