### ISSUE TITLE
Modifications in the current UI

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#104]
Currently, Web and Android versions of susi are following different themes. We should make susi web look alike susi Android.

Please comment your opinions.

Thanks

**Comment by rishiraj824** [comment]
@madhavrathi Let's change the title to "Modifications in the current UI"
And let's focus on these points -
- Adding chat bubbles to messages
- Having SUSI's messages on the left, while user's messages on the right
- Having a send button.
- Propose a color pattern for the template.


Let me know about your views.
