### ISSUE TITLE
[BUG] Susi doesn't take input of strings starting with angle bracket, random results

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/chat.susi.ai#1042]
**Actual Behaviour**
Susi doesn't take input of strings starting with `<` and **responds randomly to it** 

**Expected Behaviour**
Susi App must either reject the input before sending it to the `susi_server` , or
display the message after escaping it instead of **completely not showing it**.
An error message can also be added for such input.

**Steps to reproduce it**
- Add checks for input
- Display notification for improper input format

**Screenshots of the issue**
![susi-bug](https://user-images.githubusercontent.com/14032427/34905714-bba5cb1c-f884-11e7-81fb-b7b68014ae27.gif)

**Would you like to work on the issue?**
Not too comfortable in react. It should be assigned to someone else.

**Comment by luckykumardev** [comment]
I want to work on this issue.

**Comment by YashKumarVerma** [comment]
@luckykumardev please go ahead 😄

**Comment by sayak119** [comment]
@YashKumarVerma I am taking up this issue due to inactivity. Will make a PR soon
