### ISSUE TITLE
Error Message Wrong !!

### ISSUE THREAD

**Issue by Beta-King** [fossasia/chat.susi.ai#1048]
**Actual Behaviour**
While signing up if you put down an email which already has an account it says, 'Failed. Try Again'

Please state here what is currently happening.

**Expected Behaviour**
While signing up if you put down an email which already has an account it should say, 'This email already has an account attached to it.' 

Then a dropbox stating what went wrong, for example:
- is this not your email
- did you forget your password
- would you like to try again
etc...

State here what the feature should enable the user to do.

**Steps to reproduce it**
go to https://accounts.susi.ai/signup
try this error for yourself by filling the fields which already have an account...

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Comment by Beta-King** [comment]
![screen shot 2018-01-14 at 10 21 34 am](https://user-images.githubusercontent.com/33036913/34913035-7534c79e-f917-11e7-9845-bb07ffdf6308.png) --> this is the error !!

**Comment by DNS-404** [comment]
I would like to work on this.

**Comment by DNS-404** [comment]
How about we just change the message to "Email already taken. Please try with another email."?
I don't think that there is a need to create "forgot your password" option here because it's already present in the login window.

**Comment by Beta-King** [comment]
Go AHEAD, That seems fine too :D

**Comment by DNS-404** [comment]
Okay!

**Comment by DNS-404** [comment]
How did you go to https://accounts.susi.ai/signup from https://chat.susi.ai/ ?
