### ISSUE TITLE
Add Date format feature

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/chat.susi.ai#1049]
**Actual Behaviour**
Currently the date is shown only in one format.
**Expected Behaviour**
User should be given the option to change the format of the date.
**Steps to reproduce it**
Have to add a new feature for Date Format
**Screenshots of the issue**
![screen shot 2018-01-14 at 11 39 21 am](https://user-images.githubusercontent.com/31013104/34913322-965514f8-f91f-11e7-9b85-014bcd75f6df.png)
![screen shot 2018-01-14 at 11 39 42 am](https://user-images.githubusercontent.com/31013104/34913323-9eef44c6-f91f-11e7-8898-79777e28592f.png)

**Would you like to work on the issue?**
Yes

**Comment by harsh-jindal** [comment]
Any member please reply do we need this feature or not?

**Comment by mariobehling** [comment]
Currently out of scope.
