### ISSUE TITLE
Add Heroku deployment and its auto deploy button

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/chat.susi.ai#1063]
**Actual Behaviour**

Currently, Heroku deployment for the repo and its auto-deploy button is not present.

**Expected Behaviour**

Add Heroku deployment for the repo and its auto-deploy button

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

**Yes**

**Comment by sakshee-19** [comment]
@bhaveshAn If you are not working on this issue, then I am taking this up :+1:

**Comment by bhaveshAn** [comment]
Sure

**Comment by mariobehling** [comment]
Actually, we don't need it since it deploys directly to Github pages. Thanks for the concern though!
