### ISSUE TITLE
Heading "General" is not required under "Text-To-Speech settings"

### ISSUE THREAD

**Issue by DNS-404** [fossasia/chat.susi.ai#1069]
**Actual Behaviour**

There's a heading "General" above language settings which is not required because are not any options other than general options. If we add other options in future, then we can add "General". Right now, it looks odd.

**Expected Behaviour**

"General" should not be there.

**Steps to reproduce it**

Go to https://chat.susi.ai/settings and open "Speech Settings".
Now click on "SELECT DEFAULT LANGUAGE" under "Speech Output Language".

**Screenshots of the issue**

<img width="500" alt="screen shot 2018-01-26 at 5 02 04 pm" src="https://user-images.githubusercontent.com/31174685/35438118-5000b9c6-02bb-11e8-886f-d2cba961418b.png">

**Would you like to work on the issue?**

Yes

**Comment by Divy123** [comment]
I want to work on this.

**Comment by DNS-404** [comment]
I've already created a PR.
