### ISSUE TITLE
Incorrect sharing button in settings (when not logged in)

### ISSUE THREAD

**Issue by DNS-404** [fossasia/chat.susi.ai#1079]
**Actual Behaviour**

When not logged in, in the settings menu, we get "Share on Facebook" button but after logging in, we get "Share on Social Media" button.

**Expected Behaviour**

We should get "Share on Social Media" button when we're not logged in as well.
This is also maybe causing the current "Share on Facebook" button to not work as it was changed to "Share on Social Media" previously.

**Steps to reproduce it**

Go to https://chat.susi.ai/settings and have a look.

**Screenshots of the issue**

When not logged in - 
<img width="379" alt="screen shot 2018-01-29 at 11 08 45 pm" src="https://user-images.githubusercontent.com/31174685/35525408-61a337e4-054a-11e8-847f-4f6762170698.png">

When logged in -
<img width="336" alt="screen shot 2018-01-29 at 11 09 12 pm" src="https://user-images.githubusercontent.com/31174685/35525420-6928f792-054a-11e8-9980-ce226b2c32b3.png">

**Would you like to work on the issue?**

Yes

**Comment by VibhorCodecianGupta** [comment]
Hi, I think i resolved this in one of the commits in #1075 . Please have a look :)

**Comment by DNS-404** [comment]
Yeah that solves it. Nicely done :D
