### ISSUE TITLE
Extra space when resetting password

### ISSUE THREAD

**Issue by DNS-404** [fossasia/chat.susi.ai#1080]
**Actual Behaviour**

There is extra space between "New Password" and "Confirm New Password".
The "Change" button also is too close to "Confirm New Password".

**Expected Behaviour**

Spaces between "Current Password", "New Password", "Confirm New Password" and "Change" should be uniform.

**Steps to reproduce it**

Go to https://chat.susi.ai/settings and log in. Then click on "Password" and have a look.

**Screenshots of the issue**

<img width="299" alt="screen shot 2018-01-29 at 11 08 06 pm" src="https://user-images.githubusercontent.com/31174685/35525877-d24f6dc2-054b-11e8-9bf5-2b7bb0ab425f.png">

**Would you like to work on the issue?**

Yes

**Comment by ashupednekar** [comment]
I would like to work on this issue

**Comment by DNS-404** [comment]
I have already created a PR.
