### ISSUE TITLE
SUSI Logo on susi.skills.ai is hyperlinked to nothing.

### ISSUE THREAD

**Issue by himanshuc3** [fossasia/chat.susi.ai#1090]
**Actual Behaviour**

Currently SUSI logo at the top of skills.susi.ai is hyperlinked to home root **( href="/" )**. 

**Expected Behaviour**

Hyperlink should either be removed ( as it does not serve a purpose ) or hyperlink should either take the user to chat.susi.ai ( as it is the core feature according to me and the user may expect the site to take it there instead of having to in the menu every time to use chat ).

**Steps to reproduce it**

It is Simple.
Go to https://skills.susi.ai and click on SUSI logo at top-left corner.

**Screenshots of the issue**

![screen shot 2018-02-03 at 7 12 18 pm](https://user-images.githubusercontent.com/19166045/35767670-c1ef7b38-0916-11e8-9080-ddf80bc1025a.png)

**Would you like to work on the issue?**

Yes.

**Comment by SudhanvaMG** [comment]
Hey , i have finished this . I made the hyperlink connected to chat .Will make a PR soon .

**Comment by SudhanvaMG** [comment]
Hey @himanshuc3  Skills.susi.ai is a different website , the logo is linked to "/" root , which is skills.susi.ai , so clicking on it should stay on the same page rather than redirecting it to chat .

**Comment by Akshat-Jain** [comment]
@himanshuc3 I'm closing this issue as this is not relevant anymore. Thanks :-)
