### ISSUE TITLE
User should be greeted with some text in the beginning.

### ISSUE THREAD

**Issue by nityanandagohain** [fossasia/chat.susi.ai#1091]
**Actual Behaviour**

Currently when the user opens susi the chat area is blank.

**Expected Behaviour**

Instead of blank chat screen initially there should be some greeting's like "Hi! I am SUSI, Ask me anything"

**Steps to reproduce it**

open : https://chat.susi.ai/

**Screenshots of the issue**

![screenshot from 2018-02-04 10-36-49](https://user-images.githubusercontent.com/26831659/35774503-8cff03c2-0997-11e8-90c7-56034513d5ea.png)

**Would you like to work on the issue?**

Yes, I want to work on this.

**Comment by nityanandagohain** [comment]
@abishekvashok @bhaveshAn @rupav opinion's guys

**Comment by mariobehling** [comment]
This should be thought-through and followed up in the server repo.
