### ISSUE TITLE
Nice image/logo should be there on Contact us page inside first div like support page

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1116]
**Actual Behaviour**
No such image is there , It should be consistent for every page.
**Expected Behaviour**
Something like this on support page
![support](https://user-images.githubusercontent.com/30981465/36884575-e3d8280c-1e07-11e8-8508-ab8cadbbbec1.png)

**Would you like to work on the issue?**
Yes.

**Comment by dhirajj75** [comment]
@PrP-11 You have created same issue four times. I request you to close other repeated issues.

**Comment by PrP-11** [comment]
I am no longer working on this.
