### ISSUE TITLE
Width of first div of blog page is shorter than width of page

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1117]
**Actual Behaviour**
![div](https://user-images.githubusercontent.com/30981465/36884912-d02b1c68-1e09-11e8-9542-289d1b202f9b.png)

**Expected Behaviour**
Width should be relative not absolute.

**Screenshots of the issue**
![div2](https://user-images.githubusercontent.com/30981465/36884943-fa0eec3a-1e09-11e8-8372-f97f22568e92.png)

**Would you like to work on the issue?**

Yes.

**Comment by dhirajj75** [comment]
I would like to work on this issue. Can I?

**Comment by anshumanv** [comment]
@dhirajj75 good to see your interest, but I think @PrP-11 is already working on this?

**Comment by dhirajj75** [comment]
@PrP-11 are you still working on it?

**Comment by PrP-11** [comment]
Yes I am currently working on this and a couple of other issues together. So give me two three days if I am unable to do this then you can proceed. But I will appreciate some suggestions about this issue from you too.

**Comment by dhirajj75** [comment]
@PrP-11 It will be great if you solve it. :)
can you explain me the steps you have taken to solve it? So that I can help if I am able to.

**Comment by PrP-11** [comment]
1.) set the width of top nav bar to width of screen cus it is mainly causing the problem 
and set width of title div to 100% or browser width.
2.) we can disable horizontal scroll and make the complete page responsive to avoid any further problems in future.

**Comment by dhirajj75** [comment]
Have you applied the changes?Can you Provide Screenshots ? If yes then make a PR.
And why there is a need to disable scroll?

**Comment by PrP-11** [comment]
Issue #1117 and #1112 are caused due to same reason.
One of the code block is causing the problem
![problem](https://user-images.githubusercontent.com/30981465/37073929-dd222922-21ef-11e8-8ef4-0de0752d7fd3.png)
But I am searching from where this is happening.
overflow property is not working for this problem.

**Comment by PrP-11** [comment]
And I don't know why these blocks are made using table tag and not using div tag as the code blocks on top.

**Comment by PrP-11** [comment]
And the page is made responsive therefore I thought we can disable the horizontal scroll as if a page is responsive then we don't require horizontal scroll.
