### ISSUE TITLE
Readability of the code for different sections can be improved in the Overview.react.js file

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1122]
The code for the different sections of the Overview page should be spaced apart a little bit so as to improve the code readability. Also, some punctuation marks need to be closed.

**Would you like to work on the issue?**

Yes

**Comment by Orbiter** [comment]
I do not approve code reformatting without functional changes. This enhances the chances for further code conflicts for other functional changes and furthermore increases the danger for unwanted functional changes based on untested front-end behavior.
