### ISSUE TITLE
Refactor code base according to best practises

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#113]
**Actual Behaviour**

Currently, there are very few components of the app not following best practices.

**Expected Behaviour**

We should always follow best practices. l found this link useful for following best practices :https://github.com/airbnb/javascript
In future, we should follow this only.

**Would you like to work on the issue?**

Yes, sending PR.

**Comment by AnshulMalik** [comment]
This issue shouldn't be closed since there are still a lot of refactoring to be done.
