### ISSUE TITLE
Implement custom theme option on main page(not logged in)

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/chat.susi.ai#1134]
**Actual Behaviour**
There is no custom theme option on main page(not logged in).
**Expected Behaviour**
There should be a custom theme option on main page(not logged in).
**Screenshots of the issue**
NOT LOGGED IN:-
![screen shot 2018-03-05 at 11 14 47 pm](https://user-images.githubusercontent.com/31013104/36990470-cee3794a-20ca-11e8-8af0-c68c50e5f0a8.png)
LOGGED IN:-
![screen shot 2018-03-05 at 11 15 09 pm](https://user-images.githubusercontent.com/31013104/36990477-d6502ac0-20ca-11e8-9405-52cde1a11d3d.png)

**Would you like to work on the issue?**
YES

**Comment by mariobehling** [comment]
If at all theming should only be available for logged in users.
