### ISSUE TITLE
When "logged In" the theme setting custom option does not work properly 

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/chat.susi.ai#1136]
**Actual Behaviour**
When "logged in" the theme setting custom option does not do anything for now.
**Expected Behaviour**
The theme setting option should be linked to the colour pallet.
**Screenshots of the issue**
![screen shot 2018-03-06 at 4 41 23 pm](https://user-images.githubusercontent.com/31013104/37029448-87da632c-215d-11e8-87c8-c578cccddf34.png)

**Would you like to work on the issue?**
Yes

**Comment by dhirajj75** [comment]
I would like to work on this. Can I ?
@harsh-jindal

**Comment by harsh-jindal** [comment]
@dhirajj75 I'm working on this

**Comment by mariobehling** [comment]
Theming has low priority
