### ISSUE TITLE
Right arrow mark on each setting of the settings page not working properly

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/chat.susi.ai#1137]
**Actual Behaviour**
Right arrow mark on each setting of the settings page on clicking takes us to the first setting.
**Expected Behaviour**
Right arrow mark on each setting of the settings page on clicking should take us to the corresponding setting.
**Screenshots of the issue**
![screen shot 2018-03-06 at 7 42 16 pm](https://user-images.githubusercontent.com/31013104/37036652-5327cc28-2176-11e8-91a0-e4527dd6972b.png)
**Would you like to work on the issue?**
YES

**Comment by SudhanvaMG** [comment]
@harsh-jindal This seems to be working properly .There is no issue here .
