### ISSUE TITLE
BUG : Search button isn't working as expected

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1138]
**Actual Behaviour**

On the main chat screen, if you press the search button and search for anything, then it works as expected. But then if you ask Susi anything, it kind of disables the search functionality (it still shows 1/12 or 0/7 or something but the search phrase isn't highlighted in the chat screen. The "up" and "down" arrow functionality doesn't work either). To re enable the search functionality, you have to click on the "x" icon near the search box and then click on the "search" icon and then search for the phrase.

**Expected Behaviour**

Search functionality should work flawlessly.

**Screenshots of the issue**

For example, in this screenshot, no "hi" in the chat out of the 12 occurrences is highlighted.
![searchnotworking](https://user-images.githubusercontent.com/31135861/37037653-cb25e4ba-2178-11e8-997a-ebb347b7aaaa.png)

**Would you like to work on the issue?**

Yes

**Comment by dhirajj75** [comment]
Yes! Just state your problem might be I can help you with this.

**Comment by Akshat-Jain** [comment]
I'm not sure what files or what kind of changes would be required to fix this bug....

**Comment by dhirajj75** [comment]
Well for that you have to work on the whole code and understand its functionality by you own.
You have to look for the functionalities that triggers the search function and look for the mistake.

**Comment by Akshat-Jain** [comment]
Yeah, I've been trying to study the code and will continue trying. Thanks :D
