### ISSUE TITLE
Dark Theme Modifications

### ISSUE THREAD

**Issue by dhirajj75** [fossasia/chat.susi.ai#1142]
**Actual Behaviour**

The present dark theme is good. But we use Dark theme when working in low light or to save the battery Power and in present dark theme we have white background which is consuming more power and on the chat screen text is in greenish color which is readable but gives strain on eyes.

**Expected Behaviour**

1.Background color should be changed.
2.Text Color in Dark theme should be changed.

**Screenshots of the issue**

![before dark theme chat](https://user-images.githubusercontent.com/30864895/37132686-0c676092-22b5-11e8-8483-b763574cee79.png)

![before settings dark theme](https://user-images.githubusercontent.com/30864895/37132696-1dd0e966-22b5-11e8-999c-e21ad602e69b.png)

**Would you like to work on the issue?**

Yes!

**Comment by singhrohan62** [comment]
Hey @dhirajj75 just wanted to know if you are still working on this issue? I am also willing to work on the same issue so if you have come up with some ideas, do tell me so that we both can work for the same.

**Comment by psikarwal** [comment]
They are using MenuItem from Material-UI. Maybe [this link](http://www.material-ui.com/#/components/menu) will help @singhrohan62. :sunglasses:

**Comment by singhrohan62** [comment]
Hey @psikarwal kindly check if the requirements are met in the created PR. Thank you!
