### ISSUE TITLE
Add invert colour option in the menu 

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/chat.susi.ai#1148]
**Actual Behaviour**
No invert colour option in the menu.
**Expected Behaviour**
There should be a invert colour option in the menu.Clicking on it should toggle between the light and dark theme.
**Screenshots of the issue**
![screen shot 2018-03-10 at 7 36 46 pm](https://user-images.githubusercontent.com/31013104/37243086-1f0e767c-249a-11e8-8bb4-f9e57e5f382f.png)

**Would you like to work on the issue?**
YES

**Comment by mariobehling** [comment]
Out of scope currently.
