### ISSUE TITLE
Add Icons for email and password fields

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1149]
**Actual Behaviour**
No icons for email and password field
![icons2](https://user-images.githubusercontent.com/30981465/37256255-0532b6ca-257e-11e8-870e-25217b648741.png)

**Expected Behaviour**
Icons should be there on email and text fields
![icons](https://user-images.githubusercontent.com/30981465/37256263-122aae6e-257e-11e8-83fc-32386e649619.png)

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
@mariobehling The PR is already merged. It can be closed
