### ISSUE TITLE
Change the favicon.ico

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#115]
The existing favicon is the default created by create-react-app

![favicon](https://cloud.githubusercontent.com/assets/13276887/26618185/0dba70ba-45f7-11e7-85d3-ff587a1748b0.png)

Put a SUSI related favicon instead or simply remove the favicon

Will work on this :)

**Comment by uday96** [comment]
I tried this:
![favdem](https://cloud.githubusercontent.com/assets/13276887/26650380/d8517fc0-4666-11e7-948b-dfdb0a94601a.png)

Made a favicon with this:
![susi](https://cloud.githubusercontent.com/assets/13276887/26650408/e52c58c8-4666-11e7-9e31-32df23c97ebe.jpg)

It is hardly visible. Does there already exist a favicon for susi? sus.ai/chat uses loklak favicon.
We can try something like the above or just remove it.

@isuruAb @rishiraj824 @madhavrathi Suggestions please.

**Comment by chiragw15** [comment]
https://github.com/fossasia/susi_android/blob/development/app/src/main/ic_launcher-web.png Try this one and see if it looks good.

**Comment by chiragw15** [comment]
or https://github.com/fossasia/susi.ai/blob/gh-pages/assets/images/susi-logo-original.svg this with white background.

**Comment by uday96** [comment]
@chiragw15 Thanks, will try em :+1:

**Comment by uday96** [comment]
![f3](https://cloud.githubusercontent.com/assets/13276887/26690188/ffb19d20-4715-11e7-8dd6-7a84aea88cdc.png)
![f2](https://cloud.githubusercontent.com/assets/13276887/26690189/ffb34c1a-4715-11e7-85c1-9b9ab857d3bd.png)

Tried those, the first one seems okay for me. suggestions? Try the second one with white background too?

**Comment by rishiraj824** [comment]
first one looks good. @uday96

**Comment by uday96** [comment]
@daminisatya please suggest if https://cloud.githubusercontent.com/assets/13276887/26690188/ffb19d20-4715-11e7-8dd6-7a84aea88cdc.png is fine or should we try more.
