### ISSUE TITLE
Enlargement of the input box on typing a large message

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/chat.susi.ai#1154]
**Actual Behaviour**

When a user types a large message, the input box increases in size and hence overlapping the previous chat.

**Expected Behaviour**

The textbox should have a fixed size and a scroll bar should be added

**Steps to reproduce it**

Write a long message in the input box

**Would you like to work on the issue?**
YES

**Comment by Aakash-DD** [comment]
I think this no overlaping of the text, as i haven't seen the overlapping.

**Comment by stealthanthrax** [comment]
@Aakash-DD , I was talking about this overlapping , 
<img width="1237" alt="screen shot 2018-03-17 at 12 17 22 pm" src="https://user-images.githubusercontent.com/29942790/37552650-8ff2a472-29df-11e8-8c4d-cf98d98f5f91.png">

**Comment by Aakash-DD** [comment]
Yeah, this is a issue....
