### ISSUE TITLE
Profanity Filter in ChatApp

### ISSUE THREAD

**Issue by KrUciFieR-Jr** [fossasia/chat.susi.ai#1155]
**Actual Behaviour**

I wanted to explore a way to handle Cuss Words

**Expected Behaviour**

To implement a way to handle clean chats

**Screenshots of the issue**
![screenshot from 2018-03-15 23-08-30](https://user-images.githubusercontent.com/21988185/37481383-9d05cd94-28a7-11e8-8b38-5c08b0d6b140.png)

**Would you like to work on the issue?**

Yes I would definitely love to work on this

**Comment by Aakash-DD** [comment]
But i think it will work only for reserved and pre-defined words from the server.

**Comment by KrUciFieR-Jr** [comment]
There are common words which public uses, although implementation has already about 1750 profane words.

**Comment by Orbiter** [comment]
This should not be handled on the client side. All profanity responses must be coded as skill.
It is also a cultural thing what a "clean chat" should be.

**Comment by Orbiter** [comment]
This is neither a bug nor a valid feature on this side. If a user wishes to transport profanity to the server, it must be done. Filtering profanity on the client side will cause confusion because other clients don't work then the same way.
