### ISSUE TITLE
Dark theme colours inconsistent

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#1158]
![diamond](https://user-images.githubusercontent.com/10114907/37569345-422d6d5a-2ae1-11e8-9790-0842425c9eee.png)
The bubbles have two components a rectangle (diamont suit symbol) and a rectangle with rounded corners for the text container. There is a color difference of both items using dark theme. It should be always the same. In some displays the colour difference cannot be seen.

![farbdifferenz](https://user-images.githubusercontent.com/10114907/37569291-7435c910-2ae0-11e8-9117-461672ac4fd1.png)

**Comment by KrUciFieR-Jr** [comment]
I would like to take up this issue

**Comment by tabesin** [comment]
Go for it. It could be that the phenonemon relates to the rendering of the browser, meaning that it may well be that it is the same colour in the definition but the rendering supports different colour depth spaces. In that case the simplified colour needs to be selected which is actually displayed by the diamond suit rectangle. There are quite a lot of online ressources on web stable colours.
