### ISSUE TITLE
Add Send Button next to the message box.

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#116]
**Actual Behaviour**

Currently users have to press enter to send the message,But it is bit confusing for new users.

**Expected Behaviour**

But if we can add send button  next to the message box it is little bit easy for new users.

**Comment by madhavrathi** [comment]
@isuruAb I would like to work on this.

**Comment by rishiraj824** [comment]
@isuruAb @madhavrathi i thought this was part of Issue #104

**Comment by madhavrathi** [comment]
@rishiraj824 If that's the case then i think this should be closed. I'll contribute to your fork for button if that's ok.

**Comment by rishiraj824** [comment]
@madhavrathi you can start implementing the issue from this pull https://github.com/fossasia/chat.susi.ai/pull/124

**Comment by isuruAb** [comment]
@rishiraj824  sorry i didn't see that.may i close this ?

**Comment by rishiraj824** [comment]
@isuruAb It still needs to be implemented. Let it be open. I think @madhavrathi is still working on it as well.
