### ISSUE TITLE
Text in the search field resets when the case sensitivity is toggled 

### ISSUE THREAD

**Issue by SudhanvaMG** [fossasia/chat.susi.ai#1160]
**Actual Behaviour**

When the search text field is being used and during that time if the case sensitivity is toggled , the text in the search field resets to null , you have to type the search string again .

**Expected Behaviour**

When the case sensitivity is toggled , if there is a text in the search field , the search results should be shown without the text being reset to null and the user has to enter the search text again. 

**Steps to reproduce it**

1.Visit https://chat.susi.ai/ 
2.Converse with the bot .
3.Click on the search icon , and type a search string 
4.Click on the menu in top right , toggle case sensitivity

**Comment by akshatnitd** [comment]
Working on it
