### ISSUE TITLE
Clicking on the thumbs up/down icon redirects to that elements page

### ISSUE THREAD

**Issue by SudhanvaMG** [fossasia/chat.susi.ai#1162]
**Actual Behaviour**

In the Skills page , when you click on the thumbs up/down icon , it redirects to the elements page 

**Expected Behaviour**

When the icon is clicked , the value should be incremented and it should not redirect 

**Steps to reproduce it**

Go to https://skills.susi.ai/ and go the the skills tab . Click on any of the thumbs up/down icon on the cards.

**Comment by psikarwal** [comment]
can I work on this issue?  @SudhanvaMG

**Comment by SudhanvaMG** [comment]
@psikarwal  Hey , this issue is in susi skills repo please look into that and yes you can work on it .
