### ISSUE TITLE
Solving the problem of localization

### ISSUE THREAD

**Issue by daminisatya** [fossasia/chat.susi.ai#1167]
Please think of a way on how we can solve the issue of localization instead of manually translating the docs and content.

**Comment by vaibhavsingh97** [comment]
A script which call Google Cloud Translate API and convert all the docs and content in particular language. This can be done on rolling basis and can be reviewed by Language locals

**Comment by daminisatya** [comment]
Is the translate API free?

**Comment by ParthS007** [comment]
The Google Translation API is priced monthly based on usage. 

  | 0-1 billion characters
-- | --
Translation | $20 per 1,000,000 characters*
Language Detection | $20 per 1,000,000 characters*

If you store documents to be translated in Google Cloud Storage, or use other Google Cloud Platform resources in tandem with the Cloud Translation API, such as Google App Engine instances, then you will also be billed for the use of those services.

Source : https://cloud.google.com/translate/pricing

**Comment by vaibhavsingh97** [comment]
@daminisatya We can use `selenium` as an hack and can translate using google translate. I can write script for that.
