### ISSUE TITLE
SUSI not responding after execution of specific query

### ISSUE THREAD

**Issue by DipanshKhandelwal** [fossasia/chat.susi.ai#1168]
**Actual Behaviour**
SUSI not responding to this query
``` Recipe list for biryani ```
The skill that must be used - [cooking guide](https://github.com/fossasia/susi_skill_data/blob/master/models/general/Food%20and%20Drink/en/cooking_guide.txt)

**Expected Behaviour**
Must respond correctly and give output. And at least work if not able to execute this query.

**Steps to reproduce it**
+ Open [chat.susi.ai](http://chat.susi.ai/)
+ Ask SUSI - ``` Recipe list for biryani ```
+ Try to ask something else

**Would you like to work on the issue?**
Yes

**Comment by aashutoshrathi** [comment]
Also, it doesn't respond to any query after it! :cry: 
@anshumanv

**Comment by anshumanv** [comment]
Please help us solve the issue @aashutoshrathi to make it a better application, you are free to send in pulls at any point of time to have our maintainers review it.

**Comment by DNS-404** [comment]
@aashutoshrathi @anshumanv How do I fix it now? I can't send any message on it now.. 😞

**Comment by psikarwal** [comment]
@DNS-404, you have to hard reset. Or, you can change your IP address.

**Comment by DNS-404** [comment]
A restart worked. Thanks!
