### ISSUE TITLE
Two themes for chat application 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#118]
**Actual Behaviour**

Now the web chat application has only one theme "light theme". 

**Expected Behaviour**

If we can implement a dark theme and way to switch between those two themes that would be really helpful for users who like to dark theme.

**Would you like to work on the issue?**

I would like to work on this issue

**Comment by rishiraj824** [comment]
@isuruAb are you working on this?

**Comment by isuruAb** [comment]
@rishiraj824  yes
