### ISSUE TITLE
Feedback component throws an error when message text is undefined

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/chat.susi.ai#1181]
**Actual Behaviour**
Feedback component throws an error in console when message text received is undefined and none of the messages are displayed.

**Expected Behaviour**
There should be no console error and the message text can be changed to ""

**Steps to reproduce it**
Try producing a query whose query in undefined. I did by writing an invalid rule in a skill.

**Screenshots of the issue**

![screenshot from 2018-05-04 17-18-32](https://user-images.githubusercontent.com/12656846/39626506-d499fbba-4fbf-11e8-9545-9bba91fa819d.png)

**Would you like to work on the issue?**

Yes, I am working on it

**Comment by Akshat-Jain** [comment]
@akshatnitd As this has already been solved, I'm closing this issue. Thanks :-)
