### ISSUE TITLE
Implement option to clear chat history

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1186]
**Actual Behaviour**
Whenever we open the webchat it just shown the previous chats.

**Expected Behaviour**
But if you see assistants like siri etc they did not show them directly.

- We can make a show hide toogle button.
- For clearing history we can give options like clear history for the past hour, day etc.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Clear chat history might be needed, but we need to define this in detail, e.g. if we actually clear the log or just the screen.

I dont see that other personal assistants and messengers like Whatsapp have the option to hide and it clutters the UI. Therefore we dont need it at the moment.

**Comment by PrP-11** [comment]
@mariobehling we can give both options either to clear the screen or the log, but I am not sure whether clearing from the log will be a good idea or not. Can you suggest which one should be there( or both).
