### ISSUE TITLE
Clicking on SUSI.AI logo changes URL but the view is not rendered if you are logged in

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1189]
**Actual Behaviour**

The React routes are set up to reflect that click on the SUSI.AI logo should direct to a certain route. However, when I click on the logo, it changes the URL in my browser, but does not update anything being rendered in the DOM. Note that this is the case only when you are logged in. It works fine otherwise.

**Expected Behaviour**

Clicking on the logo should switch to route specified and update rendered component and URL accordingly.

**Steps to reproduce it**

Go to https://chat.susi.ai and log in with your email and password. Now go to About -> Blog (or any other link for that matter) (You can also open settings). Now click on the SUSI.AI logo on the top left. You'll notice that only the URL changes but the chat page is not rendered. The chat page is rendered if you click on the logo once more though. 

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
For me, the page changes too at once, are you having a slow internet connection?

**Comment by Akshat-Jain** [comment]
@anshumanv Ehh I guess I have a decent enough Internet connection. In any case, the loading of the site should start even if I have a slow connection, right ??

**Comment by anshumanv** [comment]
![peek 2018-05-08 08-19](https://user-images.githubusercontent.com/21009455/39735345-ccb42548-5298-11e8-9798-e8bccf2a643a.gif)

This is what I'm seeing, not sure :sweat_smile:

**Comment by Akshat-Jain** [comment]
![reactrouterissue](https://user-images.githubusercontent.com/31135861/39736072-152b0870-529c-11e8-81f9-98a0881c34bc.gif)
Not sure what's happening :sweat_smile:
