### ISSUE TITLE
Settings page for SUSI web chat application

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#119]
**Actual Behaviour**

Currently there are no any place to change settings of chat application. still there are no any changeable things in web chat application.

**Expected Behaviour**

We can make a separate settings page for : 

- switch between themes
- enable /disable chat history

**Comment by Orbiter** [comment]
This should be considered within a general concept how to sign up at the web chat and how to do a self-administration of personal settings. It should be considered within the AAA right concept as well.

**Comment by Fluepke** [comment]
Which settings do we need to store?
If it's only about themes, booleans, etc. why not a simple key value store?

**Comment by rishiraj824** [comment]
I think we can continue to implement this feature as just mere static settings, but as @Orbiter said we need to implement the AAA, login feature first to ensure the user is able to administer this in the personal settings. @Fluepke we can definitely store it as key values. It can be asked while in the sign-up process, and later on tin the settings. The themes as of now have been decided as `dark or light`, chat history can be a `boolean` type.

**Comment by Orbiter** [comment]
The ability to store Accounting data is already there:
- using the Authorization object which is handed over in  https://github.com/fossasia/susi_server/blob/development/src/ai/susi/server/AbstractAPIHandler.java#L100
- The Authorization object provides the Accounting object in https://github.com/fossasia/susi_server/blob/development/src/ai/susi/server/Authorization.java#L96
- The Accounting object extends JSONObject. You can therefore throw in whatever you want.

What I believe should be a 'general concept' is a object model that you put inside the Accounting JSON. Not to implement a key-value store. That framework exist.

Please read the code and follow the calls to see how that works.

**Comment by rishiraj824** [comment]
@Orbiter ok, will go through the code, this actually makes it easy for us. Thanks :+1:

**Comment by rishiraj824** [comment]
@isuruAb Instead of a separate page, we can have a settings icon on the top right of the header and a dropdown with all the options. What do you suggest?

**Comment by isuruAb** [comment]
@rishiraj824  since we haven't a big list of options to select we can add them into a dropdown 👍

**Comment by rishiraj824** [comment]
@uday96 @isuruAb The ability to switch the chat history has to be added first to add that as a setting.

**Comment by uday96** [comment]
I will work on adding chat history option. But we need a toolbar first right? @isuruAb is working on that.

**Comment by rishiraj824** [comment]
@uday96 created an issue #147 for the same. :+1:

**Comment by uday96** [comment]
@rishiraj824 :+1:
