### ISSUE TITLE
Can't send any query if the User is logged in

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1190]
**Actual Behaviour**

If you are logged in, then you are not able to send the query.

**Expected Behaviour**

The query should be sent and a proper response should be received.

**Steps to reproduce it**
Go to https://chat.susi.ai and log in with your email and password. Now try to send any query you like. You'll see that you are not able to send your query.

**Would you like to work on the issue?**

Yes

**Comment by Akshat-Jain** [comment]
@anshumanv Are you logged in ??

**Comment by Akshat-Jain** [comment]
@anshumanv I am unable to send query on my laptop browser (checked with Chrome and Firefox), and even on my mobile browser (Chrome). Even my friend got the same issue when he was logged in.

**Comment by anshumanv** [comment]
> @anshumanv Are you logged in ??

Yes, just tried after logging in, anyways see if others are able to reproduce this issue.

**Comment by DNS-404** [comment]
I too am able to send queries when logged in.

**Comment by DNS-404** [comment]
Maybe this issue is somehow related to https://github.com/fossasia/chat.susi.ai/issues/1168

**Comment by Akshat-Jain** [comment]
@DNS-404 Maybe

**Comment by akshatnitd** [comment]
Please check if there are some console errors or not. If yes, please post a screenshot of it

**Comment by akshatnitd** [comment]
@Akshat-Jain Understood the issue. It is solved in #1182

**Comment by akshatnitd** [comment]
@Akshat-Jain Understood the issue. It is solved in #1182. It happens when the message text is undefined.

**Comment by Akshat-Jain** [comment]
@akshatnitd Yeah, #1182 solves this issue as well. Thanks :smile:
