### ISSUE TITLE
Custom theme must be applied to the settings page also

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1200]
**Actual Behaviour**
When applying a custom theme on chat interface of chat.susi.ai, it is not applied on the settings page.

**Expected Behaviour**
Theme of settings page should also change.

**Steps to reproduce it**
Apply any custom theme on chat interface and then open the settings page.

**Screenshots of the issue**

Applied random theme

![theme](https://user-images.githubusercontent.com/30981465/39953398-e2be53ee-55c8-11e8-8c08-188cbafdbc5f.png)

But light theme on settings page.

![theme2](https://user-images.githubusercontent.com/30981465/39953401-ea79deaa-55c8-11e8-9054-59b7404708a8.png)

**Would you like to work on the issue?**
Yes

**Comment by prateekiiest** [comment]
@PrP-11 when you are on the overview page or support page or any other page other than the chat page,
you will not find themes icon on the topbar dropdown menu.

Theme is only available as of now in the chat application. And moreover I think that is only desirable. SUSI has its own theme of blue and white 

@mariobehling your thoughts on this issue?
