### ISSUE TITLE
Make provision for Google Sign in during Login  - FUTURE PLAN

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/chat.susi.ai#1213]
**Actual Behaviour**

Only username and password provided as of now.
No sign in through google account

**Expected Behaviour**
A new option for sign in with Google account

Users can use SUSI to connect with their google account and other apps related to their account.
As a future plan, including something like notifications that reminds you in your mail can be done.

For example
```
Me: SUSI, book time on google calendar at  this date
SUSI : Ok, sure

SUSI: send notifications to your mail about meeting.

```

**Would you like to work on the issue?**

This will be a major task. So I am willing to do this along with other developers

**Comment by PrP-11** [comment]
@prateekiiest this needs to be implemented on susi server first and then on accounts. I am already working on this [here](https://github.com/fossasia/accounts.susi.ai/issues/242) and is one of the major component of my gsoc project this year. This is a part of [this](https://github.com/fossasia/labs.fossasia.org/issues/194) issue at labs.fossasia.org. I think we can collaborate on this.

**Comment by prateekiiest** [comment]
Sure @PrP-11
