### ISSUE TITLE
Logout link always redirect default to chat.susi.ai

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/chat.susi.ai#1217]
When anyone logs out being on any page (for example chat.susi.ai/overview) it should redirect to chat.susi.ai/overview instead of redirecting to default chat.susi.ai

**Comment by PrP-11** [comment]
@prateekiiest SUSI gives us an option to chat anonymous therefore redirecting to chat makes more sense. Thanks. :smile:

**Comment by prateekiiest** [comment]
Umm, but on a normal basis dont you think if any user is going through a particular info (say in the overview page), if he/she wishes to logout, then he/she can continue reading the info instead of jumping into the chat app directly

**Comment by Akshat-Jain** [comment]
@prateekiiest I also think that redirecting to the chat screen makes more sense.
@DNS-404 @akshatnitd @anshumanv Thoughts ?

**Comment by anshumanv** [comment]
Agreed with @Akshat-Jain, since in any app like twitter/fb when you're on any page and you logout, you'll be redirected to index or login page which in this case is the chat screen.

**Comment by DNS-404** [comment]
Agreed with @Akshat-Jain and @anshumanv
