### ISSUE TITLE
Play audio & video from a Youtube stream

### ISSUE THREAD

**Issue by Orbiter** [fossasia/chat.susi.ai#1218]
**Expected Behaviour**

When susi returns a audio_play action, the hardware which the user is using must play the given audio or video source.

**Steps to reproduce it**

Ask susi "open the pod bay door" - https://api.susi.ai/susi/chat.json?q=open+the+pod+bay+door
You will get the following action object:
```
"actions": [
      {
        "type": "audio_play",
        "identifier_type": "youtube",
        "identifier": "7qnd-hdmgfk"
      },
      {
        "language": "en",
        "type": "answer",
        "expression": "I'm sorry, Dave. I'm afraid I can't do that."
      }
    ]
```
or
```
"actions": [
      {
        "type": "video_play",
        "identifier_type": "youtube",
        "identifier": "7qnd-hdmgfk"
      },
      {
        "language": "en",
        "type": "answer",
        "expression": "I'm sorry, Dave. I'm afraid I can't do that."
      }
    ]
```

This means that susi shall do (in that order):
* if "type" is "audio_play": play the audio from the youtube video with the given ID. Use the "identifier_type" to see that the "identifier" object denotes a youtube ID
* if "type" is "video_play": play the video from the youtube video with the given ID. Use the "identifier_type" to see that the "identifier" object denotes a youtube ID
* write out the answer

**Documentation of the audio_play action**

see issue https://github.com/fossasia/susi_linux/issues/117

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by PrP-11** [comment]
@Orbiter I will work on it.Thanks.
