### ISSUE TITLE
Provide Themes even when Signed off

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/chat.susi.ai#1220]
**Actual Behaviour**

Currently when one chats anonymously then there is no option for adding any themes.

**Expected Behaviour**

Provision for theme for anonymous user

**Steps to reproduce it**

- Logout
- Click on the right corner to see if the themes icon is there.

**LogCat for the issue**

**Screenshots of the issue**

![screenshot 99](https://user-images.githubusercontent.com/16035442/40436520-bf3ea2fa-5ed0-11e8-94c5-6f64c2061442.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please see here: https://github.com/fossasia/chat.susi.ai/pull/1221#issuecomment-391732730
