### ISSUE TITLE
Display list of connected devices on the Web Client

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1222]
**Actual Behaviour**

There is no section for Devices on the web client.

**Expected Behaviour**

The devices which are linked to the logged in user should be fetched from the APIs created in [susi_server #740](https://github.com/fossasia/susi_server/pull/740) and then be displayed on the web client.

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please implement font and design following design of other tabs and use International English punctuation.

**Comment by mariobehling** [comment]
One of the last changes resulted in the left sidebar not being aligned on top in the settings area. Please help to resolve this in following PRs as well. Thanks.

![screenshot from 2018-05-28 01-01-25](https://user-images.githubusercontent.com/1583873/40591506-d309faf6-6212-11e8-8586-44a089a364f9.png)

**Comment by Akshat-Jain** [comment]
@mariobehling Sorry, I did not understand what you meant with regards to font and design aspects. I am using the same font which is used all throughout the Settings page, that is "Roboto". Also, where do I need to use International English punctuation. Can you please explain it ? Thanks !
