### ISSUE TITLE
Implement Account Tab in Settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1233]
Account Info should be as in screenshot below.

Ensure this data is stored on the server backend.

![screenshot from 2018-05-25 01-04-01](https://user-images.githubusercontent.com/1583873/40517820-a27fbc70-5fb7-11e8-9bfb-8809eb857afc.png)

**Comment by PrP-11** [comment]
@mariobehling working on it.

**Comment by mariobehling** [comment]
Please do all required changes to finalize this issue including:
* Move language option here (and take out Language Settings tab)
* Add timezone option

**Comment by PrP-11** [comment]
@mariobehling To implement change email address, every time a user changes their email, a call to the server is made which verifies whether the email address is in their database or not. I think an api on server should be implemented first.
