### ISSUE TITLE
Implement Tab "Password" in settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1234]
Add tab in "Password" in settings as below.

![screenshot from 2018-05-25 01-07-20](https://user-images.githubusercontent.com/1583873/40518124-3bb1ea98-5fb9-11e8-9204-9e9514685230.png)

**Comment by PrP-11** [comment]
@mariobehling Working on it.

**Comment by prateekiiest** [comment]
I just started out on it and I have changed only the Current Password layout.
@PrP-11 we can collaborate on this

**Comment by PrP-11** [comment]
@prateekiiest I was already working on this and the other issue. This is not how we work. Please follow guidelines and best practices followed at fossasia. If someone is already working on an issue than you should focus on other important issues. If he/she has not done anything for atleast some days  than you can ask them if they are still working or not. These issue are not big to be solved in collaboration.
