### ISSUE TITLE
The voice used by SUSI is not the same as Google's voice

### ISSUE THREAD

**Issue by batbrain7** [fossasia/chat.susi.ai#1238]
**Actual Behaviour**

The voice used on clicking the mic is not the same one as that used by google.

**Expected Behaviour**

The voice used by SUSI should be the same as that of google

**Steps to reproduce it**

Click on the mic icon on the chat and say something and wait for the response.

**Would you like to work on the issue?**

No, anyone can take up this issue

**Comment by akshatnitd** [comment]
I would like to take this up

**Comment by akshatnitd** [comment]
@mariobehling We can achieve this by changing the values of speech speed and pitch from the Settings menu. Should I change the default values to match Google Assistant's voice ?

**Comment by mariobehling** [comment]
@Akshat-Jain Yes, please go ahead and update us on the progress.

**Comment by fliptrail** [comment]
Since the issue is still open, I would like to work on it.

**Comment by fliptrail** [comment]
I think that getting exact same voice as Google Assistant would be very difficult due to the fact that it used Google Text To Speech Wavenet model.
https://cloud.google.com/text-to-speech/docs/basics
However, it's rate and pitch could be reduced to make it sound more "humanlike"
