### ISSUE TITLE
Improve speed of drop-down menu 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1241]
Please speed up the expansion of the drop-down menu similar to the user menu in Facebook.

Also add "Botbuilder" in the chat drop-down below "Skills" for logged in users.

**Comment by mariobehling** [comment]
Please open the same in all SUSI.AI components and implement it in the same way afterwards. Thanks.

**Comment by anshumanv** [comment]
@Akshat-Jain can you please help lookup about the dropdown speed? 

It has something to do with the transitionDuration prop on the Popover component - https://material-ui.com/api/popover/

I've been trying that since an hour, doesn't seem to work.

**Comment by Akshat-Jain** [comment]
@anshumanv The official documentation of the Popover component didn't have any Props to customise the duration of the animation in terms of milliseconds. It had Prop only to either turn the animation on or off completely. The transitionDuration prop which you were talking about was for different version of material-ui components.
@mariobehling Please review. Thanks :-)
