### ISSUE TITLE
Simplify Login and Sign up boxes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1243]
Please simplify the login and signup boxes. Take out icons and check the approach of Facebook to keep it more simple.

![screenshot from 2018-05-25 21-39-32](https://user-images.githubusercontent.com/1583873/40565524-3bdd971a-606d-11e8-8cb1-43942b99946b.png)

![screenshot from 2018-05-25 21-42-52](https://user-images.githubusercontent.com/1583873/40565532-3fbffc42-606d-11e8-8914-bd97c137ef6a.png)

**Comment by prateekiiest** [comment]
@mariobehling I  would like to work on this

**Comment by mariobehling** [comment]
Sure, go ahead. Thanks.

**Comment by DNS-404** [comment]
@mariobehling I would like to work on this.

**Comment by anshumanv** [comment]
Working on this.
