### ISSUE TITLE
Remove "Back To Chat" from Settings menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1257]
1. Please remove "back to Chat" from settings menu.
2. Take out the word "settings" from all areas on the menu.

![screenshot from 2018-05-28 01-34-54](https://user-images.githubusercontent.com/1583873/40591768-7366662a-6217-11e8-8f77-bbb58931ae4c.png)

**Comment by akshatnitd** [comment]
I am taking this up
