### ISSUE TITLE
Add the logged in email to the settings top header same as on chat page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1258]
Add the logged in email to the settings top header same as on chat page.

![screenshot from 2018-05-28 01-43-47](https://user-images.githubusercontent.com/1583873/40591855-963c3b9c-6218-11e8-95ee-a3fa02cfa148.png)

**Comment by AnupKumarPanwar** [comment]
I'll work on it.

**Comment by Akshat-Jain** [comment]
This issue has been solved already in https://github.com/fossasia/chat.susi.ai/pull/1295. Hence, closing this issue. Thanks :-)
