### ISSUE TITLE
Change "Share on Social Media" to "Apps" and implement social media connections

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1272]
Please change the "Share on Social Media" and rename this tab "Apps". Implement accounts of social networks to be connected here.

* [ ] Facebook
* [ ] Twitter
* [ ] Google

These connections need to be implemented on the server.

![screenshot from 2018-05-29 12-44-01](https://user-images.githubusercontent.com/1583873/40654301-28aa7eaa-633e-11e8-90d8-738c6de4a77e.png)

**Comment by iambk** [comment]
Can I work on this?

**Comment by sarnava1** [comment]
@tabesin @akshatnitd   changes need to be implemented in the server means?
