### ISSUE TITLE
Speech Settings not working on chromium

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/chat.susi.ai#1273]
**Actual Behaviour**
The Language option in Speech Settings doesn't work. 

**Expected Behaviour**
It should work and the speech language should get updated. Also, move the Language settings contents from the dialog box to the Speech tab itself.

**Steps to reproduce it**
Go to Settings > Speech 

**LogCat for the issue**
**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Please extend settings area's height instead of adding a scroll bar.

**Comment by akshatnitd** [comment]
@mariobehling Opened #1286 for the issue
