### ISSUE TITLE
Show no results found after a web search

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#128]
**Actual Behaviour**

No response is generated after the web search and the response is left blank.

**Expected Behaviour**

An appropriate message should be sent once the response is empty.

**Steps to reproduce it**

query `baseless argument`

**Screenshots of the issue**
![screenshot from 2017-06-03 03 18 40](https://cloud.githubusercontent.com/assets/11540785/26746122/8f8e6202-480b-11e7-9e0a-68cc2ef019ea.png)

**Would you like to work on the issue?**
Feel free to work on this issue.

**Comment by uday96** [comment]
I will work on this :smile:

**Comment by uday96** [comment]
should the response be a Plain text like "NO Result Found" ?
Or a websearch tile saying "NO Result Found" like in the android App?

**Comment by uday96** [comment]
Is this fine?

![noresults](https://cloud.githubusercontent.com/assets/13276887/26747910/d22900da-4816-11e7-8b68-824cd9b35da7.png)

**Comment by rishiraj824** [comment]
@uday96 A simple text message would look good. :smile:
