### ISSUE TITLE
Add feature to remove all devices of a User

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1284]
**Actual Behaviour**

Currently, there is no way to remove all connected devices of a User.

**Expected Behaviour**

The User should be able to remove all of his connected devices.

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please first implement "add device". This is probably challenging and should be first implemented in the mobile apps. In the meantime, please focus on what we discussed in our meetings and get features related to settings, accounts, bots and skills working. Thanks.

**Comment by Akshat-Jain** [comment]
I think this can be closed now, considering recent progress of the Devices tab. Thanks :-)
