### ISSUE TITLE
Show a loading gif while fetching web result or getting response.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#129]
**Actual Behaviour**

Currently, there is no such loading icon a person has to wait for a response

**Expected Behaviour**

There should be a material theme based loading icon to make sure the user knows that the response was generated. It should disappear as soon as the response is generated.

**Steps to reproduce it**

Search for `get me a meme`, `random gif` or any response which requires a web result.

**Would you like to work on the issue?**

Anyone is free to take it up.

**Comment by rishiraj824** [comment]
Working on this :)

**Comment by uday96** [comment]
I will work on this :+1:
