### ISSUE TITLE
Inconsistent styling of Login and Signup forms

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1290]
**Actual Behaviour**

Currently, the styling of the Login and Signup forms on https://chat.susi.ai isn't consistent, and is also inconsistent with that on https://skills.susi.ai

**Expected Behaviour**

The styling should be consistent for Login and Signup forms.

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
This is closely related to - https://github.com/fossasia/chat.susi.ai/issues/1243 Please see.
