### ISSUE TITLE
Implement a Message Search feature inside the chat similar to Android and iOS client

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#130]
**Actual Behaviour**

Once the login system is integrated a person should be able to search his messages. This feature is static and is therefore independent of the login feature. There is no such feature now.

**Expected Behaviour**

A person should be able to search his previous messages

**Would you like to work on the issue?**

Anyone can take this up.

**Comment by uday96** [comment]
Will work on this :+1:
