### ISSUE TITLE
Provision for setting background cover image in Chat

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/chat.susi.ai#1311]
**Actual Behaviour**

Currently unlike whatsapp, there is no provision in SUSI chat app to upload a background cover pic of choice by the user

**Expected Behaviour**

Set a background image with an option for upload

**Steps to reproduce it**
NA

**LogCat for the issue**
NA

**Screenshots of the issue**
NA

**Would you like to work on the issue?**

Yes.

But I would like to discuss first with mentors

**Comment by AakashMallik** [comment]
I would like to pitch in. Let us discuss this further.
