### ISSUE TITLE
User can login from different accounts on SUSI web chat and CMS simultaneously

### ISSUE THREAD

**Issue by arundhati24** [fossasia/chat.susi.ai#1326]
**Actual Behaviour**

Currently, there are following issues :

The user has to login twice if he chooses to switch to the SUSI webchat from the Skill CMS and vice versa.
As the user has to login twice, s/he can use two different accounts to use the chat and Skill CMS simultaneously.

**Expected Behaviour**

This is probably happening because the web chat and Skills CMS are dealt with differently. We need to have a mechanism wherein the user should be asked to login only once and hence should be allowed to use a single account to use both, the chat and the CMS, simultaneously. Also, the user should not be prompted for login twice. If s/he has logged into the SUSI webchat, then s/he should automatically be logged into the Skills CMS with the same account and vice versa.

**Would you like to work on the issue?**

No, anybody is free to take this up.

**Comment by arundhati24** [comment]
Same issue has been opened on Skills CMS too. [#690](https://github.com/fossasia/susi_skill_cms/issues/690)

**Comment by akshatnitd** [comment]
I ll take this up
