### ISSUE TITLE
Display name of the user instead of email on the top bar

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1337]
**Actual Behaviour**

Currently, the email is being displayed on the top bar.

**Expected Behaviour**

We should display the name of the user instead of the email, now that the name of the user is being stored in the Accounting object of the user (https://github.com/fossasia/chat.susi.ai/pull/1331).

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
I think email is better

**Comment by PrP-11** [comment]
@fragm3 I agree with @Akshat-Jain , User name is more preferable here. For example in github itself we see username everywhere and not the email directly.

**Comment by fragm3** [comment]
@PrP-11 don't compare SUSI with GitHub, both are separate things. What difference would it make if it displays username? Thats not what SUSI is about, thoughts @mariobehling?

**Comment by DNS-404** [comment]
I think displaying username is better than displaying email.

**Comment by anshumanv** [comment]
Username is more preferable.

**Comment by akshatnitd** [comment]
@fragm3 I think, we should go with username/ Name. Showing the name of the user, in place of email is better UX IMO. We can't really show email everywhere and should limit it to places only where required.
