### ISSUE TITLE
Navigation problem in skills.susi

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1338]
**Actual Behaviour**

On clicking the SUSI logo on [Skills](https://skills.susi.ai/) page, it stays on Skills page

**Expected Behaviour**

On clicking the SUSI logo on [Skills](https://skills.susi.ai/) page, it should direct to chat page, same when we are in dashboard. Will have to implement this on the SUSI

**Would you like to work on the issue?**

YES

**Comment by anshumanv** [comment]
I'm not entirely sure about this.

**Comment by mariobehling** [comment]
@fragm3 Right now we follow another approach. It will direct to the main page of the service. We need to think this through, but other things - actual features - have a priority at the moment.
