### ISSUE TITLE
Copy chat message to clipboard

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1340]
**Expected Behaviour**

Add feature to copy chat message to clipboard

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
This feature is out of scope currently and also does not match other services features set.

**Comment by fragm3** [comment]
@mariobehling please have a look at this: [pr-1340-fossasia-susi-web-chat.surge.sh](pr-1340-fossasia-susi-web-chat.surge.sh) I have already created that option

**Comment by mariobehling** [comment]
Good job. However, it is unclear if this adds functionalities that user really need. Users can already easily copy text in the browser. It is unlikely that this feature will help to increase the reach of users. Please help to implement features that are more closely related to the service itself. Thank you.
