### ISSUE TITLE
Fix links to mobile clients

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1341]
Right now we only have Android. Please fix the link to the play store on the overview page.

![screenshot from 2018-06-15 19-50-01](https://user-images.githubusercontent.com/1583873/41482551-37aff650-70d6-11e8-877c-c3bdaa7c903e.png)

**Comment by fragm3** [comment]
Would like to do

**Comment by fragm3** [comment]
In Safe and secure section, Github link and open source link also needs to be fixed.
