### ISSUE TITLE
Rearrange hamburger menu

### ISSUE THREAD

**Issue by DNS-404** [fossasia/chat.susi.ai#1346]
**Expected Behaviour**

- "Dashboard" needs to be on the top.
- "About" will be on the bottom just above logout.
- "Botbuilder" needs to be added back at the current place of "Dashboard".

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please ensure this works in all routes, e.g. also in the route `/settings`.

**Comment by DNS-404** [comment]
Okay
