### ISSUE TITLE
Implement new features in the Devices tab in settings

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1361]
As discussed in the meeting, the following things need to be taken care of in the Devices tab - 

- [x] Remove the 1st column of the table and make Device name as the 1st column
- [x] Improve alignment of the table in the Devices tab to match the styling of other tabs
- [x] Implement "geolocation" and "room" columns in the table in the Devices tab
- [x] Use data from API for the "geolocation" and "room" columns
- [x] Implement remove option in devices tab.
- [x] Implement edit device option in devices tab.
- [x] Implement a confirmation dialog while removing devices
- [ ] Implement 2 sections below "Devices" - Table view and Map view

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
@Akshat-Jain don't write `fixes` unless the PR solves the issue completely.
