### ISSUE TITLE
Check for message id fails due to timestamp suffix

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#137]
**Actual Behaviour**

The check corresponding to the message id is initialized with a new timestamp during the test case preparation, causing unnecessary fails while running the test.

**Expected Behaviour**

The check fails every time because the id of the message changes according to the time stamp. 
The test should not fail because of this issue. 

**Steps to reproduce it**

`npm run test`

It might not fail sometimes since the timestamp matches, try after sending some messages and keep the server running.

**LogCat for the issue**

```
FAIL  src/_tests_/utils/ChatMessageUtils.js
  ● check getSUSIMessageData util

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      "m_1496450220196"
    Received:
      "m_1496450220197"
      
      at Object.<anonymous> (src/_tests_/utils/ChatMessageUtils.js:18:35)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at handleMessage (internal/child_process.js:689:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

 PASS  src/_tests_/components/MessageComposer.js (8.206s)
 PASS  src/_tests_/components/ChatApp.js (12.214s)
 PASS  src/App.test.js (13.347s)
 PASS  src/_tests_/components/MessageSection.js
 PASS  src/_tests_/components/ThreadSection.js

Test Suites: 1 failed, 5 passed, 6 total
Tests:       1 failed, 7 passed, 8 total
Snapshots:   0 total
Time:        19.986s
Ran all test suites.
```

**Would you like to work on the issue?**

Anyone is free to take up the issue

**Comment by uday96** [comment]
Should the test be removed?
Ideally, we are replacing the old timestamp with the new one after the message is proccessed, so there doesnt have to be a comparision check for the two IDs right?

**Comment by rishiraj824** [comment]
@uday96 Yes, it should as the instance of the new message id is causing the fail and the check is redundant in some way.
