### ISSUE TITLE
Bug in signup form validation

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1371]
**Actual Behaviour**
There is a bug in signup form validation, whenever a user enters same password on new password and verify password section and then changes the new password, the form validation is still set true.

**Expected Behaviour**
This bug should not be there

**Steps to reproduce it**
- Type 1234567 in new password tab
- enter the same password in verify tab
- make the new password tab to 12345677

**Screenshots of the issue**
Works fine if both password are different from beginning
![s3](https://user-images.githubusercontent.com/30981465/41737584-5a3ee722-75ad-11e8-81d2-8ea37420e9c7.png)

But once the form is validated it doesn't revalidated again on changing new password
![s2](https://user-images.githubusercontent.com/30981465/41737771-d6d72484-75ad-11e8-8901-fdab7fcbf999.png)

**Would you like to work on the issue?**
Yes

**Comment by fragm3** [comment]
@PrP-11  working on this, I would like to work on this.

**Comment by PrP-11** [comment]
Sure @fragm3 you can work on it
