### ISSUE TITLE
Make StaticAppBar component responsive 

### ISSUE THREAD

**Issue by anshumanv** [fossasia/chat.susi.ai#1376]
**Actual Behaviour**
Top bar is not responsive properly

**Expected Behaviour**
It should be responsive

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/21009455/41788794-84422b16-766a-11e8-818d-1a848a775050.png)

**Would you like to work on the issue?**
No

**Comment by akshatnitd** [comment]
It is responsive now
