### ISSUE TITLE
Organise all the tests inside 'describe' functions

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1411]
**Actual Behaviour**

Currently, all the tests have 'it' functions directly written inside them.

**Expected Behaviour**

All the 'it' functions should be organised inside an appropriately named 'describe' function. This would also allow to focus on specific parts of the components at a time when more 'it' functions are added in the tests.

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
Nice
