### ISSUE TITLE
Giving response according to action defined in skill (where type is table)

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#142]
**Actual Behaviour**

If the user who made some skill of action type: table,and he defines length of response he wants to show, then only that much result should be rendered.

**Expected Behaviour**

Right now the whole response from api is rendered.

**Sample issue**

Like this skill for example http://dream.susi.ai/p/images , for query "latest images", length defined is 5, but response is showing 10 images in table, so we should slice our table rows accordingly.

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
We need the length attribute to be specified in the api response also to be able to access it and render the table accordingly from the client side.
I guess the implementation from the server side is still pending for this issue.

**Comment by madhavrathi** [comment]
@uday96 I was also having problem achieving this feature, I guess we cannot access variables defined in skill unless it comes as a response from server.
I guess this should be closed until server team has accomplished such feature.
