### ISSUE TITLE
Add Material UI App Bar 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#143]
**Actual Behaviour**

Now the top bar that shows "SUSI" is made with raw HTML and CSS

**Expected Behaviour**

we can use Material UI App Bar instead of existing bar.
material UI app bar : http://www.material-ui.com/#/components/app-bar
current App-bar:
<img width="694" alt="screen shot 2017-06-04 at 12 58 54 pm" src="https://cloud.githubusercontent.com/assets/7692626/26759776/e13a09d8-4925-11e7-89eb-0b6ee0531abf.png">

**Would you like to work on the issue?**

I would like to work on this

**Comment by rishiraj824** [comment]
@isuruAb It will be nice if its made a part of #119. So in total we have 3 changes
- A material bar
- A settings icon (gear) brings out 2 options 
   - Change theme (dark, light)
   - Toggle between chat history ( Referenced in #119 again)
- A search icon with the ability to perform a search within the chat ( #130 )
@uday96 @isuruAb @madhavrathi
