### ISSUE TITLE
UI Improvements (User Message Text) in Mobile

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/chat.susi.ai#1432]
**Actual Behaviour**

![chat susi ai_](https://user-images.githubusercontent.com/20199181/42448272-54a0b34a-839a-11e8-99d5-db4514e25434.png)

There is no margin right in user message while the reply has some margin on left.

**Expected Behaviour**
![chat susi ai_ 1](https://user-images.githubusercontent.com/20199181/42448337-7ee84fd2-839a-11e8-8020-22bd7e314527.png)

**Steps to reproduce it**
```
.message-container.You
```

**Would you like to work on the issue?**
Yup!

**Comment by Akshat-Jain** [comment]
@niteshkumarniranjan I'm unable to reproduce the same issue. It looks just fine for me.
@anshumanv @akshatnitd @DNS-404 @PrP-11 Can you also please check once if this issue exists for you? Thanks :-)

**Comment by niteshkumarniranjan** [comment]
Sorry for the inconvenience. I think this was because of the browser cache. It's fine.
