### ISSUE TITLE
Implement Login and Accounting

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#144]
Login and Accounting is not yet implemented. 

There are some prototype components with Angular JS here http://api.susi.ai/apps/applist/index.html

Please implement login and accounting features in the chat web app.

**Comment by rishiraj824** [comment]
@mariobehling Login and Chat should on the same route or different?

**Comment by mariobehling** [comment]
Not sure, what you mean with route. Login should happen in the same way it happens with the Android client. The user should be able to access the data. If you want to know a specific link, maybe use chat.susi.ai/login.

**Comment by rishiraj824** [comment]
Okay. I was just asking about the route for login or chat. We'll stick to http://chat.susi.ai for both page like in all major clients.

**Comment by rishiraj824** [comment]
@uday96 @mariobehling @isuruAb @madhavrathi 
I was thinking of the following sub-issues for this issue #144
- One is to have a UI (Using material-ui.com) having functionalities for login/signup/forgot password, which can be our first screen at http://chat.susi.ai
- Next, we authenticate the details of a new user(Sign Up) using a request to http://api.susi.ai/aaa/signup.json?signup=EMAIL&password=PASSWORD which shall generate an email, so equivalent message can be shown. Once the users confirm the email they can log in with their credentials.
Sample Response
```
{
  "session": {"identity": {
    "type": "host",
    "name": "106.222.189.133",
    "anonymous": true
  }},
  "message": "You successfully signed-up! An email with a verification link was send to your address."
}
```
- The login page, goes through the following route - http://api.susi.ai/aaa/login.json?type=access-token&login=EMAIL&password=PASSWORD
Sample Response
```
{
  "access_token": "token_value",
  "session": {"identity": {
    "type": "host",
    "name": "106.222.189.133",
    "anonymous": true
  }},
  "valid_seconds": 604800,
  "message": "You are logged in as name@example.com"
}
```
Valid_seconds is the amount of time, one has to create the session for, after that, the session closes and the user is logged out.
- After Login it opens Chat screen with the modified URL for query, route - http://api.susi.ai/susi/chat.json?timezoneOffset=-330&q=hi&access_token=token_value
Middlewares will be there for the chat screen, one cannot access it without logging in. Please follow up on the points that I have missed and elaborate more on this issue. A lot of code refactoring also needs to be done, as all the query models will change.

**Comment by uday96** [comment]
@rishiraj824 The login page also can have a remember me option which if selected, the route will be - http://api.susi.ai/aaa/login.json?login=EMAIL&password=PASSWORD&type=cookie.

From the LoginService.java:
The following parameter combinations are valid:
  - checkLogin=true	# check the login status
  - logout=true		# end the current session
  - login,password,type(session | cookie | access_token)	# login with password. session starts a browser session, cookie sets a long living cookie, access_token creates an access_token and returns it with the server reply
  - login,keyhash	# first part of login via public/private key handshake. The keyhash is displayed on key registration
  - sessionID,response	# second part. sessionID is part of the server reply of the first part. response is a signature of the challenge, also part of the server reply.

**Comment by rishiraj824** [comment]
@uday96 We can create a sub-issue for that feature as well.

**Comment by uday96** [comment]
1. So the first step will be creating a UI for the landing page
2. Implementing signup feature along with UI and link it to the signup button in the login page
3. Implement the login feature.

But how do we test it if we are using the same url http://chat.susi.ai for all the pages?
 
Forgot password can be implemented next.

**Comment by rishiraj824** [comment]
@uday96 
-  Lets create a static route with `/login` for example and test the landing page first.
- Then the next issue can be to get the login page on the root directory and implement the login fefature first.
- Then comes sign up and forgot password.
What do you think ?

**Comment by uday96** [comment]
@rishiraj824 Cool, Sounds good to me. :+1:

**Comment by rishiraj824** [comment]
@uday96 Okay, creating Issue for the landing page.

**Comment by isuruAb** [comment]
@uday96  @rishiraj824  we can make login on top of the chat app.if the user is not logged in we can make it visible ,otherwise we can hide it
