### ISSUE TITLE
Thumbs up or down cannot be changed

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/chat.susi.ai#1443]
The feedback once given on an interaction should not be changeable, otherwise it will cause inconsistencies in the feedback logs that will be used for analysis.

**Would you like to work on the issue?**

No, anyone can assign the issue to himself/herself.

**Comment by thakursaurabh1998** [comment]
I would like to work on this.

**Comment by AnupKumarPanwar** [comment]
@thakursaurabh1998 Please keep us updated with your progress. Ask for help if you're anywhere.
