### ISSUE TITLE
Move Map view below Table view in Devices tab in settings

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1451]
**Actual Behaviour**

Currently, they are in separate tabs.

**Expected Behaviour**

As discussed in the meeting, the Map view should be moved below the Table view. This is still open to discussion though.

**Would you like to work on the issue?**

Depending on how the discussion proceeds.

**Comment by Akshat-Jain** [comment]
@akshatnitd @anshumanv @DNS-404 @PrP-11 @hkedia321 @AnupKumarPanwar What are your thoughts about this change? Please share your opinions. Thanks :-)

**Comment by anshumanv** [comment]
This depends on the requirement, in case it is required to see the devices list and the map simultaneously this could be useful, though I think the current tab implementation looks pretty cool and doesn't clutter the UI.

**Comment by DNS-404** [comment]
Agreed with @anshumanv. If the user have a lot of devices then the list would be long and hence map will be shifted all the way below it. Also, this UI keep things simple and clean.
