### ISSUE TITLE
Bug on rating chat window scrolls to bottom 

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1456]
**Actual Behaviour**

Try giving a rating, it would scroll to the latest chat automatically

**Expected Behaviour**

Stay, no scrolling on thumbs up or down

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Anyone is free to take this up.

**Comment by samagragupta** [comment]
I want to work on it.
