### ISSUE TITLE
Add theme preview to "theme tab" in settings and take "themes" from drop-down in chat

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1461]
The theme has a live preview on the live site. This is a nice feature, but it is not central to the app. We can achieve the same feature by having a preview on the themes folder. Please integrate this feature into the settings area (https://chat.susi.ai/settings). Here is a rough wrap up.

![screenshot from 2018-07-16 20-16-15](https://user-images.githubusercontent.com/1583873/42776061-443351ba-8936-11e8-8862-75711dc2d5e0.png)

Please also take out "themes" from the burger menu drop-down.

**Comment by fragm3** [comment]
Working on it..

**Comment by PrP-11** [comment]
@fragm3 What's your progress on this issue?
