### ISSUE TITLE
Update to React v16.4

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1464]
**Actual Behaviour**

#1441 needs to be merged before proceeding.
#1463 is not needed if we upgrade as: React 16.4 removes a lot of internals (#121) this plugin depends on and will break the plugin. The drop down menu will work fine

**Expected Behaviour**

Upgrade to latest version

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Changes to be made:
Upgrade: 

1. "html-react-parser" from "^0.3.5" to "0.4.0", otherwise it throws error, link to error: https://github.com/remarkablemark/html-react-parser/issues/43
2. Update react-dom as well, due to complete internal structure change, link to article: https://reactjs.org/blog/2017/09/26/react-v16.0.html#packaging
3. No need for injectTapEventPlugin
4. Upgrade material ui to react 16 compatible version.

**Comment by anshumanv** [comment]
Good work with the research @fragm3 :sparkle:
