### ISSUE TITLE
Text in table response not using automatic line break

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1466]
If the text in a table is longer than the width of the window the text break should happen automatically. There should not be any horizontal scrolling required.

![screenshot from 2018-07-18 21-52-01](https://user-images.githubusercontent.com/1583873/42904320-f77e1a58-8ad4-11e8-9c95-61ada60adf71.png)

**Comment by Akshat-Jain** [comment]
Working on it.
