### ISSUE TITLE
Setting to toggle chat history.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#147]
**Actual Behaviour**
No way one can toggle the chat history

**Expected Behaviour**

Create a setting to toggle the chat history.

**Would you like to work on the issue?**

@uday96 can take it.

**Comment by uday96** [comment]
:+1:

**Comment by uday96** [comment]
@rishiraj824 From my understanding, when the user first visits http://chat.susi.ai , based on the default setting (for now as aaa isnt implemented yet), the chat history is either displayed or not. Suppose, initally the setting was for not to display history, and after visiting http://chat.susi.ai (no history will be displayed now) and some queries, if the setting is toggled to display history, should the history be added to the ongoing session (i.e add the history to the beggining of the chat and append the queries of the current session) ? Similarly for the other case where initially it was to display history then the option was toggled, then should i delete the history from the ongoing session?

**Comment by rishiraj824** [comment]
@uday96 I think a better approach (for now) could have been to refresh the page once it is toggled. We can't have the older messages pop up as soon as the toggle is clicked. In fact, this is pretty difficult to implement too, in my opinion.

**Comment by uday96** [comment]
@rishiraj824 If we are refreshing the page, and we have to show history, once the page is refreshed, we display only the messages returned by the memory endpoint. Which has a limit of 10. What if the current session had more than 10 new messages, wont few of them be lost?

**Comment by mariobehling** [comment]
@uday96 History should be displayed in the same way as on chat apps. If you scroll back, it gets displayed and loads more and more history. Therefore a toggle is not needed.
