### ISSUE TITLE
Use same signup form across app and add Recaptcha on all signup forms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1470]
On the page https://chat.susi.ai/support the signup form is different to other signup forms. Please always use the same route for signup forms and add recaptcha to all forms.

![screenshot from 2018-07-19 08-41-27](https://user-images.githubusercontent.com/1583873/42926412-99559d36-8b31-11e8-8783-70bc8a45985c.png)

**Comment by Bharghvi** [comment]
Hi, Is the Issue still not solved? I see the same signup form component being used in both the places.

**Comment by oldrick** [comment]
i think it should be solved, bcuz even me i see the same signup forms

**Comment by pranav1698** [comment]
Yeah @mariobehling, as said by @oldrick it appears to be resolved
