### ISSUE TITLE
Modify Custom Theme

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1471]
**Actual Behaviour**

As said by @mariobehling in https://github.com/fossasia/chat.susi.ai/issues/1461

**Expected Behaviour**

- [ ] Add custom theme in settings
- [ ] Add live preview
- [ ] Fix bug like background images not resetting(see in chat.susi.ai by setting background image, then try removing it

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
This is mostly a duplicate of #1461
