### ISSUE TITLE
Avoid hardcoded strings for API server and implement a config file

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1474]
The search on https://github.com/fossasia/chat.susi.ai/search?q=api.susi.ai&unscoped_q=api.susi.ai shows a number of hardcoded URLs.

Currently the system has a number of hard-coded string to Github and the SUSI Server. Please change this. This config should come from a single config or settings file. 

If we deploy this server and server elsewhere or even locally it will not work out of the box otherwise and will take a long time to change.

Ensure the following can be changed easily through changing a config file:

* The URL of the API server
* The URL of the chat service itself
* The logo image on all pages (If the image is changed in the config, it should change everywhere)

**Comment by fragm3** [comment]
Will work on this.

**Comment by fragm3** [comment]
For point 3, the logo image is imported from project folder itself.
