### ISSUE TITLE
Make Forgot Password component consistent with CMS

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/chat.susi.ai#1485]
Actual Behaviour
* It has a different UI
No loading state for button.
Expected Behaviour
* Make Forgot Password component consistent with CMS

**Screenshots of the issue**
![deepinscreenshot_select-area_20180729190034](https://user-images.githubusercontent.com/12656846/43366857-b164ea66-9361-11e8-825f-e6a09d02c66a.png)

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Can I take this up @akshatnitd ? What's CMS ?

**Comment by rupav** [comment]
Ok, thanks. 😃
