### ISSUE TITLE
Share on facebook not working

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1486]
**Actual Behaviour**

Share on facebook showing error.

**Steps to reproduce it**

Settings -> Share On Facebook

**Screenshots of the issue**

<img width="1191" alt="screen shot 2018-07-29 at 8 37 28 pm" src="https://user-images.githubusercontent.com/18073126/43367716-550cfff2-936f-11e8-95ee-b1cb15de20c9.png">

**Comment by darthgera123** [comment]
can i work on this issue?

**Comment by fragm3** [comment]
@pranav1698 you can work on it, if its giving you an error.

**Comment by pranav1698** [comment]
@fragm3 @akshatnitd we can close this as it is working fine 
And there is no problem with the code
