### ISSUE TITLE
Add feature for user avatar upload

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/chat.susi.ai#1494]
**Actual Behaviour**

**Expected Behaviour**
* Added feature in settings to upload avatar.
* Integrate API response of avatar
* Add feature to switch between gravatar and user uploaded avatar

Server issue: https://github.com/fossasia/susi_server/issues/1100
Ref: https://github.com/fossasia/susi_skill_cms/issues/1132
**Would you like to work on the issue?**
Yes

**Comment by darthgera123** [comment]
i would like to work on this issue

**Comment by akshatnitd** [comment]
@darthgera123 I am looking out to implement in on server and then do it here. You can work out on other issues for the time-being.

**Comment by darthgera123** [comment]
okay cool
