### ISSUE TITLE
Fetch api keys from server instead of hard coding

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1495]
**Actual Behaviour**
Currently the api keys are hard coded in config.js file

**Expected Behaviour**
They must be fetched from the server to that they are updated automatically.

**Would you like to work on the issue?**
Yes

**Comment by starlord1311** [comment]
@PrP-11 can i take up this issue?

**Comment by PrP-11** [comment]
@starlord1311 The issue has been fixed already in #1496
