### ISSUE TITLE
A problem is that e.g. the settings page of users gives a 401 to API calls and constantly tries to reload the page

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/chat.susi.ai#1499]
**Actual Behaviour**
* A problem is that e.g. the settings page of users gives a 401 to API calls and constantly tries to reload the page

**Expected Behaviour**
* A solution seems to related to JSONP callbacks. A unique callback for each API endpoint, needs to be implemented. Need to research, if this is the correct soln.

**Would you like to work on the issue?**
Yes

**Comment by starlord1311** [comment]
@akshatnitd can i take up this issue?

**Comment by akshatnitd** [comment]
@starlord1311 I am still investegating the cause of the issue. We can first discuss the approach here, before solving.

**Comment by akshatnitd** [comment]
The issue is not reproducable for me, hence taking more time.
