### ISSUE TITLE
[Pie Charts Visualization] Make the data more generic

### ISSUE THREAD

**Issue by daminisatya** [fossasia/chat.susi.ai#15]
![selection_260](https://cloud.githubusercontent.com/assets/6227784/17386806/b5a96930-5a0b-11e6-8739-34389271579c.png)

**Comment by daminisatya** [comment]
The data is taken statically for getting the pie chart visualization 

```elementObject['name'] = data.answers[0].data[element].president;```

This line must be generic to name or label which can further support a generic pie chart display

**Comment by Cryzek** [comment]
Shouldn't this be addressed at the server. Sending response something like - 
<pre>
      data.answers[0] = {
        isGraphicData: true,
        name: "Chart Name",
        data : [{
          y: some value,
          name: some name
        }, ....] 
      }
</pre>
Also , I tried the query 'Who will win the 2016 presidential elections'. Response was - 
![sketch](https://cloud.githubusercontent.com/assets/9551285/25066450/4f27bfee-2243-11e7-8d91-161140ea6989.png)
