### ISSUE TITLE
Turn the delete account button into warning color

### ISSUE THREAD

**Issue by anshumanv** [fossasia/chat.susi.ai#1507]
**Actual Behaviour**
Delete account button seems like a normal button which can be clicked accidentally.

**Expected Behaviour**
It should be colored in warning color. I know we follow a generic theme but warning color seems more suitable to me for this action.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/21009455/43754449-815b9626-9a28-11e8-99e7-9b575c5f5169.png)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
See comment here please: https://github.com/fossasia/chat.susi.ai/pull/1509/comment#issuecomment-411604183
