### ISSUE TITLE
Recaptcha console error message even if Recaptcha is not used

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#1513]
Recpatcha messages appear in the console even if Recaptcha is not used on the specific page.

`jquery.js:9488 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Comment by fragm3** [comment]
Working on it.

**Comment by fragm3** [comment]
Turns out recaptcha is not giving this error, it was due to `config.js` in /src folder
