### ISSUE TITLE
Pause YouTube when other interactions happen

### ISSUE THREAD

**Issue by YashRE42** [fossasia/chat.susi.ai#1515]
**Actual Behaviour**

Videos continue playing even when:

- [ ] modal is opened eg sign up/ sign in

- [x] another YouTube is opened in new message.

**Expected Behaviour**

In both these cases, playback should automatically be stopped.
Unsure if user should have the ability to play more than one YouTube video at a time, by clicking play on them both, or if only one should play at a time.

**Steps to reproduce it**

Ask for YouTube video, open sign-in modal.

**Would you like to work on the issue?**

Yes, but I would appreciate some guidance on how to proceed with it, and confirmation on intended functionality.

**Comment by PrP-11** [comment]
@YashRE42 you can call a function whenever user click on signup, login or ask something to susi. In this function search for the id of the player using js or jquery and then change its player state.

**Comment by YashRE42** [comment]
I've been trying to do this but created iframes do not have an ID which can be used to select them, additionally, I haven't been able to find a way to select elements within the iframe.

possibly, restrictions prevent that.
![image](https://user-images.githubusercontent.com/33805964/44000050-28f63574-9e36-11e8-8d7f-77e0c56d1f91.png)

I did, however realize that onReady has no definition in MessageListItem :

![image](https://user-images.githubusercontent.com/33805964/44000076-9fe350a4-9e36-11e8-92d4-a4adf33fd633.png)
adding 
`  _onReady(event) {
    // access to player in all event handlers via event.target
    event.target.pauseVideo();
  }`

as in react-youtube docs would prevent videos from playing automatically, however isn't a complete solution and may be against the intended functionality...

More guidance would be appreciated.
