### ISSUE TITLE
Change Send button color according to theme set

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#152]
**Actual Behaviour**

The color of button is not changing

**Expected Behaviour**

It should change according to theme

**Screenshots of the issue**

![nav](https://cloud.githubusercontent.com/assets/22375731/26787742/b5acda62-4a28-11e7-9692-64907e6fb58b.png)

**Would you like to work on the issue?**

Yes, i am trying to solve this.

**Comment by rishiraj824** [comment]
closing via #153
