### ISSUE TITLE
Don't show Modal when redirected through skill example

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#1522]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/21199234/43988195-d9a4113c-9d4d-11e8-8585-5ea7ebfe9b33.png)

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/21199234/43988201-f6fa5f70-9d4d-11e8-8803-d415f5de0370.png)

**Steps to reproduce it**
Click on skill example card on skills.susi.ai

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
Thanks for this @aashutoshrathi

**Comment by rupav** [comment]
Its fixed, not showing modal anymore. This can be closed @anshumanv @aashutoshrathi

**Comment by akshatnitd** [comment]
Yes, even I am not able to reproduce the bug. Hence, closing.
