### ISSUE TITLE
Background color of chat is not changing 

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1533]
**Actual Behaviour**
Changing the background color in user settings on server is not changing the color on chat

**Expected Behaviour**
The color should be changed to the value stores in server like other components.

**Steps to reproduce it**
Try to change the background color using custom theme.

**Would you like to work on the issue?**
@fragm3 , can you look into the issue please

**Comment by fragm3** [comment]
Thanks for pointing out, looking into this.
