### ISSUE TITLE
Implement color picker in custom theme

### ISSUE THREAD

**Issue by PrP-11** [fossasia/chat.susi.ai#1535]
**Actual Behaviour**
Only limited color options are there on custom theme 

**Expected Behaviour**
Implement color picker similar to that implemented on botbuilder

**Screenshots of the issue**
Current : 
![theme](https://user-images.githubusercontent.com/30981465/44091506-465efe5a-9feb-11e8-8d49-081501a61d05.png)
Expected:
![bot](https://user-images.githubusercontent.com/30981465/44091508-4b644c52-9feb-11e8-94ed-5d7146de8af8.png)

**Would you like to work on the issue?**
Anyone can take up this issue but please comment to let me know if you want to work on it

**Comment by fragm3** [comment]
I can work on this

**Comment by PrP-11** [comment]
@fragm3 you can use the code from https://github.com/fossasia/susi_skill_cms/blob/master/src/components/BotBuilder/BotBuilderPages/DesignViews/UIView.js to implement it faster. Please try to implement it faster since https://github.com/fossasia/accounts.susi.ai/pull/447 depends on this issue.
