### ISSUE TITLE
Create a static landing page for login

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#154]
**Actual Behaviour**

No login page for testing, #144. To begin with the login feature we need to have the landing page first.

**Expected Behaviour**

This page can be routed to a static route for testing purposes, example `/login` with the ability to switch to sign up, forgot password

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Let's approach a mixed option, meaning:
* offer an anonymous mode without login and
* provide additional features, e.g. chat history for users that login.

Hence this means the chat UI is still available for anonymous users.

**Comment by rishiraj824** [comment]
@mariobehling Okay :+1:
