### ISSUE TITLE
Alignment in https://chat.susi.ai/overview

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#1553]
**Actual Behaviour**

As you can see in the screenshot of the https://chat.susi.ai/overview page the column items are not aligned properly.
![bugsusi](https://user-images.githubusercontent.com/10114907/45678196-3238a000-bb36-11e8-8059-b8c849a08f87.png)

**Expected Behaviour**

It should be in a row.

**Steps to reproduce it**

https://chat.susi.ai/overview scroll down.

**Would you like to work on the issue?**
no

**Comment by sarnava1** [comment]
@tabesin @mariobehling @Akshat-Jain @akshatnitd can I try this?
