### ISSUE TITLE
Add a help document for developers.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/chat.susi.ai#1563]
**Actual Behaviour**

Need a document for developers that describes how to add more commands, translations,.... 

**Expected Behaviour**

Add a document for developers to know how to add more commands, new words and translations to SUSI.

**Steps to reproduce it**

Add aforesaid details on readme.md

**Would you like to work on the issue?**

Opened to all developers to work.

**Comment by ns200310** [comment]
I will Supun
