### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/chat.susi.ai#1564]
**Actual Behaviour**

Not any settings showing or added.

**Expected Behaviour**

Add settings...

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/33794760/45873837-fc532000-bdb0-11e8-8cf0-f7ec5783b416.png)

**Would you like to work on the issue?**

Opened to all....

**Comment by samagragupta** [comment]
Can you please explain more about this ?

**Comment by aswinmprabhu** [comment]
Can you please elaborate?

**Comment by STEdirisuriya** [comment]
@samagragupta @aswinmprabhu When clicking on tabs like password, server settings, mobile, etc. they are not showing. I think they are not added. That I mentioned.

**Comment by AakashMallik** [comment]
@STEdirisuriya It works fine on my system.

**Comment by samagragupta** [comment]
There are no such things (tabs like server settings) on https://chat.susi.ai/settings

**Comment by akshatnitd** [comment]
Cannot be reproduced.
