### ISSUE TITLE
Icons in navbar on hover says SVG icons

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#157]
**Actual Behaviour**

Icons on nav-bar on hover says SVG-icons.

**Expected Behaviour**

They should say something meaningful to their respective jobs.

**Screenshots of the issue**

![screen](https://cloud.githubusercontent.com/assets/22375731/26808681/2f125fb4-4a7c-11e7-9271-2203ffa5466a.png)

**Would you like to work on the issue?**

Yes, sending a PR

**Comment by uday96** [comment]
@mariobehling This issue has been fixed. Kindly close it

**Comment by rishiraj824** [comment]
closing via #158
