### ISSUE TITLE
Phone number input overlaps with region drop down

### ISSUE THREAD

**Issue by rossoskull** [fossasia/chat.susi.ai#1575]
**Actual Behaviour**

On Settings > Mobile, when the screen size is squeezed, the phone number input field is overlapping the region input

**Expected Behaviour**

The phone number field should move down.

**Steps to reproduce it**

Go to Settings > Mobile, and reduce the screen size.

**Screenshots of the issue**

![screenshot from 2018-09-22 23-21-28](https://user-images.githubusercontent.com/27884543/45924136-a51a9000-bf15-11e8-9572-3b360e0a6486.png)

**Would you like to work on the issue?**

Yes.

**Comment by rossoskull** [comment]
This issue is open for others to claim :v:

**Comment by samagragupta** [comment]
I would like to work on it .
Can you please assign it to me?

**Comment by samagragupta** [comment]
I would like to work on it .

**Comment by rossoskull** [comment]
Great, go on :+1:
