### ISSUE TITLE
Do not show minimum password limit while logging in.

### ISSUE THREAD

**Issue by rupav** [fossasia/chat.susi.ai#1582]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/20624380/45956970-84475d00-c031-11e8-8e53-6320573771f6.png)

**Expected Behaviour**
While logging in, no need to show the limit.

**Steps to reproduce it**
Try entering password while logging in.

**Would you like to work on the issue?**
Yes.

**Comment by aswinmprabhu** [comment]
Hey, I am looking to contribute to FOSSASIA projects and this seems like a good place to begin.
Can I please work on this?

**Comment by rupav** [comment]
Sure, go ahead. 👍. If you need any help with your first PR, feel free to message on this thread.
