### ISSUE TITLE
The buttons and links shift downwards when the "select timezone" input field is selected

### ISSUE THREAD

**Issue by akshi-11** [fossasia/chat.susi.ai#1583]
**Actual Behaviour**

The right part of the page gets dislocated and the buttons and links shift downwards when the input field of select timezone is selected in the account option of settings.

**Expected Behaviour**

The page shouldn't get dislocated when the option is selected.

**Steps to reproduce it**

Go to settings/account. Try to select a timezone.

**Screenshots of the issue**

![2018-09-24 4](https://user-images.githubusercontent.com/31557923/45965818-20c82a00-c047-11e8-92ef-ed4bda7ed685.png)

**Would you like to work on the issue?**

 Yes.

**Comment by plxity** [comment]
@akshi-11  I am taking up this issue.
