### ISSUE TITLE
Red line in Upper left Logo clicking

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#1588]
**Actual Behaviour**
When you click the logo in the upper left corner it is encircled by a red dotted line, when deactivated it becomes a blue line in a blue that is different from the background color

**Expected Behaviour**

No need for link highlighting.

**Screenshots of the issue**

![susichatt](https://user-images.githubusercontent.com/10114907/46013146-a7bee600-c0cb-11e8-869d-11cb25c8487b.jpeg)

**Would you like to work on the issue?**

no

**Comment by rupav** [comment]
@tabesin not able to reproduce the issue.

**Comment by tabesin** [comment]
My web browser is Firefox. Using the version deployed at http://chat.susi.ai

**Comment by rupav** [comment]
I am testing it on firefox as well. still not able to see the red dotted line on clicking the logo.

**Comment by tabesin** [comment]
FF 61.0.1 (64-bit)

**Comment by rupav** [comment]
Ok, I am using FF 62.0.2 (64-bit). Then someone else can claim this issue, since I am not able to reproduce this issue. 👍
