### ISSUE TITLE
Use snackbar to show info similar to CMS

### ISSUE THREAD

**Issue by rupav** [fossasia/chat.susi.ai#1590]
**Actual Behaviour**

**Expected Behaviour**
Use snackbar for error, warning, or info instead of currently used system.

**Screenshots of the issue**
**Desired output**:
![image](https://user-images.githubusercontent.com/20624380/46051884-480f1c00-c159-11e8-87a2-0d62b66032ab.png)
**Currently**:
![image](https://user-images.githubusercontent.com/20624380/46051922-6f65e900-c159-11e8-9fd2-7770c651bff3.png)

**Would you like to work on the issue?**
Yes.

**Comment by pranav1698** [comment]
Hi @rupav, are you working on the issue, I would like to work pn it

**Comment by rupav** [comment]
Yes I am working on it, basically starting it with the Auth components.

**Comment by pranav1698** [comment]
Ok👍
