### ISSUE TITLE
Create support for emoji in chat

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#160]
**Actual Behaviour**

Emojis are not shown

**Expected Behaviour**

The emojis should be rendered in the chat screen.

**Steps to reproduce it**

Sample query ```emoji```

**Screenshots of the issue**

![screenshot from 2017-06-06 07 14 29](https://cloud.githubusercontent.com/assets/11540785/26810228/0a71c562-4a88-11e7-8564-05e1db235b4d.png)

**Would you like to work on the issue?**

Anyone is free to take it up.

**Comment by madhavrathi** [comment]
I will like to work on this

**Comment by uday96** [comment]
@mariobehling This issue is fixed. Please close it.

**Comment by rishiraj824** [comment]
closing via #182
