### ISSUE TITLE
Search functionality is buggy on testing skills via SUSI Skill CMS

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/chat.susi.ai#1602]
**Actual Behaviour**

Search functionality is not working properly on the test example links which open when we try to test skills via SUSI Skill CMS.

**Expected Behaviour**

Search functionality should work properly.

**Screenshots of the issue**

![bugsearchfunctionality](https://user-images.githubusercontent.com/31135861/46286269-320bbc00-c59c-11e8-9e40-64679f301254.gif)

**Would you like to work on the issue?**

No, anyone can claim this issue.

**Comment by Akshat-Jain** [comment]
@aashutoshrathi

**Comment by YogeshSharma0201** [comment]
Would like to work on this.

**Comment by anshumanv** [comment]
@aashutoshrathi are you working on this?
