### ISSUE TITLE
Modify Scroll Up and Down

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1603]
**Actual Behaviour**

Currently 2 scroll are shown, on top right and bottom left

**Expected Behaviour**

Only 1 scroll should be shown depending whether scrolling up or down. If scrolling up, scroll up to be shown. If scrolling down, scroll down to be shown

**Would you like to work on the issue?**

Yes

**Comment by tathagat2006** [comment]
Yes

**Comment by ammarbinfaisal** [comment]
what's wrong with both being shown?
like if one is scrolling neither upwards nor downwards then it for some reason he just want to go down or up then he can just click on the desired scroll button
