### ISSUE TITLE
Forgot Password not working

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/chat.susi.ai#1609]
**Actual Behaviour**
When we click the forgot password link in the settings, it shows 404 not found

**Expected Behaviour**
It should send a verification mail to the mail id

**Steps to reproduce it**
-Go to https://chat.susi.ai/settings
-Passwords tab

**Screenshots of the issue**
![screenshot from 2018-10-05 15-39-40](https://user-images.githubusercontent.com/33062425/46529656-e5362700-c8b4-11e8-8ce6-83f74a00d0f0.png)

**Would you like to work on the issue?**
Yes

**Comment by samagragupta** [comment]
An issue is already made on it .
https://github.com/fossasia/chat.susi.ai/issues/1558

**Comment by rajvaibhavdubey** [comment]
I'm sorry, I didn't notice it,
