### ISSUE TITLE
Scrollable dropdown menu in settings

### ISSUE THREAD

**Issue by samagragupta** [fossasia/chat.susi.ai#1616]
**Actual Behaviour**

While selecting `Select default language` on https://chat.susi.ai/settings the dropdown menu is not scrollable.

**Expected Behaviour**

When selecting `Select default language` the dropdown menu should be scrollable.

**Would you like to work on the issue?**

Yes

**Comment by pranav1698** [comment]
Are you still working on this issue?

**Comment by pranav1698** [comment]
Yeah I would like to work on it

**Comment by pranav1698** [comment]
Actually, I think have found a solution for it

**Comment by samagragupta** [comment]
Go for it 🚀

**Comment by pranav1698** [comment]
Ok @samagragupta on it

**Comment by pranav1698** [comment]
@samagragupta we can use select for this issue
https://material-ui.com/api/select/
But the problem is that it asks to upgrade react to version @16.3.0 
Should I open an issue corresponding to it

**Comment by samagragupta** [comment]
@pranav1698 I think you should do it.
@anshumanv @akshatnitd @mariobehling What are your suggestions?
