### ISSUE TITLE
Placeholder text required in password tab

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/chat.susi.ai#1624]
**Actual Behaviour**

There is no placeholder text in password settings fields

**Expected Behaviour**

In accounts.susi.ai, password tab fields have placeholder text, so should the corresponding fields in chat.susi.ai have.

**Steps to reproduce it**

Open Settings -> Password

**Screenshots of the issue**
![screenshot 2018-10-18 at 8 53 17 pm](https://user-images.githubusercontent.com/31539812/47165671-20eed900-d318-11e8-9f6c-8d214de37ad0.png)

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
@neeraj3029 A placeholder in the password field would be unnecessary here. What values of placeholders do you plan to put? I am open to discussion.
