### ISSUE TITLE
Integrate Redux 

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/chat.susi.ai#1633]
**Actual Behaviour**
* Currently a flux based architecture has been implemented in the app

**Expected Behaviour**
* Redux should be implemented and the directory structure should be well organised

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
Collaborating! :tada:

**Comment by rupav** [comment]
I too would love to collaborate on this, worked with redux earlier.

**Comment by akshatnitd** [comment]
@anshumanv @rupav Sure! Once, the initial Redux structure is setup we can add actions and reducers for all the components

**Comment by fragm3** [comment]
@akshatnitd I am also interested in collaborating, great suff <3

**Comment by AakashMallik** [comment]
@akshatnitd I'll be helping out with actions and reducers. Good call on the redux part, I was planning on raising this issue myself. Let us see this through, will get started as soon as your PR gets merged.

**Comment by feat7** [comment]
Why not implement Mobx instead of Redux?
The development time of mobx is far less than that of redux. It is easy to code and implement as well.
