### ISSUE TITLE
New Improved UI Design

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/chat.susi.ai#1641]
**Actual Behaviour**

Has a old UI design

**Expected Behaviour**

A Brand new UI design to make it unique on the web.

**Would you like to work on the issue?**
Yes

## V1
 ![desktop](https://user-images.githubusercontent.com/20199181/47435530-6ef55800-d7c2-11e8-9d42-44eb1d3414f5.png)

## V2
![Version2](https://files.gitter.im/fossasia/susi_webchat/ZcTk/Web-1366-_-2.png)

## V3
![chat 1](https://user-images.githubusercontent.com/20199181/49781699-b5ceeb00-fd39-11e8-91f5-76450bb46230.png)
![skills 1](https://user-images.githubusercontent.com/20199181/49781707-bbc4cc00-fd39-11e8-8081-417290364a4c.png)

**Comment by jogendra** [comment]
The UI looks good. Great work with the mockup. The only thing looks odd to me is space between SUSI and user messages, it is quite wide and doesn't look good.

**Comment by niteshkumarniranjan** [comment]
@jogendra Okay! I will do another version.

**Comment by anshumanv** [comment]
Great work!

**Comment by niteshkumarniranjan** [comment]
@jogendra @anshumanv @akshatnitd I am also a GCI participant so maybe it will take longer for me do another version.

**Comment by fragm3** [comment]
@niteshkumarniranjan good work!
