### ISSUE TITLE
Overflow background!

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/chat.susi.ai#1646]
**Actual Behaviour**

In dark background, it overflows.
![image](https://user-images.githubusercontent.com/33794760/47503850-ae867780-d888-11e8-887d-f1250c2d8a55.png)
![image](https://user-images.githubusercontent.com/33794760/47503910-cf4ecd00-d888-11e8-9f06-1b5a48c8b8a8.png)

**Expected Behaviour**

Fix the issue!!

**Would you like to work on the issue?**

Opened to all

**Comment by neeraj3029** [comment]
@STEdirisuriya This is a duplicate issue. Please see #1622

**Comment by anshumanv** [comment]
Duplicate of #1622
