### ISSUE TITLE
Improve validation code on signup page

### ISSUE THREAD

**Issue by samagragupta** [fossasia/chat.susi.ai#1648]
**Actual Behaviour**

If there is an error in one field, and we start typing in other field, the error in the previous field is not displayed.->

**Expected Behaviour**

If there is an error in one field, and we start typing in other field, the error in the previous field is displayed.

**Would you like to work on the issue?**

Yes

**Comment by ammarbinfaisal** [comment]
@samagragupta  are u working on this? if not I can give it a try

**Comment by samagragupta** [comment]
@ammarbinfaisal Yes, I am working on it.
