### ISSUE TITLE
Make separate component for AppBar

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#165]
**Actual Behaviour**

Now all the features of AppBar is in MessageSection component and it is getting bigger day by day. 

**Expected Behaviour**

We have to make a separate component for AppBar.

**Comment by rishiraj824** [comment]
Working on this

**Comment by uday96** [comment]
@rishiraj824 are you working on this?

**Comment by rishiraj824** [comment]
@uday96 You can work on this, if you want.

**Comment by uday96** [comment]
Working on this :+1:
