### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by thegauravtiwari** [fossasia/chat.susi.ai#1656]
**Actual Behaviour**

When I message "What is hello in french". It shows NO RESULT FOUND.

**Expected Behaviour**

It should show -"Bonjour. HELLO IN FRENCH" as shown in youtube video.

**Screenshots of the issue**

![screenshot 2018-10-27 at 6 08 11 pm](https://user-images.githubusercontent.com/24623926/47604167-5c259200-da13-11e8-9a19-fa0031332a75.png)

**Comment by fragm3** [comment]
@thegauravtiwari I would like to work on this, if it's fine by you

**Comment by thegauravtiwari** [comment]
@fragm3 Hey. I'm a newbie to open source. If you could guide me on exploring the project and understanding the codebase. You can work on the issue if you want to.

**Comment by fragm3** [comment]
@thegauravtiwari learn the basics of react through https://reactjs.org/docs/hello-world.html
Currently, we are using flux with react in this project. I would recommend to start contributing with small issues first, then go for the big ones.

**Comment by akshatnitd** [comment]
@thegauravtiwari @fragm3 It is not a bug due to the code of the web client. You should check out the skill for this and then make changes in the Skill file.
