### ISSUE TITLE
Email validation is not working on signup modal

### ISSUE THREAD

**Issue by samagragupta** [fossasia/chat.susi.ai#1660]
**Actual Behaviour**

When typing the wrong email in the email textfield there is error shown.

**Expected Behaviour**

When typing the wrong email in the email textfield error should be shown.

**Screenshots of the issue**

![email validation](https://user-images.githubusercontent.com/32234926/47611101-f2919c00-da83-11e8-818d-aae7ac12b4d0.gif)

**Would you like to work on the issue?**

Yes

**Comment by samagragupta** [comment]
@aswinshenoy This issue is also fixed with this PR.

**Comment by aswinshenoy** [comment]
> @aswinshenoy This issue is also fixed with this PR.

Oh yeah, since the form is validated even before submission, such an issue doesn't even arise :)
