### ISSUE TITLE
Links returning 404 in devices page

### ISSUE THREAD

**Issue by aswinshenoy** [fossasia/chat.susi.ai#1662]
**Actual Behaviour**

On the webpage, [https://chat.susi.ai/devices](https://chat.susi.ai/devices), the links provided are preceded by a '/',  and clicking on it therefore returns the 404 page.

**Expected Behaviour**

Clicking on the link should actually take the user to playstore/github/web app link.

**Steps to reproduce it**

On looking the source code, I found that a '/' precedes the actual url and therefore makes it a extention to the current url (than being an absolute url).  Removing the preceding slash should fix the problem. 
~~~
<a class="app_store" target="_blank" href="/https://github.com/fossasia/susi_iOS"><!-- react-text: 111 --> <!-- /react-text --><!-- react-text: 112 -->Download on the App Store<!-- /react-text --></a>

<a class="app_store" target="_blank" href="/https://github.com/fossasia/susi_iOS"><!-- react-text: 111 --> <!-- /react-text --><!-- react-text: 112 -->Download on the App Store<!-- /react-text --></a>

<a target="_blank" href="/https://chat.susi.ai" style="text-decoration: none;"><!-- react-text: 121 --> <!-- /react-text --><!-- react-text: 122 -->here<!-- /react-text --></a>
~~~

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/21276922/47613390-7d8a8a80-dab4-11e8-808b-7097f264f1ee.png)

![image](https://user-images.githubusercontent.com/21276922/47613397-a743b180-dab4-11e8-8ba4-b30934bd79d7.png)

![image](https://user-images.githubusercontent.com/21276922/47613460-c68f0e80-dab5-11e8-8993-52736189e0b6.png)

**Would you like to work on the issue?**

Yes. :)

**Comment by aswinshenoy** [comment]
the issue was with susi.ai project, and not with chat.susi.ai

**Comment by fragm3** [comment]
Links working fine, closing issue.
