### ISSUE TITLE
Use Axios or fetch instead of jQuery for AJAX calls.

### ISSUE THREAD

**Issue by feat7** [fossasia/chat.susi.ai#1663]
**Actual Behaviour**
jQuery is being used to call AJAX requests, whose size is much bigger than it's current use. Moreover, it is seldom to use jQuery to manipulate the DOM while the project is based on React. Hence, the only use of jQuery I can see is for AJAX requests.

**Expected Behaviour**
Use a library such as `axios` or `fetch` APIs instead of jQuery. Thereby reduce the build bundle size by removing jQuery.

**Steps to reproduce it**
It is a code based problem.

**LogCat for the issue**
No LogCat

**Screenshots of the issue**
See the code example instead:
```
$.ajax({
    url: url,
    dataType: 'jsonp',
    crossDomain: true,
    timeout: 3000,
    async: false,
    success: function(response) {
      console.log(response);
    },
    error: function(errorThrown) {
      console.log(errorThrown);
    },
  });
```

**Would you like to work on the issue?**
Yes.

**Comment by akshatnitd** [comment]
@feat7 It is being handled in #1657. Do check out the PR #1664 and suggest any changes.

**Comment by feat7** [comment]
@akshatnitd good to see your PR.
But The given PR introduces implementation of axios and helper functions but doesn't remove jquery's dependency.
As said, the issue which I introduced is more about removing jquery's dependency rather than implementing it with axios.

**Comment by ammarbinfaisal** [comment]
I would like to help here.   

I think that we can make our own small jquery which only has the methods that are required and place it in the utils so that we have to only change `import $ from "jquery"` line to `import $ from "../utils.jquery"` or whatever the relative path might be in the files using jquery.

Or should everything be done with those long vanillajs methods `document.querySelector(..)...`?

**Comment by ammarbinfaisal** [comment]
> I think that we can make our own small jquery which only has the methods that are required and place it in the utils so that we have to only change import $ from "jquery" line to import $ from "../utils/jquery" or whatever the relative path might be in the files using jquery.

@akshatnitd should I proceed with this?

**Comment by akshatnitd** [comment]
@ammarbinfaisal We are looking to shift to axios and completely remove the use of JQuery, so IMO it would not be helpful in that case

**Comment by ammarbinfaisal** [comment]
@akshatnitd u didnt get me
I am not talking about the ajax requests.  

as @feat7 mentioned in the issue description

> jQuery is being used to call AJAX requests, whose size is much bigger than it's current use. Moreover, it is seldom to use jQuery to manipulate the DOM while the project is based on React. Hence, the only use of jQuery I can see is for AJAX requests.

jquery is being used in the app for dom element selection and animation.  
Shouldnt that be removed? To remove dependency on jquery for dom manipulation I suggested to write our own small methods to just handle the use cases

**Comment by ammarbinfaisal** [comment]
I am going to do what I am talking about and then add a PR  
if u like it then accept it or simply close it :smiley:

**Comment by AakashMallik** [comment]
@ammarbinfaisal It would be a waste of your time as we are going to use a well-published library than bug prone hand written code. That is the whole point of using libraries in the first place. Your effort could be better used in refactoring the existing code. Please help us with that.

**Comment by ammarbinfaisal** [comment]
> than bug prone hand written code.

That wont be bug prone
what I mean is simply this
`
const $ = query => document.querySelector(query)
`

and then exending the prototype of HTMLElement
 <br>

> it would be a waste of your time

Yes, I got this after checking the files using jquery.
there are many cases where jquery is still being used for http requests.
  <br>
  
> Please help us with that.

U guys decide what to do, I would love to help

**Comment by AakashMallik** [comment]
@ammarbinfaisal By the way, dom manipulation using JQuery is highly discouraged in the react community. There are many libraries for complex animations that are compatible with react. So'll we'll find a way.

**Comment by ammarbinfaisal** [comment]
> By the way, dom manipulation using JQuery is highly discouraged in the react community. There are many libraries for complex animations that are compatible with react.

I completely agree and thats why I want to remove jquery  
moreover I dont event do dom manipulation using vanilla js methods while using react but thats there in the project already.

**Comment by feat7** [comment]
@ammarbinfaisal currently jQuery is being used for ajax requests. Nothing more. No dom manipulation. And we want to remove jQuery and replace it with axios. For axios is the standard nowadays and can be used to replace jQuery instead of we writing code for AJAX requests. We don't want to reinvent the wheel.

**Comment by ammarbinfaisal** [comment]
@feat7 It is being used in src/components for animation, scrolling, adding removing classes etc.

**Comment by AakashMallik** [comment]
@feat7 I am afraid @ammarbinfaisal is right about this. JQuery is being used for dom manipulation.

**Comment by feat7** [comment]
Is it? Then this is serious issue. We need to get rid of jQuery. It should not be used with react. It leads to poor performance. @akshatnitd @AakashMallik  @ammarbinfaisal

**Comment by akshatnitd** [comment]
Already done.
