### ISSUE TITLE
Select default language feature not working

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/chat.susi.ai#1679]
**Actual Behaviour**
Language should change according to the data provided in the respective json file.

**Expected Behaviour**
Select default language feature not working

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
> @akshatnitd @samagragupta @AakashMallik @Akshat-Jain Please help me with this.
> Thank you smile

Give me some time pal, I'll get to the bottom of this. Currently working on another issue. If I find something, I'll let you know. @rajvaibhavdubey

**Comment by AakashMallik** [comment]
@rajvaibhavdubey Any progress on this?
