### ISSUE TITLE
Make stateless components into functional components

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1681]
**Actual Behaviour**

Following Components are stateless:

- FourButtons
- CircleImage
- Footer
- Logout
- DialogSection
- ThreadListItem
- Devices

**Expected Behaviour**

Convert above components to functional components.

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
It is great to see people putting in a time to refactor the code. We really need this right now.
