### ISSUE TITLE
Refactor RemoveDialogDevice, TableComplex

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1704]
**Actual Behaviour**

RemoveDialogDevice, TableComplex needs to be refactored

**Expected Behaviour**

Refactor RemoveDialogDevice, TableComplex(needs to be made functional), code clean up

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
A PR for Login refactor already exists. https://github.com/fossasia/chat.susi.ai/pull/1688

**Comment by fragm3** [comment]
Okay, thanks for telling!
