### ISSUE TITLE
Refractor ChangePassword component

### ISSUE THREAD

**Issue by ammarbinfaisal** [fossasia/chat.susi.ai#1720]
**Actual Behaviour**

it is not like the rest of the refactored codebase.

**Expected Behaviour**

Changes I would like
- [ ] remove dependency on jquery
- [ ] convert normal functions to arrow functions
- [ ] arrange import statements

**Would you like to work on the issue?**

yes

**Comment by AakashMallik** [comment]
@ammarbinfaisal There is a helper file named ajax.js that has been created to make the use of Axios simpler and unified, see if you can make use of it instead of calling in axios urself.

**Comment by ammarbinfaisal** [comment]
okay, I would

**Comment by ammarbinfaisal** [comment]
closing just for a while until I have something to improve/workon. I'll rename the issue and edit description then
