### ISSUE TITLE
ScrollTop button does not appear when chat is scrolled down using scrolldown button

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/chat.susi.ai#1723]
**Actual Behaviour**
ScrollTop buttons does not appear when chat is scrolled down using scrolldown button

**Expected Behaviour**
ScrollTop button should appear when chat is scrolled down using scrolldown button

**Steps to reproduce it**
Try scrolling down the chat using scrolldown button.

**Screenshots of the issue**
GIF-
![cur](https://user-images.githubusercontent.com/31539812/48298453-d52ceb00-e4e3-11e8-81d6-21436ee88dea.gif)

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
Nice. You spotted a hard to find bug.
