### ISSUE TITLE
Remove jquery's usage for DOM manipulation

### ISSUE THREAD

**Issue by ammarbinfaisal** [fossasia/chat.susi.ai#1725]
**Actual Behaviour**

Currently jquery is being used for manipulating the DOM

* At many places it is being used for scrolling the page or getting an element's height(in StaticAppBar.react.js). Vanilla js functions can be used for that.
* In ThemeChanger.js it is being used for triggering the click event(line 201) vanilla js can also be used for that
* In RemoveDeviceDialog.react.js it is being used for changing the styles.
* In settings.react.js it is being used for adding removing classes(line 716)

**Expected Behaviour**

It should not be used for DOm manipulation

**Comment by jamesgeorge007** [comment]
I would like to pick this up 👍
