### ISSUE TITLE
Maximum limit of allowed passoword length in password fields needs to added

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/chat.susi.ai#1729]
**Actual Behaviour**
Presently, the password field allows password length of any number of characters greater than/equal to 6.

**Expected Behaviour**
Maximum limit allowed password length in password fields needs to added, as the **maximum number of allowed characters on server side is 64.**

**Steps to reproduce it**
Try updating the password with length greater than 64.

**Would you like to work on the issue?**
Yes

**Comment by Lahirutech** [comment]
I would like to work on this
