### ISSUE TITLE
No need of forgot password form

### ISSUE THREAD

**Issue by samagragupta** [fossasia/chat.susi.ai#1735]
**Actual Behaviour**

We have to write the email address in forgot password form when logged in (Change password settings)

**Expected Behaviour**

After clicking the forgot password button recovery mail should be directly sent.

**Screenshots of the issue**

![forgot](https://user-images.githubusercontent.com/32234926/48668896-e8f8d280-eb1d-11e8-836a-84f5e95b5603.PNG)

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
@samagragupta Doesn't make sense. Why would want to do that? Say I forgot my password and use your system to send a forgot password request. Or say you have two accounts.

**Comment by samagragupta** [comment]
@AakashMallik  then you can use the forgot password form from the main login page.
![forgot](https://user-images.githubusercontent.com/32234926/49067349-d67f4700-f249-11e8-9d21-82b68710e5ad.PNG)

**Comment by AakashMallik** [comment]
@samagragupta Why would you want the user to go back all the way to the main login page. I think the current implementation is pretty functional. @Akshat-Jain  What do you think?

**Comment by anshumanv** [comment]
Let this stay as is, I don't think it'll make a big addition or solve some major issue.
