### ISSUE TITLE
Search number is not changing

### ISSUE THREAD

**Issue by samagragupta** [fossasia/chat.susi.ai#1736]
**Actual Behaviour**

Search number is not changing

**Expected Behaviour**

Search number should change correctly

**Screenshots of the issue**

![search](https://user-images.githubusercontent.com/32234926/48676964-2e57e700-eb94-11e8-8b7b-de01786426a3.gif)

**Would you like to work on the issue?**

Yes

**Comment by prateek76** [comment]
@samagragupta i want to work on this issue

**Comment by prateek76** [comment]
@AakashMallik i have solved the counter issue can i make pr?

**Comment by rajvaibhavdubey** [comment]
Since this issue has been inactive for many days, you can surely send a PR.
ThankYou :smile:

**Comment by prateek76** [comment]
@rajvaibhavdubey i am a beginner,i have just started thanks for help
