### ISSUE TITLE
Share chats of susi implement for facebook

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/chat.susi.ai#1738]
**Actual Behaviour**
Implement chat sharing for facebook

**Expected Behaviour**
Implement chat sharing for facebook

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
What are you planning to do?

**Comment by rajvaibhavdubey** [comment]
@anshumanv Similar to chat sharing on twitter 
![screenshot from 2018-11-19 12-02-16](https://user-images.githubusercontent.com/33062425/48690051-0350b000-ebf3-11e8-8ff2-33dd58dee1da.png)

I was thinking to implement it for facebook also.

**Comment by rajvaibhavdubey** [comment]
@Aakash-DD sure, go ahead :+1:
