### ISSUE TITLE
feedback.react.js not working skill rating failed

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/chat.susi.ai#1739]
**Actual Behaviour**
feedback.react.js not working skill rating failed

**Steps to reproduce it**
On liking or disliking a susi chat it should submit feedback, instead it shows error in console skill rating failed.

**LogCat for the issue**
![screenshot from 2018-11-19 02-02-44](https://user-images.githubusercontent.com/33062425/48677729-3ec18f00-eb9f-11e8-9c8c-4af18ae39074.png)

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
@rajvaibhavdubey  Did you login while testing it? Coz as far as I remember, you need to be logged in in order to give a like.

**Comment by rajvaibhavdubey** [comment]
@AakashMallik Yeah it's not working upon login.

**Comment by AakashMallik** [comment]
![screenshot-localhost-3000-2018 11 19-13-59-01](https://user-images.githubusercontent.com/19551058/48694769-4d419200-ec03-11e8-8cf5-f6c4b0a8ea9b.png)
Working for me. I hope you are testing it on the master branch and not the hosted version.

**Comment by rajvaibhavdubey** [comment]
> ![screenshot-localhost-3000-2018 11 19-13-59-01](https://user-images.githubusercontent.com/19551058/48694769-4d419200-ec03-11e8-8cf5-f6c4b0a8ea9b.png)
> Works for me. I hope you are testing it on the master branch and not the hosted version.

View the console also, there you should see an error message 😅

**Comment by AakashMallik** [comment]
@rajvaibhavdubey Yup, you are right, it is not being sent to the backend. Proceed with the issue. Good job finding the bug. :+1:
