### ISSUE TITLE
It's not suitable a dropdown always.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/chat.susi.ai#1750]
**Actual Behaviour**

In a widescreen(Desktop, Laptop), it's not suitable for adding dropdown list.

**Expected Behaviour**

Add icons on the navbar, and make it turning to the dropdown in the mobile screen. Make it responsive!!! 

**Steps to reproduce it**

- Add icons on the nav bar
- Set dropdown shows in mobile screen.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/33794760/48883076-0bebf500-ee44-11e8-8a5d-24837fbb51a9.png)

**Would you like to work on the issue?**

Yes, I'm working on it.

**Comment by STEdirisuriya** [comment]
Could I work on this?

**Comment by AakashMallik** [comment]
@anshumanv I am against this change. What is your opinion on this?

**Comment by anshumanv** [comment]
No changes needed in this section, it looks perfectly apt to me

![screenshot from 2018-11-22 19-36-12](https://user-images.githubusercontent.com/21009455/48907595-f0a5d780-ee8d-11e8-98c4-77dac8e9a48c.png)

Thanks for the heads up @AakashMallik :+1:
