### ISSUE TITLE
Scroll to bottom stays even when user is at the bottom.

### ISSUE THREAD

**Issue by sak6e** [fossasia/chat.susi.ai#1752]
**Actual Behaviour**
The 'Scroll to bottom' icon stays even when the user is already at the bottom. 

**Expected Behaviour**
It should disappear when user is at the bottom, just like 'Scroll to top' icon does when on top.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/22349909/48889090-afe09b00-ee5a-11e8-89b9-c0f80b8be5e1.png)

**Would you like to work on the issue?**
Yes.

**Comment by fliptrail** [comment]
I would like to work in this issue.
