### ISSUE TITLE
Footer should be consistent

### ISSUE THREAD

**Issue by samagragupta** [fossasia/chat.susi.ai#1754]
**Actual Behaviour**

The footer on chat susi is different from the other susi sites.

**Expected Behaviour**

The footer should be consistent in all susi sites.

**Screenshots of the issue**

Footer - chat
![chat footer](https://user-images.githubusercontent.com/32234926/48918879-75581c00-eeb5-11e8-971b-8d3bd49c7a98.PNG)

Footer - accounts
![footer accounts](https://user-images.githubusercontent.com/32234926/48918885-7e48ed80-eeb5-11e8-942e-ab5f3ac8a7fc.PNG)

**Would you like to work on the issue?**

Yes

**Comment by ammarbinfaisal** [comment]
can i take it up?

**Comment by samagragupta** [comment]
@ammarbinfaisal Sorry bro, I am working on this.
