### ISSUE TITLE
Login button activates with empty password field

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/chat.susi.ai#1764]
**Actual Behaviour**

Login button activates with initially empty password field.

**Expected Behaviour**

The button should not be activated until both the fields have valid data

**Steps to reproduce it**

Just fill in the email address

**Screenshots of the issue**

![screenshot-localhost-3000-2018 11 28-01-40-06](https://user-images.githubusercontent.com/19551058/49108676-c77eb000-f2ae-11e8-9a67-4c6f6508b22a.png)

**Would you like to work on the issue?**

Yes, I'll fix it tomorrow.

**Comment by ammarbinfaisal** [comment]
@AakashMallik can i work on this? :pray:

**Comment by AakashMallik** [comment]
Pal already started working on this. :sweat_smile: @ammarbinfaisal
