### ISSUE TITLE
Fix nav bar!

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/chat.susi.ai#1773]
**Actual Behaviour**

Navbar isn't fixed on the window.
![image](https://user-images.githubusercontent.com/33794760/49326356-1f4f3c80-f577-11e8-8e68-b1db852f4f0e.png)
----
----
![image](https://user-images.githubusercontent.com/33794760/49326365-2d9d5880-f577-11e8-8489-353f92bb407a.png)

It's on the bottom.

**Expected Behaviour**

Make it fixed.

**Steps to reproduce it**

- Change CSS to make it fixed.

**Would you like to work on the issue?**

Yes, I am working.

**Comment by samagragupta** [comment]
An issue is already made on this https://github.com/fossasia/chat.susi.ai/issues/1754

**Comment by STEdirisuriya** [comment]
@samagragupta Then I'll work for making it fixed.

**Comment by neeraj3029** [comment]
@STEdirisuriya The screenshot you have provided belongs to SUSI Skills, please make this issue in https://github.com/fossasia/susi_skill_cms/

**Comment by STEdirisuriya** [comment]
@neeraj3029 Not only that window but also in all the windows it seems same.
![image](https://user-images.githubusercontent.com/33794760/49326100-f75dda00-f572-11e8-9234-65fe7bc01140.png)

**Comment by STEdirisuriya** [comment]
Could I work on this?

**Comment by samagragupta** [comment]
You should update the issue related to chat.susi.ai

**Comment by STEdirisuriya** [comment]
@samagragupta Done.
