### ISSUE TITLE
Get error message from ajax error() when server throws API exception

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#180]
**Actual Behaviour**

When we make a server call for password recovery and it doesnt succeed, the server throws a API exception with error code and status text. But the same when queried through ajax.error() func, we always get status 404 and 'error'

**Expected Behaviour**

Get the error status and msg sent by the server

**Steps to reproduce it**

http://api.susi.ai/aaa/recoverpassword.json?forgotemail=

Opening the url directly in browser gives a status code 422 while the same when queried through ajax gives 404

**Screenshots of the issue**

![err](https://user-images.githubusercontent.com/13276887/26906520-79f4afb0-4c0b-11e7-83d6-a33a68ff4b13.png)

**Would you like to work on the issue?**

Anyone can take this up

**Comment by uday96** [comment]
If you check jQuery.ajax() documentation, you can find:

>error
A function to be called if the request fails (...) Note: This handler is not called for cross-domain script and cross-domain JSONP requests. This is an Ajax Event.

**Comment by rishiraj824** [comment]
Did error handling in `error: function()` not work ?

**Comment by uday96** [comment]
As you can see in the screenshot, we always get a status 404 and `error` message upon failure. But we dont get the actual status code and message why the request failed, sent by the server.
