### ISSUE TITLE
Map isn't show correctly.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/chat.susi.ai#1804]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/33794760/49696534-cf085800-fbd0-11e8-8e7d-a05765a2a334.png)
![image](https://user-images.githubusercontent.com/33794760/49696537-d7f92980-fbd0-11e8-9e7e-3ed3cf9e552d.png)
![image](https://user-images.githubusercontent.com/33794760/49696543-eb0bf980-fbd0-11e8-9f89-f1ae247d2fad.png)

**Expected Behaviour**

Fix it

**Would you like to work on the issue?**

Opened to all. Thank you!

**Comment by AakashMallik** [comment]
@STEdirisuriya I'll look into this

**Comment by AakashMallik** [comment]
![screenshot-localhost-3000-2018 12 09-22-10-44](https://user-images.githubusercontent.com/19551058/49700038-4d7bee80-fbff-11e8-93a9-953c203c1744.png)

@STEdirisuriya Works fine for me. Are you checking for the latest master branch?
