### ISSUE TITLE
Use helper ajax function instead of jQuery in api.actions.js

### ISSUE THREAD

**Issue by ammarbinfaisal** [fossasia/chat.susi.ai#1805]
### Actual Behaviour

Currently jquery is used for xhr in api.actions.js.

### Expected Behaviour

helper ajax function should be used instead

**Would you like to work on the issue?**

don't know how to test the changes - whether my refactoring didn't break anything?

**this is a part of already existing issue #1663**

**Comment by prateek76** [comment]
@ammarbinfaisal does removing jquery affect whole project ?

**Comment by ammarbinfaisal** [comment]
@prateek76 affect in what way? I dont get what u mean here
