### ISSUE TITLE
Connecting StatticAppBar.react.js to redux store

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/chat.susi.ai#1810]
**Actual Behaviour**

The StaticAppBar.react.js is currently linked to the old flux store.

**Expected Behaviour**

We should connect it to the newly implemented redux store.

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Hey, PR: https://github.com/fossasia/chat.susi.ai/pull/1809 does this thing
