### ISSUE TITLE
Remove jQuery from PreviewThemeChat, Blog.react.js, and MessageComposer

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1812]
**Actual Behaviour**

Currently jQuery is present in PreviewThemeChat, Blog.react.js, and MessageComposer

**Expected Behaviour**

Remove jQuery

**Would you like to work on the issue?**

Yes

**Comment by prateek76** [comment]
@fragm3  i want to work on this issue

**Comment by AakashMallik** [comment]
@prateek76 He is already working on this. Try picking up issues that have not seen any activity for more than a week.
