### ISSUE TITLE
Add smooth scrolling when clicked on UP and DOWN icons.

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#1819]
**Actual Behaviour**
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/28510494/49784946-dcdeea00-fd44-11e8-8f8a-bbd93bb954af.gif)

**Expected Behaviour**

Smooth scrolling should be their instead of directly jumping to the top/down

**Steps to reproduce it**

1) Go to https://chat.susi.ai/
2) Use UP and DOWN icons 

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by AakashMallik** [comment]
@fragm3 Could you utility be used here to address this issue?
