### ISSUE TITLE
Bug in Like and dislike button

### ISSUE THREAD

**Issue by divyabaid16** [fossasia/chat.susi.ai#1820]
**Actual Behaviour**

When the like/dislike button is clicked, it changes color only on click and then comes back to its original color. 

**Expected Behaviour**

It must retain its color after the click operation.

**Screenshots of the issue**

![like](https://user-images.githubusercontent.com/32747809/49788102-765ec980-fd4e-11e8-8346-d0236c0076ad.gif)

**Would you like to work on the issue?**

Yes

**Comment by rossoskull** [comment]
@divyabaid16 actually it's not a bug, it reverts back to original color in case of any error in skill rating.

**Comment by rossoskull** [comment]
You can notify the user of the error using a modal or so

**Comment by AakashMallik** [comment]
@divyabaid16 @rossoskull We are currently working on the api. So it will be resolved soon enough. This might not be a bug to be honest. Thanks @rossoskull for bringing this up.

**Comment by rajvaibhavdubey** [comment]
@divyabaid16 @rossoskull @AakashMallik The skill rating fails when the reply from susi is not a defined skill. View the console for the error details. :smile:

**Comment by AakashMallik** [comment]
Actually we are redoing the API for feedback. There has been some structural change, so we would probably fix all of this while integrating this with redux. @rajvaibhavdubey
