### ISSUE TITLE
Implement configurations instead of hard-coding

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#183]
Currently many configurations in the app are hard-coded, e.g. the app name, design and the server.

If other users want to install the app, they would want to use another name for their app site. Therefore, please define items in a configuration file, so they can be changed if needed.

Include the following:
* URL of SUSI.AI server
* Name of application (e.g. if a user wants to use another name)
* Enable theming (the goal is that users can add themes, that they put in a folder)
* Anything else that can be defined in a configuration file

**Comment by uday96** [comment]
will work on this :+1:

**Comment by uday96** [comment]
@mariobehling does the url of SUSI server mean the url that we are using to fetch responses i.e `api.susi.ai/susi/chat.json` ?

We can also include all the urls used for server calls like
* call to fetch responses : api.susi.ai/susi/chat.json
* call to memory servlet : api.susi.ai/susi/memory.json
* calls for the accounting system like login signup and forgot password
in the config file .

For ex, we recently had to change the server call from api.asksusi.com to api.susi.ai , so including these in config files could prove useful incase the urls change in future

**Comment by rishiraj824** [comment]
The URL configuration has been implemented #215 It means if a user wants to use a custom server of susi, he can fill in the details

**Comment by uday96** [comment]
@rishiraj824 Okay, will add that to user preferences store. Any other additions to the configuration file?

**Comment by uday96** [comment]
@daminisatya @rishiraj824 what else can be included in the configuration file?

**Comment by uday96** [comment]
The theme and server urls have been implemented already in the config or UserPrefernecesStore, I cant think of more inputs to the config file, i'll keep working on other issues and get back to this if I find anything relavant. In the meantime other devs can take this up if they want to.
@rishiraj824 @daminisatya please unassign me for now :smile:

**Comment by rishiraj824** [comment]
closing as all implementations have been done. Will open subissues if more configurations are to be added.
