### ISSUE TITLE
Login form not appearing in blog(including all section in it like overview,team and all other sections) and not found page

### ISSUE THREAD

**Issue by prateek76** [fossasia/chat.susi.ai#1847]
**Actual Behaviour**
when trying to login in blog page form is appearing

**Expected Behaviour**
login form should appear

**Steps to reproduce it**
open [https://chat.susi.ai/blog](https://chat.susi.ai/blog) and try to login

**Screenshots of the issue**

![login form not appering](https://user-images.githubusercontent.com/33982495/50003144-b29d5e80-ffc8-11e8-8370-dbd9a1f310b4.gif)

**Would you like to work on the issue?**

Yes

**Comment by prateek76** [comment]
@AakashMallik on making pr it also contains previous issue changes should i make pr

**Comment by AakashMallik** [comment]
@prateek76 Sorry, could you be more clear. I could not understand your question.

**Comment by prateek76** [comment]
@AakashMallik  i was solving some other issue and its changes are also commited in this pr

**Comment by AakashMallik** [comment]
@prateek76 you can revert specific files using git. So just revert the other files that are not related to this issue.

**Comment by prateek76** [comment]
@AakashMallik please review

**Comment by prateek76** [comment]
@AakashMallik same issue is for not found page should i make another issue or add in this, also i need help for this issue
![notfnd](https://user-images.githubusercontent.com/33982495/50045547-e8227480-00ba-11e9-8263-fc02b1293d14.gif)

**Comment by AakashMallik** [comment]
@prateek76 DM me. Let us discuss this issue and then you can implement this. I would suggest extending the issue title as this seems to be a similar problem, so can be solved under a single issue.

**Comment by prateek76** [comment]
@AakashMallik what you want can you explain me

**Comment by AakashMallik** [comment]
@prateek76 I have sent a DM to you. I have explained everything there in detail.

**Comment by prateek76** [comment]
I am working in this again

**Comment by AakashMallik** [comment]
A PR has been already opened for this.

**Comment by prateek76** [comment]
@AakashMallik can you give me some issue to work on?

**Comment by AakashMallik** [comment]
> @AakashMallik can you give me some issue to work on?

I'll let you know if something comes up. There is plently of work in the cms repo btw.
