### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by vipuldcoder** [fossasia/chat.susi.ai#1852]
**Actual Behavior**

**Expected Behavior**

**Screenshots of the issue**
http://192.168.225.137:33455/static/cutimage/ts1544938642000/storage/emulated/0/Pictures/Screenshots/Screenshot_20181216-110722.png

**Would you like to work on the issue?**

**Comment by AakashMallik** [comment]
You have not mentioned any **actual behavior** or **Expected behviour**. Also, the image you have provided does not open.
