### ISSUE TITLE
Navigation button on search bar should be correct

### ISSUE THREAD

**Issue by samagragupta** [fossasia/chat.susi.ai#1858]
**Actual Behaviour**

When UpIcon is clicked the search number is not increasing and vice-versa

**Expected Behaviour**

When UpIcon is clicked the search number should increase 

**Screenshots of the issue**

![search](https://user-images.githubusercontent.com/32234926/50141762-5a1ed780-02ce-11e9-87e0-aa07bd0a418d.gif)

**Would you like to work on the issue?**

Yes

**Comment by garvitkhandelwal** [comment]
Can I work on this issue?

**Comment by AakashMallik** [comment]
This does not look like an issue to me. When the up arrow is clicked it takes you to the text that is located above your currently selected text. There is no such convention that the topmost text should have a higher index value. I don't see the point of this issue. Could you justify it for us?
