### ISSUE TITLE
The default languages must be in alphabetical order

### ISSUE THREAD

**Issue by divyabaid16** [fossasia/chat.susi.ai#1868]
**Actual Behaviour**

All the default languages are not arranged in alphabetical order.

**Expected Behaviour**

The default languages must be arranged in alphabetical order.

**Screenshots of the issue**

![selection_041](https://user-images.githubusercontent.com/32747809/50338672-14b31200-053b-11e9-827a-9eaad67d9585.png)

**Would you like to work on the issue?**

Yes

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@divyabaid16 can i work on this?

**Comment by divyabaid16** [comment]
@RAJAGOPALAN-GANGADHARAN  I have already done the change. I'm about to submit a PR.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
😄 wow no worries.
