### ISSUE TITLE
Google play button in devices section shows error when clicked

### ISSUE THREAD

**Issue by garvitkhandelwal** [fossasia/chat.susi.ai#1871]
**Actual Behaviour**

The google play button in the devices section shows error message when clicked.

**Expected Behaviour**

It should take the user to google play where they can download the android app.

**Steps to reproduce it**

Visit https://chat.susi.ai/devices
Click on the google play button

**LogCat for the issue**

![screenshot 47](https://user-images.githubusercontent.com/24408454/50344139-b93f4f00-054f-11e9-9687-9f08035fc933.png)

**Screenshots of the issue**

![screenshot 46](https://user-images.githubusercontent.com/24408454/50343926-dfb0ba80-054e-11e9-9323-b1ad94362120.png)
This is what you get when clicking the google play button

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
There is an existing PR for this.

**Comment by garvitkhandelwal** [comment]
Let me know that issue number

**Comment by AakashMallik** [comment]
https://github.com/fossasia/chat.susi.ai/issues/1662
https://github.com/fossasia/chat.susi.ai/pull/1670

By the, you should have made sure that someone else is not working on this issue before opening the issue.
