### ISSUE TITLE
Dropdown does not disappear after choosing an option

### ISSUE THREAD

**Issue by AvaniVerma** [fossasia/chat.susi.ai#1873]
**Actual Behaviour**

When we click on any option in the drop down menu, the menu does not disappear unless the
page reloads.

**Expected Behaviour**
The drop down should disappear once an option is chosen.

**Steps to reproduce it**

On the home page, click on chat on login in settings. Even after clicking an option, the menu stays.

**Screenshots of the issue**

![error](https://user-images.githubusercontent.com/16957716/50346128-66699580-0557-11e9-87e0-5154ee1f1ab3.PNG)

**Would you like to work on the issue?**
Yes, I'll work on this one.

**Comment by AakashMallik** [comment]
Fix title

**Comment by joeedwin** [comment]
can i solve this ?

**Comment by AvaniVerma** [comment]
@joeedwin No. I'm working on this one.

**Comment by plxity** [comment]
@AvaniVerma Any progress?
