### ISSUE TITLE
Placing of hamburger icon is non-uniform on different pages

### ISSUE THREAD

**Issue by AvaniVerma** [fossasia/chat.susi.ai#1874]
**Actual Behaviour**
The hamburger icon on different pages has different right-margin. This reduces the visual appeal of the pages.

**Expected Behaviour**
The hamburger icon should have the same margin on different pages.

**Steps to reproduce it**
Compare the right-margin of the icon on home page and skills page.

**Screenshots of the issue**
![error](https://user-images.githubusercontent.com/16957716/50347051-5a330780-055a-11e9-80aa-820abaf95ab2.PNG)
![about](https://user-images.githubusercontent.com/16957716/50347096-7b93f380-055a-11e9-8398-fa3dae16d287.PNG)

**Would you like to work on the issue?**
Yes.

**Comment by garvitkhandelwal** [comment]
@AvaniVerma Can I take this issue?

**Comment by AvaniVerma** [comment]
@garvitkhandelwal No I'm working on this one already.

**Comment by AvaniVerma** [comment]
@garvitkhandelwal Sure !!
