### ISSUE TITLE
Fix Microphone toggle in Settings

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1880]
**Actual Behaviour**

Microphone toggle is not working

**Expected Behaviour**

Fix Enable mic to give voice input toggle

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
Could you show a screenshot of the issue, coz I think I have a PR open that has fixed this.

**Comment by fragm3** [comment]
<img width="595" alt="screenshot 2018-12-22 at 3 28 43 am" src="https://user-images.githubusercontent.com/18073126/50365277-b8330f80-0599-11e9-972b-652f35ecab72.png">
