### ISSUE TITLE
Menu bar is very close to the scroll bar in "About" and "Settings" section. It does not look good.

### ISSUE THREAD

**Issue by garvitkhandelwal** [fossasia/chat.susi.ai#1882]
**Actual Behaviour**

The menu bar is very close to scroll bar in **about** section. It does not look good as it is not consistent with other pages.

**Expected Behaviour**

There should be a little more margin. 

**Steps to reproduce it**

Open https://chat.susi.ai/overview
Look at the menu bar on the top right

**Screenshots of the issue**

![screenshot 51](https://user-images.githubusercontent.com/24408454/50362021-f6293700-058b-11e9-80ff-aa8e07398497.png)

**Would you like to work on the issue?**

Yes
****

**Comment by AakashMallik** [comment]
Please don't make me do this again https://github.com/fossasia/chat.susi.ai/issues/1874

**Comment by garvitkhandelwal** [comment]
I literally searched for 20min on every issue before opening this one. Just didn't use the word **hamburger**

**Comment by AvaniVerma** [comment]
@garvitkhandelwal I've opened this one before so please it.
