### ISSUE TITLE
"Here" not coming on map in dark theme

### ISSUE THREAD

**Issue by ananya-agrawal** [fossasia/chat.susi.ai#1886]
**Actual Behaviour**

![screenshot from 2018-12-13 02-03-23](https://user-images.githubusercontent.com/33188930/50372252-65854200-05f1-11e9-8668-d67cb9abb29f.png)

**Expected Behaviour**
![screenshot from 2018-12-13 02-03-43](https://user-images.githubusercontent.com/33188930/50372255-6d44e680-05f1-11e9-86b0-c57fc6800694.png)

**Steps to reproduce it**
open any location on map.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
yes

**Comment by adityavats007** [comment]
I would like to work on this issue.

**Comment by ananya-agrawal** [comment]
@adityavats007 i am working on it.
