### ISSUE TITLE
Should be able to navigate back after changing the settings.

### ISSUE THREAD

**Issue by adityavats007** [fossasia/chat.susi.ai#1889]
**Actual Behaviour**

As of now, whenever a new setting is applied then user can navigate back to the chat window by clicking on the "SUSI.AI" icon on the top-left corner.

**Expected Behaviour**

There should be a link or a button using which users can navigate back.

**Screenshots of the issue**

**Would you like to work on the issue?**
Anyone can take this issue as of now.
![screenshot 8](https://user-images.githubusercontent.com/19910046/50375009-d7bf4c00-061c-11e9-8107-064e83beaebf.png)

**Comment by AakashMallik** [comment]
We have a menu bar just for that purpose and I don't think we need separate buttons to manipulate the history stack. Plus the user can simply use the browsers back button.

@anshumanv @fragm3 @akshatnitd  Let me know your thoughts.

**Comment by anshumanv** [comment]
I don't think we need this.

**Comment by adityavats007** [comment]
@AakashMallik @anshumanv . Previously I couldn't locate the "chat" option in the dropdown menu. We do have an option for it.
