### ISSUE TITLE
The URL should change when the tab pane is changed

### ISSUE THREAD

**Issue by adityavats007** [fossasia/chat.susi.ai#1890]
**Actual Behaviour**

The current URL changes only when the save changes button is clicked after saving the changes made in settings

**Expected Behaviour**

The URL should change as soon as the tab pane is changed in settings .

![screenshot 9](https://user-images.githubusercontent.com/19910046/50375633-9df34300-0626-11e9-80ee-b3325baebd25.png)
![screenshot 11](https://user-images.githubusercontent.com/19910046/50375634-9df34300-0626-11e9-8e37-74086fbe41ee.png)

**Screenshots of the issue**

**Would you like to work on the issue?**

Not as of now

@AakashMallik any thoughts?

**Comment by AakashMallik** [comment]
I'll take a look into this.
