### ISSUE TITLE
Displaying of 'Snackbar' on top of the page.

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#1896]
**Actual Behavior**
When a user tries to search any message and in case of 'No results'. Snackbar is displayed at the bottom of the page
**Expected Behavior**
Instead of displaying on bottom of the page. It will be convenient for the user to see if is displayed on the top.

**Steps to reproduce it**
1) Go to  https://chat.susi.ai/
2) Search on any message in the App bar which is not present in the chat.

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by AakashMallik** [comment]
@plxity I don't think it is necessary plus the MUI uses snackbar at the bottom of the page.

**Comment by plxity** [comment]
@AakashMallik  Actually I tried that locally, It looks better than the original one. You can change that property by passing anchororigin props.

**Comment by AakashMallik** [comment]
@plxity But wouldn't that look inconsistent with the rest of the app where we have the snackbar appear from below. Let us see what the mentors have to say. @anshumanv  @akshatnitd @fragm3

**Comment by plxity** [comment]
@AakashMallik  Okay sure.

**Comment by Aakash-DD** [comment]
@plxity the default pop up of Snackbar is displayed at the bottom of the page, which is a good UI

**Comment by plxity** [comment]
@Aakash-DD I have implemented the snackbar on the top. I find that a better UI. Let's wait for the mentor's review.

**Comment by plxity** [comment]
@anshumanv @akshatnitd @fragm3
