### ISSUE TITLE
Theme does not change after changing the theme

### ISSUE THREAD

**Issue by joeedwin** [fossasia/chat.susi.ai#1901]
**Actual Behaviour**

Theme does not change after changing to different theme
**Expected Behaviour**

Theme  must  change to new theme after changing to different theme

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/26297616/50392492-ecaef300-0774-11e9-8365-cc66aeca337e.png)

**Would you like to work on the issue?**

yes

**Comment by AakashMallik** [comment]
I am already working on it.

**Comment by AakashMallik** [comment]
https://github.com/fossasia/chat.susi.ai/issues/1816

**Comment by Aakash-DD** [comment]
have u done on this issue, if not i will like to work on it @AakashMallik

**Comment by AakashMallik** [comment]
I have started refactoring the settings issue, this problem will be fixed in that. hopefully.
