### ISSUE TITLE
Improve UI of Dashboard section in mobile view

### ISSUE THREAD

**Issue by garvitkhandelwal** [fossasia/chat.susi.ai#1910]
**Actual Behaviour**

The **Dashboard** section does not look good in mobile view. Margins must be there.

**Expected Behaviour**

Improved UI

**Steps to reproduce it**

Open **Dashboard** from settings menu in your mobile.

**Screenshots of the issue**

![screenshot 61](https://user-images.githubusercontent.com/24408454/50432760-fd3ca600-08f9-11e9-8f5f-7a8b1e3a189d.png)

**Would you like to work on the issue?**

Yes

**Comment by plxity** [comment]
@garvitkhandelwal This issue belongs to https://github.com/fossasia/susi_skill_cms Repository. Open this issue in that Repo.
