### ISSUE TITLE
Susi doesn't know user name

### ISSUE THREAD

**Issue by Aakash-DD** [fossasia/chat.susi.ai#1914]
**Actual Behaviour**

When i ask susi "what is my name"
Susi says "**$_$1$$**"

**Expected Behaviour**
Susi could do "**I don't know, sorry or can ask for user name**"

**Screenshots of the issue**

![screenshot 23](https://user-images.githubusercontent.com/33255535/50449400-34887280-094d-11e9-9b10-f20db6940968.png)

**Would you like to work on the issue?**

yes

**Comment by AakashMallik** [comment]
Again, these things are not frontend related issues. Open these issues in susi_server.

**Comment by Aakash-DD** [comment]
where it is...?? susi_server
provide me the link buddy @AakashMallik
