### ISSUE TITLE
Don't show info about of some famous celebrity.

### ISSUE THREAD

**Issue by Aakash-DD** [fossasia/chat.susi.ai#1915]
**Actual Behaviour**

Don't show information about some of the known celebrity.

**Expected Behaviour**

Should show information on that celebrity. 

**Screenshots of the issue**

![screenshot 32](https://user-images.githubusercontent.com/33255535/50466169-ec576780-09c1-11e9-950e-5bd060edb2ee.png)

**Comment by AakashMallik** [comment]
FYI these things are not frontend related issues. Open these issues in susi_server.

**Comment by Aakash-DD** [comment]
do u have any idea related to this...?
