### ISSUE TITLE
Susi doesn't do another task in the same field !!!

### ISSUE THREAD

**Issue by Aakash-DD** [fossasia/chat.susi.ai#1916]
**Actual Behaviour**

Doesn't do another task in the same field !!!

**Expected Behaviour**

Should show other results if asked by user another time....

**Screenshots of the issue**

![screenshot 27](https://user-images.githubusercontent.com/33255535/50466282-a6e76a00-09c2-11e9-99d3-cfdc4c07bf08.png)

![screenshot 28](https://user-images.githubusercontent.com/33255535/50466302-c088b180-09c2-11e9-91f4-b3c6417b62a4.png)

**Comment by AakashMallik** [comment]
These are all server problems. Please read the code before opening issues.
