### ISSUE TITLE
Clicking on Username and avatar in Navbar should navigate user to his account settings.

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#1917]
**Actual Behaviour**

When clicked on username and avatar on the navigation bar, nothing happens.

**Expected Behaviour**

When clicked on the username on the navigation bar user should to redirected to account's settings.

**Steps to reproduce it**

1) Log in to your account
2) Click on the username in the navigation bar.

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by plxity** [comment]
There is nothing to plan in it :)
The issue is about to redirect the user to his account settings that is '/settings', When a user clicks on his avatar in navigation bar. 
That's how most of the application behaves.

**Comment by AakashMallik** [comment]
@plxity Name one. 
Also, clicking on avatar usually takes the user to their home screen and not their settings. As we don't have anything like a home component here, it would make no sense to make the avatar interactable. 
Open to discussion.

**Comment by plxity** [comment]
As you said in most of the application it redirects the user to home page. Where user  can see profile picture , username etc. In our app if we keep this it will redirect the user to setting and in that the default tab opened is account tab, where user can see profile picture , username etc. This would be provide a smooth functioning! These are my opinions. Let's see what mentor's say on this. Cheers:)

**Comment by AakashMallik** [comment]
@plxity Well, Fb, Insta all have a separate user home page, that is why clicking on profile pic makes more sense there. But yeah, why not, ask the mentors about this. @anshumanv @akshatnitd

**Comment by plxity** [comment]
Sure!

**Comment by plxity** [comment]
@anshumanv @akshatnitd What do you suggest or think about this feature?
