### ISSUE TITLE
Save Theme Setting according to the user

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#192]
**Actual Behaviour**

This is a sub-issue for #183. There is no theme setting preferred for the user. 

**Expected Behaviour**

One needs to throw the theme setting to the server.

**Would you like to work on the issue?**

Anyone can take the issue.

**Comment by uday96** [comment]
I will work on this :+1:

**Comment by uday96** [comment]
We can have a seperate store like UserPreferencesStore where we can have the default settings from which we can initialise themes and other preferences. This will make it easy to push user data onto server later if thats an option.

**Comment by uday96** [comment]
by theme preference does it mean `light` or `dark` right?

**Comment by mariobehling** [comment]
Please ensure theme settings as well as all settings in general are saved on the server itself as well. Some parts need to be implemented on the server itself.

**Comment by uday96** [comment]
@mariobehling @daminisatya @rishiraj824 This can be closed now. Implemented in https://github.com/fossasia/chat.susi.ai/pull/346 :smile:

**Comment by rishiraj824** [comment]
closing via #346
