### ISSUE TITLE
Share on LinkedIn

### ISSUE THREAD

**Issue by sk9331657** [fossasia/chat.susi.ai#1922]
**Actual Behaviour**
Share Susi on the LinkedIn option is  not present.

**Expected Behaviour**
Added Option to Share Susi on the LinkedIn option

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes.

**Comment by fliptrail** [comment]
@sk9331657 Are you working on this or should I start?

**Comment by fliptrail** [comment]
I am working on this
