### ISSUE TITLE
SUSI server broken?

### ISSUE THREAD

**Issue by BopItFreak** [fossasia/chat.susi.ai#1924]
When i got to https://api.susi.ai/susi/chat.json?q=hi

I get
HTTP ERROR 500
Problem accessing /susi/chat.json. Reason:

Server Error
Caused by:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by sk9331657** [comment]
@BopItFreak  This is an issue of Server. Report it on server repo.
