### ISSUE TITLE
Fix Preview Theme Chat In Settings

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1929]
**Actual Behaviour**

- Currently, Preview Theme Chat header(SUSI logo) out of position.
-Messaging a number of messages increases the height of the chat window.
- Max message width
- No, Send the message on 'enter' key press
- Allows to send an empty message
- Chat window width increase as the message increases, fix it

**Expected Behaviour**

Fix above bugs

**Screenshot**

<img width="103" alt="screenshot 2019-01-05 at 4 47 36 am" src="https://user-images.githubusercontent.com/18073126/50715864-0b7e8500-10a5-11e9-8171-a0c0628b57d2.png">

<img width="322" alt="screenshot 2019-01-05 at 4 49 14 am" src="https://user-images.githubusercontent.com/18073126/50715911-45e82200-10a5-11e9-9f44-c3acbf57e00e.png">

**Would you like to work on the issue?**

Yes

**Comment by neilchauhan2** [comment]
@fragm3  I would love to give this one a try.
