### ISSUE TITLE
Fetch old messages as soon as one is logged in

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#193]
**Actual Behaviour**

Currently one looks at the blank message history when he logs in.

**Expected Behaviour**

Show the previous messages of the user using the following response
```
api.susi.ai/aaa/login.json?type=access-token&login=user@example.com&password=PASSWORD
```
**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
Then what about the memory servlet? http://api.susi.ai/susi/memory.json.
The memory servlet ensures sync between all platforms too.

**Comment by rishiraj824** [comment]
@uday96 I think the old messages of the user can be fetched by passing the access token to chat.json
```
api.susi.ai/susi/chat.json?access_token=ACCESS_TOKEN
```

**Comment by uday96** [comment]
@rishiraj824 Doesn't the access token change everytime the user logs in?

**Comment by rishiraj824** [comment]
@uday96 Yes that's why I am saving the access_token every time and using that to query the chat.json file. This is how the login functionality is made currently.

**Comment by uday96** [comment]
How does it return history? Suppose I log in and have a conversation, then logout, and i log in again, will i get the history of the previous conversation too? Also, is the endpoint returning based on the user identity? Otherwise history wont be in sync across all platforms i.e android, iOS and web. And does it return the entire history? or only a few?

**Comment by rishiraj824** [comment]
@uday96 Just try to generate an access_token and pass it to the chat.json file. You'll see the history. It doesn't produce all the messages.

**Comment by uday96** [comment]
I tried, it only gives query and text. We'll have to make server calls again for every query to get the response.
> {
        "text": "YOU GOT MY JAW TO THE FLOOR WITH YOUR SLayage",
        "0": "",
        "1": "",
        "timezoneOffset": "0",
        "answer": "City of London is a place with a population of 7556900. Here is a map: https://www.openstreetmap.org/#map=13/51.51279067225417/-0.09184009399817228",
        "query": "where is london"
      },
      {
        "text": "Kamala Harris, thank you for that analogy. Putting \"hope\" back in context.",
        "query": "universities in germany"
      },

Once I logged out and logged in again, and queried with the new access token, the previous sessions messages werent there.

Please try and confirm?

**Comment by uday96** [comment]
Worked it out. Use http://api.susi.ai/susi/memory.json?access_token=<ACCESS_TOKEN> for fetching history. It maintains sync too across all platforms and you can use the current access_token when the user logged in to retrieve history of previous sessions too across all platforms

**Comment by rishiraj824** [comment]
@uday96 Awesome, will use this then. Just need to change the url in the gethistory() right? But won't the access_token change every time i logout and login again?

**Comment by uday96** [comment]
I tried getting a new access_token and calling the server with the old access token, it still gave correct history. But I guess using the new access_token everytime would be better. Find a workaround :+1:

**Comment by rishiraj824** [comment]
Okay, cool then.
