### ISSUE TITLE
Add Scroll Up and Down button similar to susi chromebot.

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#1932]
**Actual Behaviour**
It has two different button for scroll up and down.

**Expected Behaviour**
It can be reduced to one one button, similar to susi chromebot.
![capture](https://user-images.githubusercontent.com/28510494/50724976-62737100-111c-11e9-8c76-311ef93cce83.PNG)

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by plxity** [comment]
@akshatnitd @anshumanv What do you suggest? Can it be implemented in this?

**Comment by AakashMallik** [comment]
@plxity So say you are midway in the chat. Which of the two buttons will you show to the user? UP or DOWN? :wink:

**Comment by plxity** [comment]
@fragm3 Okay No issues.
