### ISSUE TITLE
Write new test cases for the App

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#194]
**Actual Behaviour**

Currently, lots of changes are added, but there are no test cases

**Expected Behaviour**

New Test cases should be added in _tests_ using jest.

**Would you like to work on the issue?**

Anyone can take this up.

**Comment by isuruAb** [comment]
working on this

**Comment by AnshulMalik** [comment]
@isuruAb Still working?

**Comment by isuruAb** [comment]
@AnshulMalik  if you are interested  you can work on it

**Comment by rishiraj824** [comment]
I'll work on this
