### ISSUE TITLE
Integrate Redux In StaticAppBar, TopBar

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1941]
**Actual Behaviour**

Redux is not integrated for TopBar, fix StaticAppBar code

**Expected Behaviour**

Integrate for TopBar, fix StaticAppBar code

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
https://github.com/fossasia/chat.susi.ai/issues/1810 Would it be okay for you to just work on the TopBar. I was actually waiting for your getAdmin PR to get merged to work on the staticAppBar. Let me know if you are okay with this.

**Comment by fragm3** [comment]
@AakashMallik I have already created issue, please wait for https://github.com/fossasia/chat.susi.ai/issues/1808, its been pending from a long time.

**Comment by AakashMallik** [comment]
@fragm3 Sure bro... no problem...

**Comment by fragm3** [comment]
Thanks man
