### ISSUE TITLE
Propose a workaround for the case when the captcha fails to load

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/chat.susi.ai#1947]
**Actual Behaviour**

As of now, if the server fails to respond with captcha key, then the captcha doesn't load. But that will also mean that the user won't be able to signup.

**Expected Behaviour**

Propose a workaround for this.

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
@akshatnitd @anshumanv What should be do about this? I was thinking to tell the user to either reload the app, or may be let the user pass without the captcha.

**Comment by anshumanv** [comment]
And we can't test it on deployment links too, proly allow if not present?
