### ISSUE TITLE
Call getAdmin api in componentDidmount (App.js) and login only

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/chat.susi.ai#1958]
**Actual Behaviour**

As of now, this api is being called only during login. 

**Expected Behaviour**

Ideally, it should be called when the app starts so that an already logged in user can be verified as admin.

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@AakashMallik it's also called inside TopBar, StaticAppBar menu

**Comment by AakashMallik** [comment]
@fragm3 exactly..  which is not desirable... so i'll be removing those calls from the bars...
