### ISSUE TITLE
Disable the email field in account Tab.

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#1966]
**Actual Behaviour**
As we are not able to change the value in the email field. But still a user can click on the field.

**Expected Behaviour**

Disable the email field. 

**Steps to reproduce it**

1) Go to https://chat.susi.ai/settings?tab=Account
2) Click on email field.

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by AakashMallik** [comment]
An exciting PR has taken care of this issue...  that PR has not been finalised due to some dealy from server side. This issue may be closed.

**Comment by plxity** [comment]
@AakashMallik  Which exciting PR are you talking about?

**Comment by AakashMallik** [comment]
I am on my phone right now so will be a little hard for me to post the exact link but the PR that is connecting the Settings component with redux.

**Comment by AakashMallik** [comment]
should be easy to find in the PR list.

**Comment by plxity** [comment]
@AakashMallik  Okay got it.
