### ISSUE TITLE
Message info alignment issue

### ISSUE THREAD

**Issue by zerefwayne** [fossasia/chat.susi.ai#1969]
**Actual Behaviour**

The time, share, upvote, downvote should be equally spaced and centre aligned.

**Expected Behaviour**

These should be centre aligned.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/28949397/51459735-858a5b80-1d7f-11e9-9980-0a3f0392c04d.png)

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
@zerefwayne Good catch... :white_check_mark:
