### ISSUE TITLE
Reply button changes colour on hover [feature]

### ISSUE THREAD

**Issue by zerefwayne** [fossasia/chat.susi.ai#1978]
**Actual Behaviour**

The buttons in susi's reply don't become blue after hovering. (Adding a feature)

**Expected Behaviour**

They should become blue once hovered.

**Screenshots of the issue**

![hover](https://user-images.githubusercontent.com/28949397/51561271-c6cc5980-1eac-11e9-8d72-9c40136de418.gif)

**Would you like to work on the issue?**

Yes

**Comment by plxity** [comment]
@zerefwayne Yeah, I think this a good feature.
