### ISSUE TITLE
Placeholder text is not aligned properly

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#1989]
**Actual Behaviour**

![capture](https://user-images.githubusercontent.com/28510494/51675831-dce83000-1ffa-11e9-90a1-2c19f46ea879.PNG)

**Expected Behaviour**

Placeholder text in the password field and text in Login Button should be aligned properly.

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by fliptrail** [comment]
@plxity Are you still working on this issue or I shall see to it?

**Comment by plxity** [comment]
@fliptrail I am busy with other stuff. You can work on it if you want.

**Comment by rajshah9914** [comment]
@fliptrail I have already aligned the placeholder for password, so if you don't mine , can I work on this issue, you can work with login alignment if you want to, actually I didn't see this already created issue before and I was going to make a new issue today same as this..
