### ISSUE TITLE
Change the login URL on SignUp page

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#199]
**Actual Behaviour**

http://chat.susi.ai/signup The login URL on this page is incorrect

**Expected Behaviour**

The URL needs to be changed

**Comment by madhavrathi** [comment]
I want to work on this.

**Comment by uday96** [comment]
The same in forgot password page also.

**Comment by uday96** [comment]
https://github.com/fossasia/chat.susi.ai/issues/200 , the same here. change the route of chat anonymously button in the login dialog

**Comment by uday96** [comment]
@madhavrathi please fix https://github.com/fossasia/chat.susi.ai/issues/200 also. I have closed https://github.com/fossasia/chat.susi.ai/issues/200 as it is similar to this issue.

**Comment by rishiraj824** [comment]
closing this via #210
