### ISSUE TITLE
notFound: login and signup button does not work

### ISSUE THREAD

**Issue by AdityaSrivast** [fossasia/chat.susi.ai#1999]
**Actual Behaviour**

Currently, the login and signup buttons on the not found page does not work.

**Expected Behaviour**

It should work

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/31389740/51764398-20c25e80-20fb-11e9-9bdb-93bf00d68ed3.png)

**Would you like to work on the issue?**

Yes.

**Comment by AdityaSrivast** [comment]
@Mishra121 I'm already working on it.

**Comment by fliptrail** [comment]
@AdityaSrivast Still working on it or can I start?

**Comment by AdityaSrivast** [comment]
@fliptrail Thanks for reminding. If I don't make a PR by tomorrow, you can take it up

**Comment by parammittal16** [comment]
@AdityaSrivast can I do this ??

**Comment by AdityaSrivast** [comment]
@parammittal16 Sure. Go ahead
