### ISSUE TITLE
Add a feature to check if an email ID is available in real time while user enters the emailID

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/chat.susi.ai#2006]
**Actual Behaviour**

As of now, the user has to enter the email id and all the other details and press the submit button to see if the emailID is actually available. 

**Expected Behaviour**

A feature should be introduced so that this process can be done in real time and thus the user would know if the email ID is available as soon as he fills the email ID field. 

**Would you like to work on the issue?**

Yes

**Comment by Nathandrake229** [comment]
exactly where did you find this issue?
kindly tell

**Comment by AakashMallik** [comment]
Issue? this is a feature request. U can see this feature in action in most of the popular apps out there. Do you want me to link some example apps? :smiley:

**Comment by AakashMallik** [comment]
@Nathandrake229

**Comment by Nathandrake229** [comment]
Yes please
It will help me understand the issue better

**Comment by AakashMallik** [comment]
@Nathandrake229 Try creating an account in instagram.

**Comment by Nathandrake229** [comment]
Yes I understand it's a skill to be added
It would have to be able to access the Instagram server to confirm whether
the account exists
Maybe by applying it's API would do the trick
