### ISSUE TITLE
Sign up button is not working

### ISSUE THREAD

**Issue by Parth910** [fossasia/chat.susi.ai#2020]
**Actual Behaviour**

On  the page [ https://chat.susi.ai/support]( https://chat.susi.ai/support), below  "get started today" sign up button is not working

**Expected Behaviour**

On clicking sign up button, sign up window should open.

**Comment by AakashMallik** [comment]
@Parth910 Will be covered under this issue https://github.com/fossasia/chat.susi.ai/issues/1954 . You may close this.
