### ISSUE TITLE
Adding underline feature on hover on login page

### ISSUE THREAD

**Issue by varnika2212** [fossasia/chat.susi.ai#2025]
**Actual Behaviour**

No underline when we hover on the given text.

**Expected Behaviour**
It should be underlined when we hover upon it.

**Screenshots of the issue**

![underlineproblem](https://user-images.githubusercontent.com/32407962/52189877-68668a00-2861-11e9-8174-799df0250402.PNG)

**Would you like to work on the issue?**
yes.

**Comment by AakashMallik** [comment]
Underline what exactly?

**Comment by varnika2212** [comment]
"forgot password" and "sign-up for susi"

**Comment by AakashMallik** [comment]
Ohkay, that is one way to talk to a fellow contributor. Every suggestion is open to discussion and taking suggestions as an act of apprehension is not really a great way to start for a rookie, but sure, go ahead.

**Comment by anshumanv** [comment]
@AakashMallik it's okay to go ahead with this for now, there will be major revamp in summers so a lot of things are gonna change.

@varnika2212 thanks for this but please be a little more open to suggestions/discussions as they're important in open source, all the best! 🎉
