### ISSUE TITLE
Color of delete my account in https://chat.susi.ai/settings should be same as https://accounts.susi.ai/settings

### ISSUE THREAD

**Issue by prateek76** [fossasia/chat.susi.ai#2027]
**Actual Behaviour**

Color of delete my account in https://chat.susi.ai/settings and accounts.susi.ai are different

**Expected Behaviour**

Color of delete my account in https://chat.susi.ai/settings should be red as it is in accounts.susi.ai
because its better to keep deleting option in red color

**Steps to reproduce it**

open https://chat.susi.ai/settings and https://accounts.susi.ai/settings to see the difference

**Screenshots of the issue**

https://chat.susi.ai/settings screenshot - 
![feature](https://user-images.githubusercontent.com/33982495/52196017-3f092680-2880-11e9-86fd-d3cb6c889d92.PNG)

https://accounts.susi.ai/settings screenshot -
![goo](https://user-images.githubusercontent.com/33982495/52196104-90191a80-2880-11e9-90c9-44a39f840b62.PNG)

**Would you like to work on the issue?**

yes

**Comment by prateek76** [comment]
@AakashMallik should i make this change?

**Comment by AdityaSrivast** [comment]
@prateek76 I am already working on this issue. Please close it
