### ISSUE TITLE
Login Button Not Working in Dashboard

### ISSUE THREAD

**Issue by Puranjay25** [fossasia/chat.susi.ai#2028]
**Actual Behaviour**

When you go to Dashboard the "Login" Button is not responding to any event when clicked.

**Expected Behaviour**

Fix this issue

**Steps to reproduce it**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20750726/52206983-fcf0dc80-28a1-11e9-8a4c-8d55bea53d1d.gif)

**LogCat for the issue**

**Comment by harshil1712** [comment]
Can I take this?

**Comment by Puranjay25** [comment]
@harshil1712 Yeah Sure

**Comment by harshil1712** [comment]
It seems to work fine for me

**Comment by harshil1712** [comment]
The user logins in on his local machine, but as he/she goes to the dashboard the user is taken to the susi website, and not to the local page. Hence the error
