### ISSUE TITLE
Languages dropdown overlapping SearchBar 

### ISSUE THREAD

**Issue by mann27** [fossasia/chat.susi.ai#2034]
Languages Dropdown in the skills section overlapping the search bar.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/33790390/52517575-499e3400-2c63-11e9-9944-3adfa03af031.png)

I would like to take up this issue.

**Comment by mann27** [comment]
Can someone guide me through the codebase so that I can fix the issue.Thanks!

**Comment by plxity** [comment]
@mann27 This issue belongs to https://github.com/fossasia/susi_skill_cms repo.

**Comment by mann27** [comment]
Ok, I will make a copy of the issue there.thanks!
