### ISSUE TITLE
Colour inaccuracy in login credential

### ISSUE THREAD

**Issue by ashwaniYDV** [fossasia/chat.susi.ai#2039]
**Actual Behaviour**
![capture](https://user-images.githubusercontent.com/43786728/52537044-f5d93b00-2d87-11e9-9875-06d551801e6c.PNG)

**Expected Behaviour**
Yellowish color of input field should not come out of div.

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
@ashwaniYDV Which browser are you using?

**Comment by ashwaniYDV** [comment]
I'm using google chrome.

**Comment by ashwaniYDV** [comment]
I've checked it on firefox and edge and its fine there. But this issue occurs in chrome
