### ISSUE TITLE
Inaccurate positioning of topRightMenu

### ISSUE THREAD

**Issue by ArexJambusarwala** [fossasia/chat.susi.ai#2041]
**Actual Behaviour**

![issue1](https://user-images.githubusercontent.com/35253743/52609165-55c40480-2ea2-11e9-8119-9e9737982e04.png)
It is difficult for the user to find it.

**Expected Behaviour**

![corrected1](https://user-images.githubusercontent.com/35253743/52609204-73916980-2ea2-11e9-9d25-a067d5f15d61.png)

This is how it is in the homepage:

![corrected2](https://user-images.githubusercontent.com/35253743/52609319-db47b480-2ea2-11e9-80fc-15da17a77abd.png)

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Already fixed, closing issue.
