### ISSUE TITLE
Incorrect positioning in login form

### ISSUE THREAD

**Issue by ashwaniYDV** [fossasia/chat.susi.ai#2043]
**Actual Behaviour**
Password field and login text in login buttonis wrongly positioned in login form.

**Expected Behaviour**

Password field should be styled same as email field.

**Screenshots of the issue**

![1f215213-adaf-45aa-8e3e-2c9665a3e076 png](https://user-images.githubusercontent.com/43786728/52690540-0a822280-2f84-11e9-8845-f5043b400a35.jpg)

**Would you like to work on the issue?**

Yes

**Comment by kushthedude** [comment]
Is this issue still open? @ashwaniYDV

**Comment by Safnaj** [comment]
Is this issue fixed ??

**Comment by fragm3** [comment]
Already fixed, closing issue.
