### ISSUE TITLE
tightly couple verify password and new password

### ISSUE THREAD

**Issue by ArexJambusarwala** [fossasia/chat.susi.ai#2049]
**Actual Behaviour**

When something is entered in the fields and the removed, the validation text remains.

**Expected Behaviour**

The validation text should not be displayed when the fields are empty.

**Steps to reproduce it**

1. Settings -> Password
2. Type something in any of the 3 inputs requested.
3. Clear the input.

**Screenshots of the issue**

![issue7](https://user-images.githubusercontent.com/35253743/52836949-be191d00-3112-11e9-87c7-af55acb72fd8.png)

**Would you like to work on the issue?**

Yes

**Comment by HSR05** [comment]
Is it still open? I would like to take up this issue.
Can you guide me a little @ArexJambusarwala

**Comment by AakashMallik** [comment]
@HSR05 A PR has already been submitted for this. So I guess this is taken up.

**Comment by fragm3** [comment]
Closing issue, already fixed.
