### ISSUE TITLE
Unfortunately,Package installer has stopped.

### ISSUE THREAD

**Issue by Ashish-cse38** [fossasia/chat.susi.ai#2054]
**Actual Behaviour**

It asks for 3 permissions :1.Location access,2.Sound recording,3.Media file access.
If any of the above permissions not given, then after reopening the app a message "Unfortunately,Package installer has stopped." shows and app closes.

**Expected Behaviour**

App should open doesn't matter if permissions given or not.
It should ask for permission again if user is doing something in which that permission is required.

**Steps to reproduce it**

1.Download the app.
2.Do login or skip.
3.Don't give any one or more permissions.
4.Close and reopen the app.

**LogCat for the issue**

**Screenshots of the issue**
![error](https://user-images.githubusercontent.com/33326109/52918418-c0e75e00-331c-11e9-8f6b-bd2e06692c27.jpg)

**Would you like to work on the issue?**

Yes.

**Comment by naman653** [comment]
Are you out of your mind or a complete noob. This is the issue for susi android app.
