### ISSUE TITLE
Reset button in edit theme relaods the webpage

### ISSUE THREAD

**Issue by fliptrail** [fossasia/chat.susi.ai#2055]
**Actual Behaviour**

Reset button in edit theme menu reloads the whole web page

**Expected Behaviour**

Reset button should just close the dialog box or reset colors to deafult value without reloading web page

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
There is a PR https://github.com/fossasia/chat.susi.ai/pull/1926 that is supposed to take care of all these things. Avoid making changes to the settings component, the refactor PR should take care of all that.

**Comment by fliptrail** [comment]
Okay!
