### ISSUE TITLE
Highlight on upvote/downvote

### ISSUE THREAD

**Issue by 123vivekr** [fossasia/chat.susi.ai#2057]
**Actual Behaviour**

When the user upvotes/downvotes a message, it should be highlighted. I have upvoted the message but currently there is no highlighting.

![20190222_204418](https://user-images.githubusercontent.com/28249428/53251585-058b4480-36e3-11e9-8158-e3cd7b366be5.png)

**Expected Behaviour**

Highlight the thumbs up/thumbs down emoji on upvote/downvote

**Would you like to work on the issue?**

Yes.

**Comment by isuruAb** [comment]
@123vivekr  any update ?

**Comment by 123vivekr** [comment]
@isuruAb I'm not working on this. I'm currently engaged in another project.

**Comment by fragm3** [comment]
Upvote, downvote not yet implemented on the backend. Currently, this PR is out of scope, closing.
