### ISSUE TITLE
Add snackbar duration, snackbar aciton and snackbar action handler support to ui-reducer

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/chat.susi.ai#2060]
**Actual Behaviour**

As of now, we only have the state variables to just open and close the snackbar

**Expected Behaviour**

The snackbar component must support snackbar duration, snackbar actions and snackbar action handler functions.

**Would you like to work on the issue?**
Yes

**Comment by fragm3** [comment]
Already implemented. Closing
