### ISSUE TITLE
Upgrade material-ui to @material-ui/core

### ISSUE THREAD

**Issue by rossoskull** [fossasia/chat.susi.ai#2069]
**Actual Behaviour**

The current version of Material UI module being used for this project is now deprecated, and should be changed to @material-ui/core module.

**Expected Behaviour**

Use new module with support

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
I would like to work on this.

**Comment by rossoskull** [comment]
Sure @fragm3

**Comment by fragm3** [comment]
Continuing with the following:
 - Settings Left Menu
 - StaticAppBar
 - Blogs
