### ISSUE TITLE
Fixing save changes button position and alignment from bottom and left

### ISSUE THREAD

**Issue by prateek76** [fossasia/chat.susi.ai#2076]
**Actual Behaviour**

The button is stuck to the bottom

**Expected Behaviour**

The button should be at the center or aligned at the left with some padding in the bottom and left.

**Steps to reproduce it**

Open https://chat.susi.ai/settings and go to speech tab.

**Screenshots of the issue**

![button fix](https://user-images.githubusercontent.com/33982495/56152139-84f51000-5fd0-11e9-8fc2-e19683369d35.PNG)

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Already fixed, closing issue.
