### ISSUE TITLE
Use axios for calling API's in Settings

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/chat.susi.ai#2083]
**Actual Behaviour**
Currently the action and reducer are present but not used.

**Expected Behaviour**
Use the action and reducer present in Settings.react.js

**Would you like to work on the issue?**
Yes

**Comment by meetzaveri** [comment]
Hey Harsh, I would like to know that how many files currently you've refactored to axios config/impletn?

**Comment by fragm3** [comment]
@meetzaveri The app is already refactored if you want to collaborate more actively, join gitter channel https://gitter.im/fossasia/susi_webchat

**Comment by fragm3** [comment]
Closing this, already implemented.

**Comment by meetzaveri** [comment]
Okay, sure then!
