### ISSUE TITLE
Login Button of the signUp page navigate to a blank page

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#209]
**Actual Behaviour**

When user clicks on the login button of the signup page it redirects user to blank page.

**Expected Behaviour**

It should open the signUp light box instead of moving to another location.

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.
<img width="472" alt="screen shot 2017-06-10 at 7 49 38 am" src="https://user-images.githubusercontent.com/7692626/26999194-687a2d58-4db1-11e7-887c-9107c6421eb1.png">
redirect to this URL and page
<img width="389" alt="screen shot 2017-06-10 at 7 47 39 am" src="https://user-images.githubusercontent.com/7692626/26999183-2c323412-4db1-11e7-9dbb-67b3865beb53.png">

**Would you like to work on the issue?**

yes

**Comment by uday96** [comment]
same as https://github.com/fossasia/chat.susi.ai/issues/199

**Comment by isuruAb** [comment]
@uday96  now i saw that . little bit late but it is okay i will close this 👍
