### ISSUE TITLE
Navbar box should close when clicked on it's element.

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#2090]
**Actual Behaviour**

![qq](https://user-images.githubusercontent.com/28510494/57747616-f4574000-76f3-11e9-9f86-17cc2e6cf1bd.PNG)

As of now, the navbar box doesn't close when clicked on it's element.
**Expected Behaviour**

The Navbar box should automatically close when clicked on any on its element

**Steps to reproduce it**

**Would you like to work on the issue?**

Yes, I would like to wotk on this.

**Comment by fragm3** [comment]
@plxity It is working fine for me. Could you share a GIF of bug

**Comment by plxity** [comment]
@fragm3 Okays sure,
But for you, the navbar box closes as you click on any of its elements?

**Comment by fragm3** [comment]
@plxity yes it works fine for me

**Comment by plxity** [comment]
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/28510494/57772655-9cd8c480-7733-11e9-8d10-6e694e359538.gif)
@fragm3

**Comment by fragm3** [comment]
@plxity Yeah, for Login not closing for me either.

**Comment by plxity** [comment]
@fragm3 Even for "Share" it isn't working for me.

**Comment by fragm3** [comment]
Closing this, already fixed.
