### ISSUE TITLE
Search input field is not displayed properly

### ISSUE THREAD

**Issue by plxity** [fossasia/chat.susi.ai#2110]
**Actual Behaviour**

![Capture1](https://user-images.githubusercontent.com/28510494/57987563-ac903a00-7aa0-11e9-8aec-f0b69602ac09.PNG)

**Expected Behaviour**

The search field should be displayed properly.

**Steps to reproduce it**

Click on the search icon.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by harsh-jindal** [comment]
@plxity Are you working on this?

**Comment by plxity** [comment]
@harsh-jindal Yes, I am working on it.
