### ISSUE TITLE
Migrate CMS into Chat Repo

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/chat.susi.ai#2134]
**Actual Behaviour**
* Currently they are 2 separate repos

**Expected Behaviour**
* CMS should be integrated to this repo, under /skills route

- [x] Move Home Page and category, language pages
- [x] Move Skill details pages
- [ ] Move Botbuilder
- [ ] Move Skill creator, Skill editor
- [ ] Move Skill History, version
- [ ] Dashboard
- [ ] Admin

**Would you like to work on the issue?**
Yes. Also, @fragm3 , @harsh-jindal

**Comment by akshatnitd** [comment]
Working on the 1st point.

**Comment by fragm3** [comment]
@akshatnitd please allot which files I and @harsh-jindal have to migrate to chat.susi.ai

**Comment by akshatnitd** [comment]
@fragm3 I would suggest you and @harsh-jindal to start once I send a PR tonight with the home page migration. Post that, you all can select any of the checkpoint from above and start working, after commenting here.

**Comment by fragm3** [comment]
Awesome

**Comment by fragm3** [comment]
Collaborating with @harsh-jindal to migrate `Skill details pages`

**Comment by fragm3** [comment]
Edit: I have worked on `Skill Details Page`

@harsh-jindal will migrate the Botbuilder, Skill creator, Skill editor, Skill History, version, Dashboard

Following up on it, i'll migrate Admin component, once https://github.com/fossasia/susi_skill_cms/pull/2001 is merged

**Comment by harsh-jindal** [comment]
@fragm3 I'll send a PR for the above mentioned work by tonight.
