### ISSUE TITLE
Can't go to SignUp page using URL

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#221]
**Actual Behaviour**

When we navigate to signup page by clicking top right corner button it works correctly.but when we click on this link directly it moves to 404 page http://chat.susi.ai/signup

**Expected Behaviour**

User should have ability to move to signup page directly by clicking this url.
http://chat.susi.ai/signup

**Would you like to work on the issue?**

yes

**Comment by rishiraj824** [comment]
@isuruAb How are you proceeding with this? As far as I know <Link to="/" /> can be only used to navigate between the links while using `react-router`. Given that this is a static single page.
