### ISSUE TITLE
Remove warnings and error messages

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#229]
**Actual Behaviour**

Currently there are some deprecated packages and errors resulting from them

**Expected Behaviour**

Clear errors from the console and test

**Steps to reproduce it**

`npm run test`

**Screenshots of the issue**

![screenshot from 2017-06-12 13 21 14](https://user-images.githubusercontent.com/11540785/27024334-d23be1a0-4f73-11e7-957f-9e853b57bd82.png)
![screenshot from 2017-06-12 13 19 58](https://user-images.githubusercontent.com/11540785/27024335-d4ec63d4-4f73-11e7-8379-8eec74ad42e8.png)

**Comment by madhavrathi** [comment]
Will try to resolve this .

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb i have made changes according to this https://stackoverflow.com/questions/43303761/accessing-proptypes-via-the-main-react-package-is-deprecated

but the warning signs are still showing up. Please review the commit https://github.com/madhavrathi/chat.susi.ai/commit/1e44c9cee4703cf13399d8383137345204c4e9a1
and suggest what more needs to be done.

PS:I came across a fact that react 15.xx is showing these warnings, so i also tried downgrading to 14.xx, still no luck.
Thanks

**Comment by AnshulMalik** [comment]
I can't see these warnings Node v.7.0.0

**Comment by rishiraj824** [comment]
closing as fixed now
