### ISSUE TITLE
Speech to Text feature for Web

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#232]
**Expected Behaviour**

User should be able to send messages through speech similar to other clients.

One implementation procedure could be to use **CMU's Pocket Sphinx**
**Demo** - https://syl22-00.github.io/pocketsphinx.js/
**Pocket Sphinx** - https://www.npmjs.com/package/pocketsphinx

Please suggest more implementaion features @uday96 @isuruAb @madhavrathi

**Comment by betterclever** [comment]
@rishiraj824 pocketsphinx does not give even usable performance if we consider full vocabulary based STT. You may use Google STT or IBM Watson Services. They both are very good. IBM Watson has best free tier.

I am also considering a server based speech handling in this issue that aims at solving speech requirements for all clients. https://github.com/fossasia/susi_hardware/issues/28 .Please join the discussion and give input.

**Comment by rishiraj824** [comment]
@betterclever Sure, let's go with IBM Watson if that's the case. I will go through the docs and propose an idea.

**Comment by rishiraj824** [comment]
closing via #396
