### ISSUE TITLE
Proposal for feedback system of SUSI responses

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#247]
**Actual Behaviour**

 No feedback system for SUSI responses is present currently

**Expected Behaviour**

SUSI responses must have a like or dislike option
This can be used for guided learning

Come up with a proposal to implement the guided learning system.

@rishiraj824 @isuruAb @madhavrathi please share your ideas.

**Comment by rishiraj824** [comment]
@uday96 Even if we record the like and unlikes, how are we planning to maintain this in the client?

**Comment by uday96** [comment]
We must send the feedback to server I guess. This needs server side implementation too.
We need to know how things will be handled in the server and what all information the server needs.
The basic implementation from the client side according to me must be:
 * Have a like or dislike option for each susi response
 * Incase the user dislikes an answer, maybe show a pop up with predefined list of reasons as to why the user was not satisfied with the answer (the options will also depend on how the server wants the feedback to be)
* sending the feedback back to the server (should it be sent back for every response?)

We first need to know the server side implementation as in what all info the server needs based on that we can proceed on the client side implementation.

**Comment by rishiraj824** [comment]
@saurabhjn76 @dynamitechetan @DravitLochan Please give your inputs and create issues on the server for this feature.

**Comment by dynamitechetan** [comment]
We cannot rate every response. Most of the response are dynamic and sent from various APIs.
So we can have an API Endpoint where you post the Expert Name (which contains the skill) and the rating/feedback of that expert, and then we can store that rating/feedback at the server.

**Comment by saurabhjn76** [comment]
Even I agree with @dynamitechetan, at present we can rate an expert files based on matched skills. But there could be certain problems like a good expert might get poor feedback because of a particular skill. So we need to find some way to rate skills rather than an expert.

**Comment by rishiraj824** [comment]
closing as implemented
