### ISSUE TITLE
ipinfo.io blocked by client

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#248]
**Actual Behaviour**

Currently, the IP info is showing an error for some clients.

**Expected Behaviour**

It should take the IP from the user client.

**Steps to reproduce it**

Query `where am i` This also happened when it was loaded from a message from history

**Screenshots of the issue**
![screenshot from 2017-06-13 19 13 20](https://user-images.githubusercontent.com/11540785/27085314-88b5a9ae-506c-11e7-8622-4a614aa601b0.png)
![screenshot from 2017-06-13 19 13 07](https://user-images.githubusercontent.com/11540785/27085319-8b43c066-506c-11e7-80dc-c0dbaeea55fe.png)

**Comment by uday96** [comment]
@rishiraj824 If the latitude and longitude are not given as parameters to the server, then the server must handle it accordingly. Currently it is a bug in the server for responses like `where am i` as it server is responding with $latitude$ $longitude$ in response when it should do so. refer - https://github.com/fossasia/susi_server/issues/269

**Comment by rishiraj824** [comment]
@uday96 Okay, lets keep this issue open until https://github.com/fossasia/susi_server/issues/269 fixes

**Comment by uday96** [comment]
Will add implementation to fetch location using the inbuilt geolocation api for the client upon ipinfo.io failure :+1:

**Comment by uday96** [comment]
Used https://tutorialzine.com/2016/06/quick-tip-detecting-your-location-with-javascript to fetch clients location based on GPS or WIFI first and if that fails then call ipinfo.io . But Chrome gives an error `Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)` saying we need https to query client location. Any work around possible?

**Comment by rishiraj824** [comment]
closing via #344
