### ISSUE TITLE
The full content present in a column, not shown in table type output.

### ISSUE THREAD

**Issue by Manveer695** [fossasia/chat.susi.ai#253]
**Actual Behaviour**
When we hover over a name in a column in table type output, the full content of that column is not shown.

**Expected Behaviour**
The content on that column should be shown into a text box above it like this:
![screenshot 236](https://user-images.githubusercontent.com/20307535/27120362-d6604666-5100-11e7-843b-c8b9895308b6.png)

**Screenshots of the issue**
In this screenshot, if we hover over an author name in this table its full content is not shown.
<img width="418" alt="webchathovertitle" src="https://user-images.githubusercontent.com/20307535/27120545-a43d3648-5101-11e7-808a-05b2d199cfda.PNG">

**Would you like to work on the issue?**
@isuruAb, would you like to work on it?

**Comment by uday96** [comment]
same as https://github.com/fossasia/chat.susi.ai/issues/133 . But the hover idea seems better than autosizing the table :+1:

**Comment by Manveer695** [comment]
@uday96 So should we close that or this?

**Comment by uday96** [comment]
@Manveer695 Lets close  #133 :+1:

**Comment by uday96** [comment]
Will work on this :+1:
