### ISSUE TITLE
Make websearh rss results UI similar to android iOS clients

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#261]
**Actual Behaviour**

The current UI for websearch rss results uses a carousel like display

**Expected Behaviour**

UI must be made similar to android iOS clients which are also similar to the google assistant UI

**Steps to reproduce it**

Sample query : 
websearch : search for *
rss : stock quotes

**Screenshots of the issue**

![screenshot from 2017-06-14 19 25 00](https://user-images.githubusercontent.com/13276887/27166471-81d43fae-51b8-11e7-884e-414413fb9fd6.png)

**Would you like to work on the issue?**

Anyone can take this up

 I tried a lot of modules including
[react-swipe](https://github.com/voronianski/react-swipe)
[nuka-carousel](https://github.com/FormidableLabs/nuka-carousel)
[react-slick](https://github.com/akiran/react-slick)
But faced issues with all of them, so I ended up using the current [react-responsive-carousel](https://github.com/leandrowd/react-responsive-carousel) module

**Comment by rishiraj824** [comment]
@uday96 what was the issue with http://neostack.com/opensource/react-slick ?

**Comment by uday96** [comment]
The problems faced with each were:

* **react-slick** : `matchMedia not present, legacy browsers require a polyfill`
  The module was the best suited for carousel display and had indicators and control arrows also and was running perfectly fine upon `npm start` too. But it was giving `matchMedia not present ` error upon `npm test` and the work around mention in their site page did not work and also we cannot display more than one result tile i guess.

* **nuka-carousel** : This was also a good option for carousel display, but we have to write our custom decorators for control arrows and indicator dots which i did, but displaying more than one result like in android iOS wasnt working properly - width issues and also upon rendering the scrollbar was a little bit off the bottom which i couldnt fix

* **react-swipe** : simple swipable component without any carousel overlay and rendering is also fine, but couldnt display more than one tile like other clients and also dint have control arrows or indicator dots

**Comment by uday96** [comment]
* We must remove the `Know More` link in the bottom and instead hyperlink the entire tile.
* Have a swipeable list of tiles similar to google assistant instead of a carousel display

**Comment by rishiraj824** [comment]
I will implement this :+1:
