### ISSUE TITLE
SUSI Search in message section not working

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#268]
**Actual Behaviour**

message search in susi web is not working due to recent merges.

**Would you like to work on the issue?**

Yes, i will find the typo made in recent commits , fix it and send PR 
thanks.

**Comment by madhavrathi** [comment]
this is fixed but a part is yet to be solved, the text in search section is black , will fix to become white.
i will work on this and send PR

**Comment by rishiraj824** [comment]
@madhavrathi is this issue fixed?

**Comment by madhavrathi** [comment]
Yes
