### ISSUE TITLE
Implement Voice on Chrome

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#277]
The Google Search shows a voice activation icon that can be used in the Chrome Browser.

Please implement the same feature on the web chat.
![screenshot from 2017-06-17 16-43-00](https://user-images.githubusercontent.com/1583873/27253842-7c4c3cec-537c-11e7-8270-9d82a4bfad91.png)

**Comment by rishiraj824** [comment]
@mariobehling on it :+1:

**Comment by rishiraj824** [comment]
@mariobehling I checked with [Google speech to text API](https://cloud.google.com/speech/pricing), which is only free for the first 60minutes. After that limit, one starts getting charged. One can use [IBM Watson speech](https://github.com/watson-developer-cloud/speech-javascript-sdk) to text API for this feature. Please let me know if you have anything else in mind.

**Comment by madhavrathi** [comment]
@rishiraj824 IBM Watson speech to text seems appropriate choice for this. I am also trying to achieve this feature. Since you're already on it, please let me know if you need any help in testing or code.
