### ISSUE TITLE
Develop a skill where SUSI showcases her skills

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#280]
What skills does SUSI.AI have? Please showcase SUSI skills.

**Comment by rishiraj824** [comment]
@mariobehling This needs an API endpoint implementation I think which shall give us all the list of skills. 
Few more ideas to follow up on this-
- Should it be on a separate page? This way we can accommodate all the skills, maybe have a pagination and a search feature on the skills too.
- Once a skill is viewed we should also be able to give the user suggestions on what sample queries he can perform to get certain responses.

**Comment by uday96** [comment]
Yes, we could have an option like demo in the app bar drop down and clicking that we can redirect to a separate page where we can have a sidebar with different sample queries clicking on which the particular query would be sent and the response is rendered. With something like this, we can either hardcode it in the client with the tutorial as a reference or we could have an endpoint in the server to get the list of all sample queries. 
But how do we handle side bar in mobile screens? 

I would like to work on this :+1:

**Comment by rishiraj824** [comment]
@uday96 Let's divide this into sub-issues as it requires lots of implementation starting from 
- Creating a static landing page first (Instead of a sidebar lets have an Alexa type landing page https://www.amazon.com/b?node=13727921011)
- Showing skills dynamically as soon as we have an endpoint from the server
- Showing Query Suggestions based on the skills selected
- Having the option to search the skills as well

@mariobehling @madhavrathi @isuruAb  Please suggest and give your feedback

**Comment by uday96** [comment]
@rishiraj824 Sure, we can create sub issues for this.
We already have an endpoint for fetching sample queries : http://api.susi.ai/cms/getExampleList.json
And also categorised queries for ex: http://api.susi.ai/cms/getExampleList.json?model=general

But we must confirm it once as to do we proceed on this or not as @mariobehling had quoted ` In this case I think the wiki is probably the best location to give an overview of the skills and if people want they can edit it here as well.` regarding this discussion in gitter channel

**Comment by rishiraj824** [comment]
@uday96 Should we create sub-issues for this?

**Comment by uday96** [comment]
@rishiraj824 Let us confirm with @mariobehling before proceeding.
