### ISSUE TITLE
custom theme colour changes after message sent

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#283]
**Actual Behaviour**

Custom theme colour changes after a message sent

**Expected Behaviour**

custom theme colours should not be changed while chatting and it should be stored as a state.

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.
![ezgif-2-b53f737ebf](https://user-images.githubusercontent.com/7692626/27313744-39433226-558d-11e7-9610-9a0812f08672.gif)

**Would you like to work on the issue?**
yes

**Comment by mariobehling** [comment]
I don't understand the issue exactly. The message changes randomly suddenly when an unrelated message appears or how?

**Comment by mariobehling** [comment]
Actually if custom themes stay, they should be implemented as a skill in the server as well. Imagine you say "use the dark theme" and the theme changes. This setting should be stored on the server. So, working on this issue should be related following this.
