### ISSUE TITLE
Map answer in three bubbles instead of one

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#284]
The map answer is coming up in three bubbles instead of one. 
![screenshot from 2017-06-18 10-58-58](https://user-images.githubusercontent.com/1583873/27259535-81e36c2c-5415-11e7-9be3-fb5d04d98ea4.png)

**Comment by uday96** [comment]
We are generating this based on the response from the server. The server is asking the client to generate three bubbles. 

"actions":[{"type":"answer","expression":"City of London is a place with a population of 7556900. Here is a map: https://www.openstreetmap.org/#map=13/51.51279067225417/-0.09184009399817228"},{"type":"anchor","link":"https://www.openstreetmap.org/#map=13/51.51279067225417/-0.09184009399817228","text":"Link to Openstreetmap: City of London"},{"type":"map","latitude":"51.51279067225417","longitude":"-0.09184009399817228","zoom":"13"}]

First an answer, then an anchor and finally a map. 

Generating based on https://github.com/fossasia/chat.susi.ai/issues/151

**Comment by tabesin** [comment]
The server hands over a structure with answer, anchor and map that needs to be rendered as a whole. In fact, not necessarily everything needs to get rendered. So the task is to build a renderer for such an object.

**Comment by uday96** [comment]
@rishiraj824 This can be closed now. Implemented in https://github.com/fossasia/chat.susi.ai/pull/561

**Comment by rishiraj824** [comment]
closing via #561
