### ISSUE TITLE
Improve and fix top bar related to search box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#285]
The top bar changes height when the search field is activated.

Please also implement an expansion of the search box to the left and when it is expanded move "SUSI" to the left. 

Similar to this effect here: https://www.w3schools.com/howto/howto_css_animated_search.asp
![screenshot from 2017-06-18 13-50-21](https://user-images.githubusercontent.com/1583873/27260505-ea83dbb4-542d-11e7-9129-6c862f33f1da.png)

**Comment by uday96** [comment]
Will work on it :+1:

**Comment by rishiraj824** [comment]
@uday96 Are you working on this currently?

**Comment by isuruAb** [comment]
working on it

**Comment by uday96** [comment]
@mariobehling the top bar height issue fixed. For the search field animation, Its a nice idea but, even if we animate and expand the search field, we cant show both SUSI logo and search field on mobile screens and on desktop screen, theres lot of space so theres no need to move the susi logo along with animation.
So we could include the animation for the search field, but we will have to remove the SUSI logo in mobile screens. Should I proceed this way?

**Comment by mariobehling** [comment]
> we cant show both SUSI logo and search field on mobile screens
 
It does not matter. In this case let's logo disappear and see how this works a bit.

**Comment by uday96** [comment]
Okay, on it :+1:
