### ISSUE TITLE
Add functionality to Susi Hardware connect UI

### ISSUE THREAD

**Issue by betterclever** [fossasia/chat.susi.ai#289]
**Actual Behaviour**

UI for Susi Hardware connect has been made. Addition of functionality is still pending.

**Expected Behaviour**

Functionality is needed to be added to facilitate connection.

**Steps to reproduce it**

N/A

**LogCat for the issue**

N/A
**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes. I have started working on this already. Please assign me. :smile:

**Comment by rishiraj824** [comment]
closing via #298
