### ISSUE TITLE
Option to choose server in Chat Anonymously mode

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#293]
**Actual Behaviour**

When the user is in `Chat Anonymously mode` , he can only use standard server i.e `api.susi.ai`

**Expected Behaviour**

User must have an option to choose server in Chat Anonymously mode too

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Actually, I think we need to think this through more. Let's think about what use cases we actually want to support. Right now this is not a top priority I would say. The difference to the Android phone installation of SUSI is, that the web UI actually runs on the server of someone. So maybe only the admin of the SUSI.AI chat instance should be allowed to switch?

**Comment by uday96** [comment]
@mariobehling Just to be clear, this feature is same as android i.e every user can change server for him only. Like if I want to test my own SUSI deployment on Google cloud platform, I can use front end of chat.susi.ai and backend of my own deployment rather than api.susi.ai. We currently have this option in logged in mode where the user is asked for a server url when he is logging in. But the user doesnt have this option in chat anonymously mode. So this issue talks about implementing that option in chat anonymously mode too.

I am not talking about changing backend server of chat.susi.ai for all users. So this has nothing do with admin right?

**Comment by rishiraj824** [comment]
@uday96 Should this be closed?

**Comment by uday96** [comment]
Its not a priority now, but we already have the option without the functionality in the UI. So if we are gonna close this, we have to remove the UI too. Should I remove the UI?

**Comment by rishiraj824** [comment]
@uday96 Let the UI and the issue be there. We can come back to this later.

**Comment by mariobehling** [comment]
It is probably out of scope for the time being. Therefore closing it.
