### ISSUE TITLE
Prompt Logout for the setting to choose default server in logged in mode

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#294]
**Actual Behaviour**

We have a setting to choose default server when the user is logged in.
But we have no use for the default server setting as we get the server the user wants to use when he is logging in

**Expected Behaviour**

Remove the settings option to choose default server

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi Is the default server setting really redundant or does it have any use?

**Comment by rishiraj824** [comment]
@uday96 one can change the default server even after he is logged in. so it's not redundant i guess.

**Comment by uday96** [comment]
@rishiraj824 Oh!, Thanks for pointing out. So changing it to choose server then. This can then be used in `Chat anonymously mode` too. :+1:

**Comment by uday96** [comment]
Closing this as the option isnt really redundant and only needs a little modification which will be implemented as a part of https://github.com/fossasia/chat.susi.ai/issues/293

**Comment by uday96** [comment]
@chiragw15 So since the user must be logged out to use new server, he must not be given an option to choose server in the settings right? So we must remove the choose server option in logged in mode from settings right?

**Comment by rishiraj824** [comment]
Yes, it should only be there as an option when logged in. @uday96

**Comment by uday96** [comment]
And in Chat Anonymously mode, option to choose server will be present in settings and the page will reload after choosing different server so that only relevant chat history is shown. @rishiraj824 Thats it na?

**Comment by rishiraj824** [comment]
Yes on point :+1:

**Comment by chiragw15** [comment]
Its optional. In android app, there is an option in settings which says "Select backend server for app" . When user clicks on it, a dialog box is displayed saying "Please login again to change susi server" with two buttons "yes" or "no" . If user clicks "yes" he is logged out and taken to login screen where he can change the server.

**Comment by uday96** [comment]
@chiragw15 Okay, Thanks that seems more elegant. So will add the same functionality in logged in mode in this issue and the option to choose server in chat anonymously mode will be handled in https://github.com/fossasia/chat.susi.ai/issues/293 .
