### ISSUE TITLE
Remove Change Theme as an drop down option and include in settings

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#295]
**Actual Behaviour**

Change Theme option is a drop down option as of now. And the settings include default theme option. 
The default theme option in the settings was originally idealised as the default theme to render when the user logs in irrespective of the theme when the user previously logged out.

**Expected Behaviour**

We must save the theme in userpreferences store i.e a part of user data which is intended to push and pull from server (once server side support is implemented) everytime user changes theme so that when he logs in, the same theme is rendered which was used when he previously logged out.

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi Please confirm so that i can proceed with this

**Comment by madhavrathi** [comment]
@uday96 this seems more appropriate, please confirm from other developers also .

**Comment by rishiraj824** [comment]
@rishiraj824 yes this option is redundant right now. should be moved to userpreferences.
