### ISSUE TITLE
Move the Angularjs app for accounting from susi server to asksusi.com

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#30]
The idea of move is to be more flexible in the development of the app and to have the app in the asksusi.com domain.

Currently the susi server keeps accounting apps. The goal is to set up a real accounting system in asksusi.com. First step is to move the apps and make them functional from the asksusi.com domain.

Links: 
Susi Accounting Apps: http://api.asksusi.com/apps/applist/index.html#AccountsAPI
Susi Server https://github.com/fossasia/susi_server

**Comment by nikhilrayaprolu** [comment]
@mariobehling so does that mean to bring the accounting related app to asksusi.com and then change the api endpoints such that they point to the server?

**Comment by mariobehling** [comment]
@nikhilrayaprolu Yes, please use the API endpoints from the server. The first step is to implement the app in asksusi.com. 

Later steps would include to implement an architecture and set up a server that takes care of the accounting features independently. But this is out of scope of this issue. For now we would like to see accounting in asksusi.com. Thank you.

**Comment by nikhilrayaprolu** [comment]
@mariobehling I am facing CORS errors while I am accessing the api. can something be done on the server side to access the api.
or is a problem from my side?

**Comment by nikhilrayaprolu** [comment]
@mariobehling 
the api documentation at api.asksusi.com doesn't have any documentation regarding some routes required for account management.
like
1) aaa/login.json
2) http://api.asksusi.com/aaa/recoverpassword.json?getParameters=true&token= (422 UNKNOWN) (no documentation regarding this call
3)http://api.asksusi.com/aaa/account-permissions.json (no documentation)
