### ISSUE TITLE
remote configuration for susi_service

### ISSUE THREAD

**Issue by chiragw15** [fossasia/chat.susi.ai#308]
Follow these 2 issues : 
1. [#155](https://github.com/fossasia/susi_android/issues/155)
2. [#156](https://github.com/fossasia/susi_android/issues/156)

What needs to be done : 
Fetch array from http://config.asksusi.com/config_susi.json . Store it. When one server times out, use other one. Like if index 0 timed out use 1, if 1 timed out then 2 and so on. If last timed out use 0.

**Comment by rishiraj824** [comment]
Would like to work on this

**Comment by uday96** [comment]
Is this for the standard server?
Further we are using api.susi.ai now and not api.asksusi.com right?

**Comment by chiragw15** [comment]
@rishiraj824 @uday96 Yes it needs to be transfered to api.susi.ai . @Orbiter said he'll do it soon. And AFAIK this is for standard server. But you may try it with every server. Like try fetching for custom server, if you succeed, then use it else use the default configuration.

**Comment by uday96** [comment]
@chiragw15 got it :+1:
