### ISSUE TITLE
Reduce width of login Dialog box of 404 page

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#318]
**Actual Behaviour**

Login form has extra left and right margins.

**Expected Behaviour**

should reduce the width of the login form

**Screenshots of the issue**

<img width="775" alt="screen shot 2017-06-23 at 9 49 12 am" src="https://user-images.githubusercontent.com/7692626/27466564-49a160d4-57f9-11e7-8817-8d13e19e42d4.png">

**Would you like to work on the issue?**

yes

**Comment by rishiraj824** [comment]
closing via #319
