### ISSUE TITLE
Remove the hyperlink styling in the websearch rss tiles

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#323]
**Actual Behaviour**

The entire text in websearch rss tiles is styled as custom anchor (highlighted and underlined)

**Expected Behaviour**

Remove the anchor styling for tile text (do not show the underline)

**Steps to reproduce it**

sample query : pirates

**Screenshots of the issue**

![hyperlink](https://user-images.githubusercontent.com/13276887/27505778-f09247ce-58c5-11e7-8491-c721f168745a.png)

**Would you like to work on the issue?**

Yes

**Comment by rishiraj824** [comment]
@uday96 Also increase the default height if possible, for accommodating text

**Comment by uday96** [comment]
@rishiraj824 Okay :+1:
