### ISSUE TITLE
Preview the link provided in rss response to show image in tiles

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#324]
**Actual Behaviour**

rss response contains only title description and link. An image url is not provided. So image is not displayed.

**Expected Behaviour**

We can use that link to preview that link and get an image for that link to display it.

iOS client is using : https://github.com/LeonardoCardoso/SwiftLinkPreview
android client is using : https://github.com/LeonardoCardoso/Android-Link-Preview

we can also find a similar library to fetch and display an image too.

**Would you like to work on the issue?**

Anyone can take this up

**Comment by rishiraj824** [comment]
I'll work on this.

**Comment by rishiraj824** [comment]
will fetch all details from https://github.com/fossasia/susi_server/pull/337 and show it as Google Assistant Tiles.
