### ISSUE TITLE
Make elements in the UI for Feedback or Rating system

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#358]
**Actual Behaviour**

The feedback or the rating system requires a like, dislike button system and a description as to why he disliked it, on responses generated by SUSI to be sent to the server endpoint. 
Server Issues here at 
https://github.com/fossasia/susi_server/issues/329
https://github.com/fossasia/susi_server/issues/328
https://github.com/fossasia/susi_server/issues/333

This is a sub-issue for https://github.com/fossasia/chat.susi.ai/issues/247

**Expected Behaviour**

This needs proper implementation as one cannot have likes and dislikes on every response. So one way of implementing it would be to have a `boolean` value received from the server on every skill object for a particular user, to know whether the user has already given the rating to that skill.
One can have reactions like in Facebook messenger for like and dislike like the following image
https://cdn.macrumors.com/article-new/2017/03/facebookmessengerreactions-800x573.jpg
@saurabhjn76 @DravitLochan @dynamitechetan Please follow up and suggest other ways of implementation.

**Would you like to work on the issue?**
Yes

**Comment by dynamitechetan** [comment]
This could be the best way to implement feedback system in my opinion.
https://cdn.macrumors.com/article-new/2017/03/facebookmessengerreactions-800x573.jpg

**Comment by madhavrathi** [comment]
@rishiraj824 How about displaying two buttons on hover of response message?
For now, we can go with simply right and wrong button. shall I work on making this UI ?
