### ISSUE TITLE
Header not fixed while typing on phones.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#360]
**Actual Behaviour**

When using the keyboard from phone the header is not fixed.

**Expected Behaviour**

One should keep the header fixed while typing.

**Screenshots of the issue**

![unnamed](https://user-images.githubusercontent.com/11540785/27724190-5e509d0c-5d8e-11e7-99a5-2ac96c31dc40.jpg)

**Would you like to work on the issue?**

Anyone can take it up.

**Comment by isuruAb** [comment]
i will do this

**Comment by rishiraj824** [comment]
closing as low priority
