### ISSUE TITLE
Remove warnings from SearchField

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#374]
**Actual Behaviour**

There is a warning of changing uncontrolled input in searchfield

**Expected Behaviour**

This warning is occuring as we are passing value=' '(NULL) in Textfield. This should be reomved.

**Screenshots of the issue**

![issuenew](https://user-images.githubusercontent.com/22375731/27801917-450eb010-603e-11e7-9ce9-ea54fb4fc4de.png)

**Would you like to work on the issue?**

Yes.

**Comment by rishiraj824** [comment]
closing as fixed via https://github.com/fossasia/chat.susi.ai/pull/375
