### ISSUE TITLE
Forgot password doesnt work from the signup->login dialog

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#378]
**Actual Behaviour**

When we select login option from signup dialog, then forgotpassword option doesnt work

**Expected Behaviour**

Forgot password option must open the forgot password dialog

**Steps to reproduce it**

1. Select SignUp
2. Select Login from the SignUp dialog
3. Select Forgot password from the displayed login dialog

**Comment by madhavrathi** [comment]
@uday96 Will do it

**Comment by uday96** [comment]
@madhavrathi Sure. Just confirm it with @rishiraj824 if this will be solved under https://github.com/fossasia/chat.susi.ai/issues/367 or seperately :+1:

**Comment by madhavrathi** [comment]
@uday96 Now this is working. @rishiraj824 Please close this issue
Thanks

**Comment by rishiraj824** [comment]
Sure @madhavrathi
