### ISSUE TITLE
Forget password button not working

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/chat.susi.ai#379]
**Actual Behaviour**
When clicked on forget password button, Nothing happens.

**Expected Behaviour**
An event should be fired calling '/forgotpwd' route.

**LogCat for the issue**
`﻿
Login.react.js:188 Uncaught TypeError: n.props.showForgotPassword is not a function
    at n.showForgotPassword (Login.react.js:188)
    at Object.o (ReactErrorUtils.js:26)
    at a (EventPluginUtils.js:85)
    at Object.s [as executeDispatchesInOrder] (EventPluginUtils.js:108)
    at p (EventPluginHub.js:43)
    at m (EventPluginHub.js:54)
    at Array.forEach (<anonymous>)
    at n (forEachAccumulated.js:24)
    at Object.processEventQueue (EventPluginHub.js:254)
    at o (ReactEventEmitterMixin.js:17)
n.showForgotPassword	@	Login.react.js:188
o	@	ReactErrorUtils.js:26
a	@	EventPluginUtils.js:85
s	@	EventPluginUtils.js:108
p	@	EventPluginHub.js:43
m	@	EventPluginHub.js:54
n	@	forEachAccumulated.js:24
processEventQueue	@	EventPluginHub.js:254
o	@	ReactEventEmitterMixin.js:17
handleTopLevel	@	ReactEventEmitterMixin.js:27
i	@	ReactEventListener.js:72
perform	@	Transaction.js:143
batchedUpdates	@	ReactDefaultBatchingStrategy.js:62
i	@	ReactUpdates.js:97
dispatchEvent	@	ReactEventListener.js:147
`
**Would you like to work on the issue?**
No

**Comment by madhavrathi** [comment]
Will do it

**Comment by uday96** [comment]
Hey, I already fixed this in https://github.com/fossasia/chat.susi.ai/pull/377 and created another issue for forgot pass word not working from signup->login dialog.

**Comment by rishiraj824** [comment]
closing as fixed in #377
