### ISSUE TITLE
Propose a way to show the SUSI skills on first appearance

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#383]
**Actual Behaviour**

There is no introductory message or process to show SUSI Skills or actions when one first opens the Website or logs in as mentioned by @chiragw15 in https://github.com/fossasia/susi_android/issues/785.

**Expected Behaviour**

Have an introductory pane or showcase skills like Cortana to show what important actions or skills SUSI has. One needs to also keep in mind that this appears only once, i.e. only the first time the User open's the site or logins.

One can also have this as an option somewhere in the Chat App to see the skills or actions when he wants. But showing this at the first appearance should be mandatory.

**Comment by madhavrathi** [comment]
Will try this. I will propose an initial UI and let's see what other's think of it.

**Comment by uday96** [comment]
@rishiraj824 @madhavrathi I think we need to first confirm with @mariobehling regarding this.

**Comment by madhavrathi** [comment]
@mariobehling What are your thoughts on this. Please comment

**Comment by mariobehling** [comment]
Implement this as a skill!

https://github.com/fossasia/chat.susi.ai/pull/453#issuecomment-314682006
