### ISSUE TITLE
Add settings for Speech

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#400]
**Actual Behaviour**

No settings are present for enabling or disabling mic input and other speech settings

**Expected Behaviour**

Add settings for
1. Mic Input
2. Speech Output
3. Speech Output always ON

As speech features keep getting added

**Screenshots of the issue**

![speech settings](https://user-images.githubusercontent.com/13276887/27897064-985877a2-623b-11e7-914e-5fcee3975636.png)

**Would you like to work on the issue?**

Yes

**Comment by isuruAb** [comment]
@mariobehling  this issue should be closed

**Comment by rishiraj824** [comment]
implemented via #477 #434 #430 #426
