### ISSUE TITLE
Implement a Speak Now view for Speech to Text

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#401]
**Actual Behaviour**

Currently, the text is being sent on its own.

**Expected Behaviour**

Have a speak now view to and then send the text following the Google Search process.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
The first implementation is a start, but it does not fully implement the process as expected. Please do the following:
* Adapt the same colors and functionality as the Google search speech input and output
* Add a gray circle indicating voice input is active. Show it moving according to the input voice.
* Voice output of SUSI is currently not working. Ensure it is working
* Stop voice input after action is performed (same as Google)

**Comment by rishiraj824** [comment]
Alright will work on it!
