### ISSUE TITLE
Implement a Service Worker to intercept the Sent Messages

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#404]
**Actual Behaviour**

Currently, the messages are being rejected when there is no Internet Connection. The aim is to make the web app work even in offline mode. 

**Expected Behaviour**

Propose a service worker to intercept Sent messages and place the message details into the IndexedDB, i.e. the Browser Database. The implementation should be such that the queries are synced and the responses are rendered at their positions when the connectivity is back. To follow up on this, various helping links are
- https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app
- https://www.twilio.com/blog/2017/02/send-messages-when-youre-back-online-with-service-workers-and-background-sync.html

Please provide your inputs  @mariobehling @uday96 @isuruAb @madhavrathi 

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
@rishiraj824 The link - https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app says :
>Service workers require HTTPS, although to facilitate local testing, that policy does not apply to localhost. If your production web server does not support HTTPS, then the service worker registration will fail, but the rest of your web app will remain functional.

We dont have HTTPS na? Is that a problem?

**Comment by rishiraj824** [comment]
@uday96 Yes we need a HTTPS domain for implementing this.

**Comment by rishiraj824** [comment]
closing as HTTPS is required
