### ISSUE TITLE
Change background for message section

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#412]
**Actual Behaviour**

Change background for background is already being implemented. 

**Expected Behaviour**

We should have an option to change background of message section as well

**Would you like to work on the issue?**

Yes

**Comment by rishiraj824** [comment]
@madhavrathi @isuruAb I think it should actually be implemented for the Message Section only and not for the whole body. What do you suggest?

**Comment by madhavrathi** [comment]
@rishiraj824 For Web user can choose background for whole body as well, for mobile only message section. I guess there is no harm in having both features.

**Comment by rishiraj824** [comment]
@madhavrathi Okay, let's try that out then. No harm in trying it out. I think the wallapaper functionality is also there in other clients, if I am not wrong?

**Comment by rishiraj824** [comment]
closing via #415
