### ISSUE TITLE
SUSI message composer text area is appearing small

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#414]
**Actual Behaviour**

Size of message composer is smaller than usual

**Expected Behaviour**

It should be brought back to normal

**Screenshots of the issue**

![susinewis](https://user-images.githubusercontent.com/22375731/27975035-2f122056-637e-11e7-9a77-a52df546d3b3.png)

**Would you like to work on the issue?**
Yes

**Comment by rishiraj824** [comment]
closing via #424
