### ISSUE TITLE
Use the memory servlet to fetch history upon scroll

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#421]
**Actual Behaviour**

We arent displaying the entire chat history.

**Expected Behaviour**

When the user scrolls up and reaches top limit of scrollbar, call the memory servlet again and load few more history messages similar to other chat apps using https://github.com/fossasia/susi_server/pull/323

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
This issue seems to be open but again @rishiraj824 was unassigned from this, has this feature been implemented already or may I consider working on this?

**Comment by AakashMallik** [comment]
If this fix went stale then let me know coz I would like to work on this issue.

**Comment by AakashMallik** [comment]
@rishiraj824 Yes, I will do a few experiments using the history API and see if we can make this enhancement efficiently. I'll let you know in a day or two.

**Comment by AakashMallik** [comment]
@rishiraj824 @Akshat-Jain So I was just going through the whole implementation and I also looked for the issue tracker in SUSI_server. So the thing is the backend ends up sending only 10 cognitions which is undesirable even from their point of view as mentioned in this [issue](https://github.com/fossasia/susi_server/issues/409). I have gone through the code so I won't have any trouble making the changes in the frontend here. So how do we wish to proceed?

**Comment by rishiraj824** [comment]
@AakashMallik Lets look at what can be done from the server side and then come back to the implementation here. It's of no use if we take a stab at it without the history being consistent.

**Comment by AakashMallik** [comment]
@rishiraj824 Agreed... Let me see if I can stir things up on the backend regarding this.
