### ISSUE TITLE
Enhance voice UI and functionality and enable the voice output

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#428]
Currently the "Speak Now" overlay is covering parts of the page. 

1. Please go to a Google's result page and check the functionality of "Speak Now" here and replicate it including following the color style. There is a top bar with the "Speak Now" functionality and the rest of the page has an semi-transparent white overlay.
![screenshot from 2017-07-09 11-18-13](https://user-images.githubusercontent.com/1583873/27992593-b0bde1ec-6498-11e7-9d37-63e37543148b.png)

2. Implement the voice output in Chrome as in Google.

**Comment by rishiraj824** [comment]
@mariobehling Okay, I'll work on this.
