### ISSUE TITLE
Avoid horizontal scroll bars on small mobile screens and ensure line breaks

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#429]
On small mobile screens there are sometimes horizontal scrollbars and long links and other items are extending over the bubble area.

Please ensure there are no horizontal scrollbars and enforce line breaks if the bubble is too small.

![screenshot_2017-07-09-13-16-07](https://user-images.githubusercontent.com/1583873/27993356-daad1e6c-64a9-11e7-8d91-b5e8ed1a0c07.png)

![screenshot_2017-07-09-13-18-15](https://user-images.githubusercontent.com/1583873/27993357-e1de904e-64a9-11e7-8948-4442cff0b679.png)

**Comment by isuruAb** [comment]
i will work on this
