### ISSUE TITLE
No mobile optimizes

### ISSUE THREAD

**Issue by Ch-Developer** [fossasia/chat.susi.ai#45]
I actually want to look at the website on my mobile phone than I see that there is no mobile optimize.
I know some people maybe think that isn´t important but I think for an mobile app we should also make an mobile version or?

**Comment by Ch-Developer** [comment]
Aso I mean a better optimize version because when I open it on my phone not much change it.
For example I made my website (appmaker.000webhostapp.com) with the material design so it will transform it automaticlly to an mobile version....wouldn´t it better with such a optimize?

**Comment by mariobehling** [comment]
Yes, please help to optimize the site.

**Comment by BrainBuzzer** [comment]
In your website you are using material design lite. Can you please try to do same with semantic ui instead of using material design on the pages. There is a sidebar module available in semantic ui so maybe use it with this?
