### ISSUE TITLE
Create an overview page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#456]
Currently we don't have a good overview page. Please create one following https://assistant.google.com 

Intended domain: chat.susi.ai/overview

**Comment by rishiraj824** [comment]
Will create one. Can we follow the details in http://susi.ai ? We do need to add more details to it of course.

**Comment by mariobehling** [comment]
@rishiraj824 Please follow the details of the Google Assistant page and use material ui as the chat part. The current home page is lacking relevance.

**Comment by rishiraj824** [comment]
Okay. I'll choose a material theme for displaying the details.
