### ISSUE TITLE
Make menu dropdown into a - real dropdown

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#457]
The drop-down menu is not dropping down. It is overlapping. Please also avoid that it attaches completely to the edge of the screen.
![screenshot from 2017-07-12 09-30-30](https://user-images.githubusercontent.com/1583873/28106642-ec12419a-66e4-11e7-8972-b37da5f6d753.png)

**Comment by uday96** [comment]
Will work on this :+1:
