### ISSUE TITLE
Lighten up the standard design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#458]
Google Assistant has a much lighter design. Please implement a lighter and "more friendly" colors closer to the Google design.

**Comment by isuruAb** [comment]
will work on this

**Comment by isuruAb** [comment]
@mariobehling  do we need an icon before SUSI's reply like Google assistant ?
<img width="60" alt="screen shot 2017-07-17 at 11 06 13 pm" src="https://user-images.githubusercontent.com/7692626/28281472-d954fc46-6b44-11e7-9ea3-01e9154312ce.png">
