### ISSUE TITLE
Adding Google Play Button

### ISSUE THREAD

**Issue by pipix51** [fossasia/chat.susi.ai#46]
Could I add the Google Play button ("Get It On Google Play") to allow users to know where to download the Ask Susi application? Currently the only way to download the mobile application is to navigate down towards the footer and clicking on the GooglePlay button, which may go unnoticed for some users.

**Comment by BrainBuzzer** [comment]
I don't think so that we are allowed to that until we have application really on Google Play. 
The download button still appears on the homepage and it is a primary button. Please close this issue.

![](http://i.imgur.com/pHpSqim.png)

**Comment by BrainBuzzer** [comment]
Sorry for the last comment. I did not see it was there on PlayStore. Sorry.

**Comment by BrainBuzzer** [comment]
Just be sure that it doesn't conflict with any other UI elements.

**Comment by daminisatya** [comment]
@pipix51 Looks like a good idea. Put also attach a screenshot for the same.

**Comment by jig08** [comment]
@pipix51 Pls do the required. Thanks !
