### ISSUE TITLE
Improve login popup

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#460]
Improve the popup login as follows:

* Speed up effect where popup slides in from top as much as possible
* Avoid internal scrollbar
* Take out "Standard Server" and only keep custom server. Make the custom server button into a button that can be activate or deactivated. When it is activated it should show URL field in the place of the the text "Custom Server"
* Design the area more space savy similar to the Facebook login
![screenshot from 2017-07-12 09-47-52](https://user-images.githubusercontent.com/1583873/28107349-ba770b18-66e7-11e7-8189-e2a0b99a986f.png)

**Comment by rishiraj824** [comment]
Will do this 👍
