### ISSUE TITLE
Improve Settings Popup

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#461]
Please improve the settings popup as follows

* Speed up effect where popup slides in from top as much as possible
* Avoid internal scroll bars
* Take out "Standard Server" and only keep custom server. Make the custom server button into a button that can be activate or deactivated. When it is activated it should show URL field in the place of the the text "Custom Server"
* Align all text to the left
* Make "Add Address to Connect to Hardware" into a - button - "Connect to Hardware"
* Make Save and Cancel button in one line together at the end of the page

![screenshot from 2017-07-12 09-58-08](https://user-images.githubusercontent.com/1583873/28107612-c75cfdaa-66e8-11e7-8718-ec87ac1d8a97.png)

**Comment by uday96** [comment]
Will work on this :+1:

**Comment by rishiraj824** [comment]
closing this as it's now it's been shifted to route `/settings`.
