### ISSUE TITLE
Improve Sign up Popup

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#462]
Improve as follows:

* Speed up effect where popup slides in from top as much as possible
* Avoid internal scrollbar
* Take out "Standard Server" and only keep custom server. Make the custom server button into a button that can be activate or deactivated. When it is activated it should show URL field in the place of the the text "Custom Server"
* Design the area more space savy similar to the Facebook login

**Comment by isuruAb** [comment]
Will work on this

**Comment by isuruAb** [comment]
@uday96  @rishiraj824  @madhavrathi  guys please give your suggestions to Avoid internal scrollbars 
 I'm hoping to take the signup page to another new route like /signup then we can build a seperate view for signup.

**Comment by madhavrathi** [comment]
@isuruAb this is a good option. Please confirm with @mariobehling before proceeding.
