### ISSUE TITLE
there is no way to disable Feedback feature

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#463]
**Actual Behaviour**

there is no way to disable Feedback system .

**Expected Behaviour**

There should be an option in settings page to disable feedback feature.

**Would you like to work on the issue?**

yes

**Comment by rishiraj824** [comment]
@isuruAb The feedback feature is to be linked with the API endpoint. https://github.com/fossasia/susi_server/pull/364

**Comment by mariobehling** [comment]
You are proposing a bug instead of a feature. We don't need that and we should not have that.
