### ISSUE TITLE
Create a new component for custom server

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#475]
**Actual Behaviour**

As of now we are using radio buttons to choose between standard and custom server.
The same is used in login, signup, forgot password and settings. So its better to have a seperate component for the same

**Expected Behaviour**

Take out "Standard Server" and only keep custom server. Make the custom server button into a button that can be activate or deactivated. When it is activated it should show URL field in the place of the the text "Custom Server"

**Would you like to work on the issue?**

Anyone can take this up

**Comment by rishiraj824** [comment]
Will do this. :+1:

**Comment by uday96** [comment]
@rishiraj824 Are you working on this?

**Comment by rishiraj824** [comment]
Not as of now. @uday96 you can work on this

**Comment by uday96** [comment]
Cool, Will do this. Thanks :+1:
