### ISSUE TITLE
Add settings for adjusting speech rate and pitch

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#477]
This is a sub issue of https://github.com/fossasia/chat.susi.ai/issues/400

**Actual Behaviour**

No settings to choose the speech 
 - rate
 - pitch
 - language

**Expected Behaviour**

Add settings to choose rate, pitch and have an option to listen to example speech output with the chosen settings similar to other clients

**Screenshots of the issue**

![speechlang](https://user-images.githubusercontent.com/13276887/28184767-4eed0e46-6832-11e7-8a08-5d74df00d5fc.png)

**Would you like to work on the issue?**

@rishiraj824 Please suggest how to proceed and on this and if possible lets split this to different issues

**Comment by rishiraj824** [comment]
We can do this by passing props to the file `VoicePlayer.js` and modifying the defaults defined there
```const defaults = {
      text: '',
      volume: 1,
      rate: 1,
      pitch: 1,
      lang: 'en-US'
    }```
