### ISSUE TITLE
The table type output doesn't show "number" type of outputs.

### ISSUE THREAD

**Issue by Manveer695** [fossasia/chat.susi.ai#482]
Please refer to this [issue #212](https://github.com/fossasia/susi_skill_data/issues/212) and the discussion below.

**Would you like to work on the issue?**
@rishiraj824 @isuruAb Please look into the issue.

**Comment by uday96** [comment]
@Manveer695 Can you give a sample query. The queries provided in https://github.com/fossasia/susi_skill_data/issues/212 aint giving table type responses

**Comment by rishiraj824** [comment]
@Manveer695 Yes please send a sample query I am not able to produce the table.

**Comment by Manveer695** [comment]
@uday96 @rishiraj824 You need to type these 2 queries in susi web chat:
1. dream infomovies
2. info about transformers movies

**Comment by uday96** [comment]
Fixing it :+1:
