### ISSUE TITLE
Change password should not work for same password as previous one

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#486]
**Actual Behaviour**

Right now user can change his password to current password.

**Expected Behaviour**

We should avoid this behavior and prompt the user that enter a different password

**Steps to reproduce it**

check the current password and new password before making request to server.

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
How do we get the current password of the user to compare with the new password being entered?

**Comment by madhavrathi** [comment]
@uday96 I am still figuring out a way to do this. Will update once i figure it out.
Please mention if you have some method in mind
Thanks

**Comment by uday96** [comment]
@rishiraj824 @isuruAb Please provide your inputs too

**Comment by madhavrathi** [comment]
What if we compare the values of current password field and new password field. We just need to prompt that these two should not be same and these values can be accesed.
What do you say @uday96  ?

**Comment by madhavrathi** [comment]
@uday96 I have completed it. Need merging of PR https://github.com/fossasia/chat.susi.ai/pull/474
I will send PR after this has been merged. @mariobehling Please merge the mentioned PR as it is approved now.
Thanks
