### ISSUE TITLE
Use color #4285f4 for top bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#500]
Please change the top bar color to #4285f4

**Comment by uday96** [comment]
Will do this :+1:

**Comment by uday96** [comment]
@mariobehling after changing the color of topbar, it looks like this : 

![top](https://user-images.githubusercontent.com/13276887/28267955-02256bd6-6b1a-11e7-9ff0-4a94abca881c.png)

Is this fine or should we wait till https://github.com/fossasia/chat.susi.ai/issues/458 has been implemented?

**Comment by isuruAb** [comment]
@uday96  i'm not going to change the colour of top-bar in #458  so you can change the colour.

**Comment by tabesin** [comment]
The colour is also know by web designers as "Royal Blue", you may want to add this as a css comment.

Could you sent a PR, so we can swiftly close this item?

**Comment by uday96** [comment]
@tabesin This has already been implemented. The color being used is #0084ff . Should I change it to #4285f4 if not this issue can be close

**Comment by tabesin** [comment]
I'd say move forward. Should also comprise adapting the documentation on https://github.com/fossasia/chat.susi.ai

**Comment by uday96** [comment]
@tabesin Sorry for confusion. Move forward as in change it to #4285f4 ?

**Comment by tabesin** [comment]
Yes.

**Comment by uday96** [comment]
Sending a PR rn :+1:
