### ISSUE TITLE
Update the SUSI svg with the new one

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#505]
**Actual Behaviour**

Recently orbitter suggested a new svg for SUSI. The link is here : https://github.com/fossasia/susi_artwork/blob/master/logo/svg/SUSI.AI_Letters_Blue_Large.svg

**Expected Behaviour**

We should update our svg file with new one

**Would you like to work on the issue?**
@uday96 @rishiraj824 @isuruAb @mariobehling Please give your reviews whether this should be done or not. If yes, then i would like to solve this issue

**Comment by rishiraj824** [comment]
@madhavrathi I am not sure please confirm with @mariobehling once.
