### ISSUE TITLE
Propose and implement a team page with images of participating developers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#513]
We need a team page for the complete SUSI.AI developer team. Please propose a design and implement it. Add a link on the top left of the Overview page menu bar similar to below. The "Team" link should go on the right of "Overview" in the SUSI.AI site.

![screenshot from 2017-07-17 20-20-01](https://user-images.githubusercontent.com/1583873/28283207-56ca45d6-6b2d-11e7-87f1-2391d143c7be.png)

**Comment by rishiraj824** [comment]
Would like to work on this :+1:
