### ISSUE TITLE
Improve overview page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#514]
* [ ] Move SUSI.AI logo to the top left on Overview page and add menu items "Overview", "Docs", "Blog", "Team" (Don't do this on the chat service top bar though.)
* [ ] Scroll over on "Watch" does not indicate it is a link
* [ ] Check the functionality of the **Top Bar** of the Google assistant landing page again. Scroll up and down. Stop somewhere and scroll up or down again. Also check the behavior when you start to scroll. Configure the SUSI top bar to work similarly.
* [ ] Check the bottom bar links: e.g. there is not underline and the color changes on scroll over.
* [ ] Ensure more white space above bottom bar (and below the security bar! - in between. Compare to Google!)
![screenshot from 2017-07-18 00-33-25](https://user-images.githubusercontent.com/1583873/28292752-d1a51902-6b50-11e7-917b-fa26f6fc1858.png)
* [ ] Increase the size of the bottom bar to match Google
* [ ] In section "For all Devices": Increase the space below the text (and in front of the buttons) and rename section to "For your Smartphone"
* [ ] Add logo of Open Source Initiative in the section "SUSI is Open Source" and the Github (word logo with link to https://github.com/fossasia?utf8=✓&q=susi)
* [ ] Add an area with three columns similar to api.ai. The sections should be
   * On many Platforms (convert the area - "Integrate SUSI with your favorite chat services and social networks."  - to this section)
   * For all Devices
   * Use it in many Languages

![screenshot from 2017-07-18 00-52-41](https://user-images.githubusercontent.com/1583873/28293391-3e3ae602-6b54-11e7-8f4f-d2a84dd41aec.png)

**Comment by isuruAb** [comment]
i will work on this

**Comment by isuruAb** [comment]
@mariobehling  this task is not much clear. can you be specific little more.
"Add logo of Open Source Initiative in the section "SUSI is Open Source" and the Github (word logo with link to https://github.com/fossasia?utf8=✓&q=susi)"

**Comment by mariobehling** [comment]
> @mariobehling  this task is not much clear. can you be specific little more.

What is unclear?

"Add logo of Open Source Initiative in the section "SUSI is Open Source" 

Check the first result on Google for "Open Source Initiative"!

> and the Github (word logo with link to https://github.com/fossasia?utf8=✓&q=susi)"

Check the top results on image search for "Github word logo"!
https://www.google.de/search?q=github+word+logo&tbm=isch

**Comment by isuruAb** [comment]
@mariobehling  I tried to improve app-bar of the overview page but those libraries does not allow to do that kind of modification. we will have to build it manually. we can implement it on another separate issue.
