### ISSUE TITLE
Create a page "Docs" 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#515]
List the most important facts for developers on a docs page.

**Comment by madhavrathi** [comment]
Will do this

**Comment by mariobehling** [comment]
Please follow https://developers.google.com/actions/ more closely. Just create the page and add videos etc. from the students for now.

**Comment by mariobehling** [comment]
* For the stackoverflow link use: https://stackoverflow.com/questions/tagged/susi.ai
* SUSI.AI Forums: https://groups.google.com/forum/#!forum/susiai
* Instead of Contact Us -> Chat With Us and link: https://gitter.im/fossasia/susi_server

**Comment by mariobehling** [comment]
Ok, I am closing this doc. Instead of investing time on this right now, let's focus on other things.
