### ISSUE TITLE
Add a terms page 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#517]
Add a terms page at /terms.

**Comment by isuruAb** [comment]
how this need to be implemented ? 
i would like to work on this.

**Comment by uday96** [comment]
Will do this :+1: 

@mariobehling What all should be included in the terms page?

**Comment by mariobehling** [comment]
@isuruAb Before you keep us busy with explanation solve one issue at a time, please. There are examples of term pages at loklak and susper for example.
