### ISSUE TITLE
Auto Compress JS and CSS once code is pushed

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/chat.susi.ai#52]
The goal is to auto compress JS and CSS as soon as someone pushes the code. It can be achieved with the help of node and travis.

**Comment by Achint08** [comment]
@BrainBuzzer I want to work on this.

**Comment by BrainBuzzer** [comment]
Go ahead. What technology would you love to use? Gulp or webpack?

**Comment by Achint08** [comment]
@BrainBuzzer gulp
