### ISSUE TITLE
Speech to Text long text off-screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#526]
Please ensure long text is not off-screen on large resolutions as well as on mobile. Solve it and test it on different resolutions.
![screenshot from 2017-07-18 22-51-39](https://user-images.githubusercontent.com/1583873/28339345-2b37bac2-6c0c-11e7-870c-fd73adc14a7c.png)

**Comment by rishiraj824** [comment]
Okay will havea look at this :+1:

**Comment by rishiraj824** [comment]
closing via #530
