### ISSUE TITLE
Speech to text not working on Chrome browser on mobile phone

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#527]
Speech to text only covers the first word on Google Chrome on mobile.

**Comment by rishiraj824** [comment]
Yes, this is a known issue which I've been trying to solve, need to check thoroughly what is the cause.

**Comment by madhavrathi** [comment]
@rishiraj824 yes I will try to find the issue. Will update here.

**Comment by mariobehling** [comment]
@rishiraj824 This is not fixed.

**Comment by rishiraj824** [comment]
@mariobehling It's working for my Android version phone in Chrome Browser. Please tell me the details of your phone.
