### ISSUE TITLE
Using TTS mobile phones informs user about language download even though it is already installed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#528]
The tested phone uses Google Chrome and has installed the American language pack. After speaking the phone shows the message "Download high quality voice file.." even though it is already installed.

![screenshot_2017-07-18-23-06-58](https://user-images.githubusercontent.com/1583873/28340868-91381ce0-6c11-11e7-9d91-fe48cf960703.png)

![screenshot_2017-07-18-23-07-29](https://user-images.githubusercontent.com/1583873/28340863-8c4ee8b2-6c11-11e7-9be8-319f6ca013ba.png)

**Comment by rishiraj824** [comment]
Need to check which chrome version this issue is coming in.

**Comment by isuruAb** [comment]
@mariobehling  what is the chrome version  you are using ?
