### ISSUE TITLE
Blank page after login

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#531]
After login to chat, a very short time a frame is starting to get build and then a blank page shows up.

Version used: 

Chromium Version 58.0.3029.110 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)
Firefox 54.0 (64-bit)
![screenshot from 2017-07-19 09-07-39](https://user-images.githubusercontent.com/1583873/28354846-c2c894ec-6c61-11e7-82d9-c244da10ad71.png)

![screenshot from 2017-07-19 08-40-00](https://user-images.githubusercontent.com/1583873/28353903-110192ca-6c5e-11e7-8513-c1050c7cd4d1.png)

**Comment by rishiraj824** [comment]
@mariobehling is this fixed ?
