### ISSUE TITLE
Chat input field insufficient width

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/chat.susi.ai#534]
**Actual Behaviour**

The width is very less.

**Expected Behaviour**

The field should stretch to the right till the mic button.

**Screenshots of the issue**

![screen shot 2017-07-19 at 4 09 16 pm](https://user-images.githubusercontent.com/8962264/28363133-e348a19a-6c9c-11e7-95f8-47d75c9c815c.png)

Using chrome on mac

**Would you like to work on the issue?**

No.

**Comment by mariobehling** [comment]
@chashmeetsingh Which browser, which version?

**Comment by chashmeetsingh** [comment]
It's Chrome (Version 59.0.3071.115 (Official Build) (64-bit)) 
Mac OS: 10.13
