### ISSUE TITLE
Unify "map" response and use full width

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#537]
The map response is visually separated into three responses. Please unify the responses and use the whole width of the box to provide a good map view.
![screenshot from 2017-07-19 16-45-58](https://user-images.githubusercontent.com/1583873/28373205-0af7ec78-6ca2-11e7-833c-9bbce1cb19d1.png)

**Comment by uday96** [comment]
Will do this :+1:

**Comment by rishiraj824** [comment]
@uday96 How does one record the feedback of the different responses.

**Comment by uday96** [comment]
@rishiraj824 Yes, we have to change the feedback mechanism for SUSI responses where multiple chat bubbles are rendered. We have to show feedback icons only for the first or last chat bubble. Because all the bubbles correspond to the same skill so we should collect feedback only once.

**Comment by uday96** [comment]
@mariobehling Please look at https://github.com/fossasia/chat.susi.ai/issues/284#issuecomment-309318426 . We can render it as a single chat bubble but the clients were asked to loop through the actions and render them seperately. Should not follow that procedure whenever map type actions are present in the response and render it as a single whole chat bubble?

**Comment by rishiraj824** [comment]
If we are planning to have a single chat bubble then the 2nd one has to work out for that. But in that case, the other clients should also follow the same approach. @uday96
