### ISSUE TITLE
after login web client shows same previous message for two different account.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/chat.susi.ai#540]
**Actual Behaviour**

I queried some query and logout. Again logged in using different account but it shows messages from my previous account.

**Screenshots of the issue**

![screenshot from 2017-07-20 06-39-06](https://user-images.githubusercontent.com/14003244/28396071-99c44608-6d16-11e7-9623-4e56f611a881.png)

![screenshot from 2017-07-20 06-39-29](https://user-images.githubusercontent.com/14003244/28396075-a50d38da-6d16-11e7-913c-2cd12a59831a.png)

![screenshot from 2017-07-20 06-40-30](https://user-images.githubusercontent.com/14003244/28396088-b2462188-6d16-11e7-9200-e8855c23191e.png)

![screenshot from 2017-07-20 06-40-45](https://user-images.githubusercontent.com/14003244/28396092-bb323962-6d16-11e7-8533-011af5c94cf3.png)

**Comment by uday96** [comment]
@amitiwary999 Can you please send a query after logging in so that the console log prints a url with your access_token and then use that access_token in http://api.susi.ai/susi/memory.json?access_token=ACCESS_TOKEN to once check if the actual history stored in the server for both accounts is same?

**Comment by rishiraj824** [comment]
@amitiwary999 Please tell if this issue exists for you now.

**Comment by mariobehling** [comment]
Please open if it persists. It should be solved by the server.
