### ISSUE TITLE
Height of Text Field only one line max. - Change to same way as Whatsapp Web

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#550]
The height of the chat field is only one line. Whatsapp web has 5 lines and only shows a scroll bar after that if there is more text. Please follow this approach.
![screenshot from 2017-07-21 11-29-17](https://user-images.githubusercontent.com/1583873/28457914-2262481a-6e08-11e7-8924-c6c79720fb26.png)

**Comment by isuruAb** [comment]
i'll work on this

**Comment by isuruAb** [comment]
working on this
