### ISSUE TITLE
Add New responsive App Bar to support page

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#553]
**Actual Behaviour**

- App Bar of the support page is old and it doesn't contain links and logo.
- There are few style bugs in support page.

**Expected Behaviour**

New App Bar should be there in support page and appropriate links should be there.

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.
<img width="1280" alt="screen shot 2017-07-21 at 5 19 01 pm" src="https://user-images.githubusercontent.com/7692626/28462403-b9ddcb12-6e38-11e7-8dea-3253cf06c198.png">

**Would you like to work on the issue?**

yes

**Comment by uday96** [comment]
@isuruAb @rishiraj824 This can be closed now.
