### ISSUE TITLE
favicon improvement

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#554]
**Actual Behaviour**

The favicon 1) does not render transparent background and 2) is difficult to understand.

**Expected Behaviour**

ad1 Make what is white transparent. It usually depends on the file format whether it saves transparency correctly instead of saving it as "white".
ad2 Consider to make a new favicon from the SUSI "S" that is more recognisable.

The current state is not a "real" issue but still makes the web app appear pretty unfinished to professional observers.
![favic](https://user-images.githubusercontent.com/10114907/28464429-70a96248-6e25-11e7-9546-2bd59c1b4cb3.png)

**Comment by tabesin** [comment]
Favicon is found in /public/favicon.ico

**Comment by madhavrathi** [comment]
Hey, do you want to work on this issue ?

**Comment by uday96** [comment]
@rishiraj824 @tabesin This can be closed now
