### ISSUE TITLE
Error in alignment in 404 page

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/chat.susi.ai#557]
**Actual Behaviour**

The e buttons are not aligned correctly

**Expected Behaviour**

They should be in a line

**Screenshots of the issue**

![issueh](https://user-images.githubusercontent.com/22375731/28478399-d6b45520-6e75-11e7-8af1-99255681caa1.png)

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
@madhavrathi I added a line break in https://github.com/fossasia/chat.susi.ai/pull/559 . Please check the demo link http://udaytheja.surge.sh/ .They are aligned vertically in that PR.

**Comment by madhavrathi** [comment]
@uday96 We need to have them horizontally. Also the media queries in the current implementations are making the text on the button shrink. This needs to be fixed. So i will send PR asap
