### ISSUE TITLE
If the image search shows a gif, there is only a link instead of adding the image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#567]
The answer to "image of" does not show an image output when gif images are the result e.g. from giphy.

**Comment by uday96** [comment]
@mariobehling It is working.

![img](https://user-images.githubusercontent.com/13276887/28483218-c1e195f4-6e89-11e7-904c-ea01d1e159b7.png)

**Comment by rishiraj824** [comment]
This works for me as well @mariobehling

**Comment by madhavrathi** [comment]
Works for me too.

**Comment by tabesin** [comment]
Try "Image of Mario Behling" to see the issue.

**Comment by uday96** [comment]
Okay. Will try to fix this :+1:
