### ISSUE TITLE
Scroll bar shows up if text is longer than width of window instead of breaking text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#569]
The answer of a text that is using more width than the window is breaking as expected. Please also break the line of the question. Ensure there is not horizontal scroll bar.

![screenshot from 2017-07-22 01-07-56](https://user-images.githubusercontent.com/1583873/28485514-6fd415c0-6e7a-11e7-9284-169678ca75ad.png)

**Comment by uday96** [comment]
Will fix this :+1:
