### ISSUE TITLE
Improve "safe and secure" area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#570]
In the Overview page

* Take out SUSI.AI logo instead use text SUSI.AI
* Increase size of OSI logo to match Github logo
* Decrease size of Github logo
* Ensure logos are exactly in one line

![screenshot from 2017-07-22 01-14-50](https://user-images.githubusercontent.com/1583873/28485641-3463cb88-6e7b-11e7-82da-1fadc668c14a.png)

**Comment by madhavrathi** [comment]
Will fix this
