### ISSUE TITLE
Use new settings endpoint to send multiple settings to server in one call

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#573]
**Actual Behaviour**

Currently we are making a sever call for every setting changed

**Expected Behaviour**

Use https://github.com/fossasia/susi_server/pull/404 and send all settings at once to server reducing the number of server calls

**Would you like to work on the issue?**

Yes

**Comment by rishiraj824** [comment]
@uday96 Can this be closed now?
