### ISSUE TITLE
Implement set language

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#574]
@Orbiter wrote in the channel the following. Please implement as required:

> Language detection is now in place. Susi will try to answer in the language that is submitted with the language attribute in the api query. That means this value must be set properly in all clients. Can please someone take care that this works properly? you can test if the language is set correctly with the susi chat phrase „my language“.
The skill selection for given languages will not restrict to the language but it will make the given language the main ranking criteria. So if your own language is not available, it will then prefer english next. There are exceptions like: if your language is finnish, it will prefer swedish as alternative language (they ususaly speak swedish). We can make such exceptions for any language. For not it works with english.

**Comment by rishiraj824** [comment]
Will implement this. :+1:

**Comment by rishiraj824** [comment]
@orbiter currently we are sending the language as a parameter while querying to the API. The sample query goes as follows - 
```
url = http://api.susi.ai/susi/chat.json?q=Hello&language='+locale+'&access_token=ACCESS_TOKEN;
```
Here `locale` is the user's local language. Please tell, if this is the approach to be followed.

**Comment by Orbiter** [comment]
That's fine!

**Comment by rishiraj824** [comment]
Okay, thanks @Orbiter !

**Comment by rishiraj824** [comment]
closing this as already implemented in https://github.com/fossasia/chat.susi.ai/pull/140
