### ISSUE TITLE
Propose and implement internationalization support

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#575]
What options do we have for the Internationalization of the UI? Please propose and implement it. Please ensure settings are stored on the server.

**Comment by rishiraj824** [comment]
@mariobehling We are currently sending the options to store the theme whether `Dark or Light` and fetching the same from the server. What we can store is custom theme settings if that's what you are asking for here.

**Comment by rishiraj824** [comment]
I found these links for the above issue - 
- http://www.vengaglobal.com/blog/4-website-localization-challenges-user-interface/ - This talks about how we need to change the font-styles based on the language selected of the user.
- https://www.transifex.com/blog/2015/localization-friendly-ui-design-part-1/ - This tells about the various styles which need to be configured based on the different languages, eg, `word breaks, rtl, font-sizes, line-heights etc.` 
@madhavrathi @isuruAb @uday96 Please give your inputs as well.
