### ISSUE TITLE
Improve Dark Theme overview page

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#578]
**Actual Behaviour**

- The dark theme overview page is not very user.

**Expected Behaviour**

- The describing text is should be something light color which is user friendly.

**Screenshots of the issue**

![theme-dark](https://user-images.githubusercontent.com/18073126/28497546-9e530b80-6fa7-11e7-957f-a096aaa00ac5.gif)

**Would you like to work on the issue?**

Yes

**Comment by madhavrathi** [comment]
@fragm3 It's good of you to point it out. We are currently focusing on completing all the pages - overview, docs, team, etc. After that, we will do the UI fix for the dark theme. But you can proceed here.
Thanks

**Comment by rishiraj824** [comment]
@fragm3 Thanks for pointing out. The option to change themes are only for the chat view and not for the other pages. So we can remove the theme switch from Chat page to Theme Page.

**Comment by madhavrathi** [comment]
@rishiraj824 I guess you are right, the theme is for chat window only. We do not to provide theme for overview page. Please create an issue and proceed. Thanks

**Comment by fragm3** [comment]
@madhavrathi I could work and remove the dark Overview theme. Thanks!

**Comment by uday96** [comment]
@rishiraj824 This can be closed now

**Comment by rishiraj824** [comment]
fixed via #583
