### ISSUE TITLE
"I found this on the web" should not be shown

### ISSUE THREAD

**Issue by Manveer695** [fossasia/chat.susi.ai#579]
**Actual Behaviour**
With "no results found" reply, "I found this on the web" is also shown. 

**Expected Behaviour**
No need of "I found this on the web" in that case.

**Screenshots of the issue**
<img width="505" alt="noresultsfound" src="https://user-images.githubusercontent.com/20307535/28497665-46d1f2c4-6faa-11e7-880a-8aa8325341f6.PNG">

**Would you like to work on the issue?**
@uday96 @rishiraj824 Do you think the same? If yes, can you work on it. Thanks!

**Comment by uday96** [comment]
Will work on this :+1:
I think we shouldn't render I found this on the web instead because no results found seems more apt. What do you suggest?

**Comment by rishiraj824** [comment]
Yes, @uday96 even I think so. This also looks more friendly and natural as one would think a search was made whose result was `NO Result Found`

**Comment by Manveer695** [comment]
@uday96 yes no results found is enough.

**Comment by tabesin** [comment]
Technically it is more on the SUSI server / skill side. So please make sure to file an issue there.

"no results found" should never become the answer. This is not a query machine, this is more of a dialogue. Concerning "I found this on the web" we need some variations of that phrase, so it does not become always the same and most of the times it could be skipped as well. It is an ugly fallback response anyway.

**Comment by uday96** [comment]
@tabesin The query `sin0` gives a websearch action type response asking the client to search the web. When the client searches the web using duck duck go api and still doesn't find any answer we are displaying no results found. This isn't something which should be handled by the server because the entire search happens on the client side
