### ISSUE TITLE
Add New Scroll to bottom in Chat Window

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#584]
**Actual Behaviour**

Chat window does not have any way other than scrolling to top if the user wants to read previous messages.

**Expected Behaviour**

See the screen below, something like this should be added. 

<img width="619" alt="screen shot 2017-07-23 at 10 54 39 pm" src="https://user-images.githubusercontent.com/18073126/28501476-fb7dc046-6ff9-11e7-8f0c-a160de6ce607.png">

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
@fragm3 What is the status of this?
