### ISSUE TITLE
Increase the size of web search box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#585]
Please improve the results as follows
* make the search result function more similar to Google Assistant. 
* Also increase height and add images if possible.
* Use the full width for the search result output.
* Add the info about the URL of the website

**Comment by uday96** [comment]
Will work on this :+1:

**Comment by uday96** [comment]
Working on this :+1:

**Comment by isuruAb** [comment]
i will work on this.

**Comment by uday96** [comment]
@isuruAb Are you working on this?
