### ISSUE TITLE
Add a blog page showing the SUSI.AI post using the RSS feed of Wordpress

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#586]
Display the SUSI.AI blog posts on /blog. Use the FOSSASIA blog feed at blog.fossasia.org/tag/susi-ai/feed.

**Comment by fragm3** [comment]
claim

**Comment by fragm3** [comment]
Assign me on this.

**Comment by uday96** [comment]
@fragm3 What is the status of this?

**Comment by madhavrathi** [comment]
@uday96 @mariobehling It's been few days. Should I work on this issue?
@fragm3 Please reply asap.
Thanks

**Comment by mariobehling** [comment]
@madhavrathi Would be great to get something like that: https://blog.api.ai
