### ISSUE TITLE
Improve the Support page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#590]
* Add the link to "Support" on all pages
* Use the correct top bar and color
* Make the site structure closer to https://api.ai/support/
* For the stackoverflow link use: https://stackoverflow.com/questions/tagged/susi.ai
* SUSI.AI Forums: https://groups.google.com/forum/#!forum/susiai
* Instead of Contact Us -> Chat With Us and link: https://gitter.im/fossasia/susi_server
* Instead of "Recent Changes & Updates" -> Browse, Create and Edit your own Skills... Use the link to http://skills.susi.ai
* Add a section "Create a SUSI Dream" ... You can easily create a SUSI.AI dream in the SUSI Etherpad at http://dream.susi.ai...

**Comment by rishiraj824** [comment]
Will fix them in the issue #577
