### ISSUE TITLE
Improve the top bar design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#592]
Please ensure the design of the top is the same across the pages and change the design more closely to api.ai, specifically:
* take out the background layer behind tabs
* implement an underline just like Google sites
* use the same position as menu items on Google bars

But: Keep the colors of SUSI.AI.

![screenshot from 2017-07-24 01-34-14](https://user-images.githubusercontent.com/1583873/28504023-71ab6c8a-7010-11e7-9832-fe174f781cba.png)

**Comment by isuruAb** [comment]
ill work on this
