### ISSUE TITLE
Scrolling wrong, cuts off images

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#594]
**Actual Behaviour**

Scrolling is not to the end of the picture.

**Expected Behaviour**

Scrolled to the bottom of the picture, so you can see it.

**Steps to reproduce it**

Ask for a png, eg. by "image of a dog".

**Actual behaviour screenshot**
![susierr](https://user-images.githubusercontent.com/10114907/28505071-52501c36-7020-11e7-9f66-9b2a7dc97a0e.png)

**Expected behaviour screenshot:**
![errtemp](https://user-images.githubusercontent.com/10114907/28505133-130d64ec-7021-11e7-9952-50e40a1dac6e.png)

Side note: First a "please wait" bubble is rendered. The scrolling 
is not updated when the actual results are rendered.

**Comment by isuruAb** [comment]
I will work on this

**Comment by isuruAb** [comment]
i ll try this

**Comment by r0hit-gupta** [comment]
@tabesin I am unable to reproduce the issue. Can you please check again if it is working for you or not?

**Comment by isuruAb** [comment]
hello @r0hit-gupta  , Just  ask this question from susi, "image of a dog". to see the image user need to scroll down the message pane.

**Comment by maximux13** [comment]
@tabesin @isuruAb I would like to take a look of this. I'll send you a PR in a while.

**Comment by isuruAb** [comment]
@maximux13  sure go ahead 👍

**Comment by sagar-kalra** [comment]
@isuruAb Can i work on this issue?

**Comment by isuruAb** [comment]
hello @maximux13,  how is the progress of this issue ?

**Comment by maximux13** [comment]
@isuruAb Sorry. I couldn't find a proper solution for this.

**Comment by isuruAb** [comment]
@sagar-kalra  you can work on this.
@maximux13  its okay, try out to solve other issues 👍

**Comment by arnav-mandal1234** [comment]
Can I work on this?
