### ISSUE TITLE
Proposal on how to handle connectivity loss

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#600]
**Actual Behaviour**

When you fire up the chat.susi.ai and then cut your internet connectivity and ask Susi the web app is put idle. Even after restoring the internet connection it stays as such. Connectivity loss may also happen while a request is being sent to the server.

**Expected Behaviour**

Please sketch options how SUSI web app should handle net connectivity losses to provide for great user experience. Loss of connectivity can easily happen, e.g. when you are on a train ride or when your net connection is not reliable.

**Steps to reproduce it**

1. Open http://chat.susi.ai in a web browser.
2. Cut your Wifi/unplug your net cable.
3. Ask a question.

![bildschirmfoto vom 2017-07-24 23-13-29](https://user-images.githubusercontent.com/10114907/28545266-a2c68b5e-70c6-11e7-9ebb-05436d495d93.png)

4, Reestablish internet connection.

**Questions for Options**
1. How could the user be made aware of connectivity loss conveniently? How do other chat apps deal with connectivity loss/Flight mode?
2. Do we want to disable the option to ask questions when there is a connectivity loss?
3. How can we ensure that idle questions get answered once the connectivity is back?
4. Do we want to implement a minimum local/client side skill set for the case of no net connectivity such as: "Sorry, can't answer that now. I have no net connectivity"?

**Comment by rishiraj824** [comment]
Will try to fix this :+1:
