### ISSUE TITLE
Improve team page and add more data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#603]
Please add the following to the team page:

Project Founders
* Add Twitter, LinkedIn, Website or Blog to each person

Section for "Managers"
* Hong Phuc Dang, Community and Project Manager (use images of http://2017.fossasia.org)
* Eden Dang, Event Manager
* Add Twitter, LinkedIn, Website or Blog to each person

Section "Developers"
* Sort developers by name
* Add main contributors who have worked on the project before into developers section, e.g Harshit, Sudheesh, Damini, Jigyasa, Niranjan etc.
* Add Github, Twitter, LinkedIn, Website or Blog to each person similar to FOSSASIA Summit site - on scroll over
* Change subinfo line to add the info about the core item, e.g. "Android Developer" instead of "Github" link

**Comment by isuruAb** [comment]
I will work on this
