### ISSUE TITLE
Overview page cut off in mobile view

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#611]
**Actual Behaviour**

The last section of overview page is being cut off in mobile view.

**Expected Behaviour**

Show the entire page like other static pages

**Steps to reproduce it**

Visit http://chat.susi.ai/overview in mobile phone and scroll to the bottom. `Safe and Secure` section is cut off.

**Screenshots of the issue**

![err](https://user-images.githubusercontent.com/13276887/28621247-f6d90c04-722d-11e7-8011-1f82a437c024.png)

**Would you like to work on the issue?**

Anyone can take this up

**Comment by isuruAb** [comment]
i ll work on this
