### ISSUE TITLE
Deploy new react SUSI chat app on GitHub pages

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#63]
- Deploy new chat app on Github pages.
- Update the README file

**Comment by rishiraj824** [comment]
After reading through this gist, I found that we need to get the encrypted credentials from the Travis website. https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials. This link has a demo on how to get the Travis encrypted files. After that, the deploy.sh in the current repo can be made to work. @mariobehling @isuruAb
