### ISSUE TITLE
Unite settings on route /settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#635]
Different features that should be united in a settings page are accessible on the dropdown menu. Please change as follows:

* Delete "Chat anonymously". There is no need for this, people can simply log out and chat anonymously.
* Move "Change Password" into settings
* Make settings into its own page `/settings`
* Show "Overview" on dropdown menu
![screenshot from 2017-07-29 19-28-33](https://user-images.githubusercontent.com/1583873/28746925-3d1965de-7494-11e7-9be7-09be0c6ed175.png)

**Comment by uday96** [comment]
Working on this :+1:

**Comment by mariobehling** [comment]
@uday1201 Please also ensure the Overview link shows up on the dropdown when the user is logged in.

**Comment by uday96** [comment]
@mariobehling sure.

**Comment by uday96** [comment]
@rishiraj824 This can be closed now. Implemented in https://github.com/fossasia/chat.susi.ai/pull/625

**Comment by rishiraj824** [comment]
closing via #625
