### ISSUE TITLE
Fix bottom bar on all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#639]
The bottom bar has empty links and on some pages missing items. Please fix this.

* Logo on all pages, that links to "Overview" page
* Change "About" to "Overview" and link to overview page
* Change blog to `/blog`
* Add page `/contact` in the same style as `/support`

![screenshot from 2017-07-30 10-40-52](https://user-images.githubusercontent.com/1583873/28751908-ba7ffd42-7513-11e7-91d0-b84abafdf87f.png)

**Comment by rishiraj824** [comment]
working on it :+1:

**Comment by rishiraj824** [comment]
working on this :+1:

**Comment by rishiraj824** [comment]
closing via #644
