### ISSUE TITLE
Use same width of content across all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#641]
The width of the content area is different on different pages. Please ensure the distance to the left and right is the same on all pages, e.g. compare the left area on the Overview and Support page.

![screenshot from 2017-07-30 14-06-00](https://user-images.githubusercontent.com/1583873/28753193-6d130604-7530-11e7-9d0e-9eb54b82b3ff.png)

**Comment by isuruAb** [comment]
I will do this
