### ISSUE TITLE
make a simple chat application UI 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#65]
Make a simple chat application UI using material UI http://www.material-ui.com/#/
**SPECIALLY** : User Interface should be Mobile friendly

**Comment by isuruAb** [comment]
I will work on this.

**Comment by madhavrathi** [comment]
@isuruAb Hey, let's work on this together(can divide sections), comment the changes you want(or dm me) and i'll send a pull request to your repository, and after basic UI is made, we'll send PR.
Anyone else who is interested can do the same.
is this okay for you ?

**Comment by Manveer695** [comment]
@madhavrathi @isuruAb I too want to work. I can make the header of the page as a start section for me. Can I? Also, tell me if it should be the same as the previous header as in susi.ai/chat.

**Comment by uday96** [comment]
@isuruAb @Manveer695 @madhavrathi can I also join? The main part is the component to submit queries and a component to display answers. And there is the headers component. Any other components?

**Comment by Manveer695** [comment]
@isuruAb @madhavrathi @uday96 Let's not ask each other if we can make something or not. Let's discuss the components of this UI. After that, we can assign those to ourselves. First, are we thinking to make the UI exact as the previous UI? If it is so. The components are -:
1. Header
2. Left portion (which has written Susi is online).
3. The right portion which has the main part (the textbox, send button, query box, answer box).

Anyone who has done with React can start working. I am still learning. So whatever progress we have with the project, we can comment here. I just want to make the header of it.
Thanks!

**Comment by uday96** [comment]
@Manveer695 I meant the same. Im new to react too. Ill work on the static susi online portion and follow up :)
