### ISSUE TITLE
Test and fix responsiveness of all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#654]
Several pages have issues. Test and fix responsiveness for small screens on all pages.

E.g. see below issues on Overview page.
![screenshot from 2017-07-31 23-18-48](https://user-images.githubusercontent.com/1583873/28798997-f564a6d6-7646-11e7-8a56-ca65674de5ca.png)

![screenshot from 2017-07-31 23-18-23](https://user-images.githubusercontent.com/1583873/28799004-f88a4140-7646-11e7-945a-eea6cfe311f8.png)

**Comment by madhavrathi** [comment]
Will do this.

**Comment by rishiraj824** [comment]
closing via #665
