### ISSUE TITLE
Fix Dropdown menu structure and views across apps and pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#657]
**Not logged in users:**
About -> Overview
Chat -> /chat app
Skills -> / skills app
Settings -> /settings
Login -> login

**Logged in users:**
About -> Overview
Chat -> /chat app
Skills -> / skills app
Settings -> /settings
[Themes -> theme popup (only in chat app)]
Logout -> logout

* Add icons to all menu items
* Don't show "signup" on menu. The link to signup on the login page is sufficient.
* On chat app direct settings to chat app settings
* On skills cms direct settings link to skills settings
* Ensure the dropdown menu works on the same way on chat pages overview etc.

**Comment by rishiraj824** [comment]
Will do this
