### ISSUE TITLE
Fix 404 Page

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#680]
**Screenshots of the issue**

![screenshot from 2017-08-06 02 18 10](https://user-images.githubusercontent.com/11540785/28998618-a657d9a4-7a4d-11e7-87e7-d81642f8bbaa.png)

**Would you like to work on the issue?**

Yes

**Comment by madhavrathi** [comment]
@rishiraj824 I have fixed this in PR: https://github.com/fossasia/chat.susi.ai/pull/672

**Comment by rishiraj824** [comment]
okay will close this after it get's merged.

**Comment by rishiraj824** [comment]
closing via #672
