### ISSUE TITLE
Test UI on Firefox and fix bugs.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#684]
**Actual Behaviour**

The UI is not stable in Firefox. 

**Expected Behaviour**

The UI should work on all the browsers seamlessly

**Would you like to work on the issue?**

Anyone can contribute and solve if there are any bugs.

**Comment by madhavrathi** [comment]
@rishiraj824 :+1:

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 The buttons were aligned in top bar via https://github.com/fossasia/chat.susi.ai/pull/687
