### ISSUE TITLE
Test the STT/TTS on Chrome and comment if it is not working. 

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#685]
The STT/TTS has a support for all latest Chrome browsers as mentioned in the Mozilla docs https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API. Please comment the following details, if STT/TTS is not working 
The current support details is seen on the screenshot:
![screenshot from 2017-08-07 00 46 54](https://user-images.githubusercontent.com/11540785/29006391-4581d7aa-7b0c-11e7-893c-51e090d4a20d.png)

```
Chrome Browser Version:
OS Version:
```
@saurabhjn76 @madhavrathi @chiragw15 @uday96 @isuruAb @DravitLochan @dynamitechetan @chashmeetsingh @betterclever @amitiwary999 @Manveer695 @AliAyub007 
 Please test the functionality of STT/TTS. Thank You!

**Comment by chiragw15** [comment]
STT working on Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)
whereas TTS not working.

**Comment by rishiraj824** [comment]
Thanks, @chiragw15 Will check it out.

**Comment by AliAyub007** [comment]
STT not working but TTS working. 
Chrome version: Version 59.0.3071.115 (Official Build) (64-bit)
OS : macOS Sierra 10.12.6 (16G29)

**Comment by rishiraj824** [comment]
@chiragw15 Can you please try running these two lines in the console and tell me the output.
```
var msg = new SpeechSynthesisUtterance('Hello World');

window.speechSynthesis.speak(msg)
```

**Comment by amitiwary999** [comment]
STT and TTS not working
Version 60.0.3112.90 (Official Build) (64-bit)
Ubuntu 16.04(64-bit)

**Comment by rishiraj824** [comment]
@amitiwary999  Please follow the directions in this comment.  https://github.com/fossasia/chat.susi.ai/issues/685#issuecomment-320938834 And tell me if this works for you as well or not?

**Comment by isuruAb** [comment]
STT and TTS not working 
Chrome Version 60.0.3112.90 (Official Build) (64-bit)
macOS 10.12.5 (16F73)

**Comment by betterclever** [comment]
STT not working.
TTS working
Chrome Version: 60.0.3112.90 - 64 bit
Ubuntu 16.04

**Comment by madhavrathi** [comment]
STT not working.
TTS working
Chrome Version: 60.0.3112.78 (Official Build) (64-bit)
Ubuntu 16.04

**Comment by rishiraj824** [comment]
@betterclever @madhavrathi Please use https://chat.susi.ai to test this. This needs https domains to work. Chrome does not load unsafe scripts now.

**Comment by nikhilrayaprolu** [comment]
@rishiraj824 does susi supports https? I get mixed content error when I am using the https link

**Comment by rishiraj824** [comment]
@nikhilrayaprolu No it doesn't at the moment. The CORS policy must be preventing the request to be sent. So both the server and the client needs to be converted to https.

**Comment by mariobehling** [comment]
Working now with https.
