### ISSUE TITLE
Redundant hamburger on /settings to be removed

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#686]
**Actual Behaviour**
there is a hamburger icon which is unnecessary

**Expected Behaviour**

it should be removed
**Screenshots of the issue**

![screenshot from 2017-08-07 01 19 31](https://user-images.githubusercontent.com/11540785/29006477-7fd4e3dc-7b0e-11e7-8f22-fcf3d9574f66.png)

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
The hamburger must be removed. I had removed that while making the settings route. There is no need for a drawer in settings route

**Comment by rishiraj824** [comment]
@uday96 okay, will remove that. Thanks!

**Comment by rishiraj824** [comment]
updated the details accordingly
