### ISSUE TITLE
Make minimal UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#69]
The only thing we need to get started is a UI like the Android-UI. We don't need any side or anything else. Please as a first start implement a minimalistic U, e.g. similar to the Android app.

![f538315a-f54a-11e6-9084-9f9d73596a0c](https://cloud.githubusercontent.com/assets/1583873/26023706/a590d408-37c2-11e7-8764-4441bda2b75d.jpg)

**Comment by mariobehling** [comment]
@rishiraj824 please ensure the UI is responsive and works well on phones filling complete width and height on smartphones.

**Comment by rishiraj824** [comment]
@mariobehling Yes, will take care.
