### ISSUE TITLE
Change top line on Overview and add Meta Tags to pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#691]
* Change "Meet SUSI, Your Personal Assistant." to "Meet SUSI.AI, Your Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots."
* Change start page title tag to "SUSI.AI Chat -  Open Source Artificial Intelligence"
* Overview title tag: "SUSI.AI - Open Source Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots."
* Devices title tag: "SUSI.AI - Open Source AI for Any Device, Android, iOS, Robots, Help Desks, Linux"
* Blog title tag: "Blog Posts about Open Source Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots - SUSI.AI"
* Team title tag: "Developer Team of SUSI.AI - Open Source Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots"
* Support title tag: "Support for SUSI.AI - Open Source Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots"
* Contact title tag: "Developer Team of SUSI.AI - Open Source Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots"
* Terms title tag: "Terms and Conditions - SUSI.AI, Open Source Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots"

**Comment by madhavrathi** [comment]
Will do this.
