### ISSUE TITLE
Custom theme background images are not stored in server

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#701]
**Actual Behaviour**

Custom theme background images are not stored in server

**Expected Behaviour**

Custom theme background images should be stored in the server

**Would you like to work on the issue?**

yes

**Comment by rishiraj824** [comment]
@isuruAb Currently the `listUserSettings` just store key values as strings. How are we going to store images on the server?

**Comment by isuruAb** [comment]
@rishiraj824 can't we send image URL to the server instead of image ?

**Comment by isuruAb** [comment]
@rishiraj824  since there is no end point for do this. this can't be implemented now.
