### ISSUE TITLE
Migrating from /settings to chat.susi.ai shows error

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#708]
**Actual Behaviour**
The error of `forceUpdate` is shown while moving from `/settings` to `chat.susi.ai`

**Expected Behaviour**

There shouldn't be any such error.

**Screenshots of the issue**
![screenshot from 2017-08-09 04 15 00](https://user-images.githubusercontent.com/11540785/29097791-5706462e-7cb9-11e7-885f-dde66c2596c9.png)

**Would you like to work on the issue?**

Yes

**Comment by isuruAb** [comment]
Can you check this again. It's working fine with 0 errors

**Comment by rishiraj824** [comment]
closing as fixed now thanks @isuruAb :+1:
