### ISSUE TITLE
Previous reactions don't get saved on reload

### ISSUE THREAD

**Issue by ashwini0529** [fossasia/chat.susi.ai#715]
When you react to a response:

<img width="707" alt="screen shot 2017-08-09 at 11 11 07 pm" src="https://user-images.githubusercontent.com/8419333/29135987-80132cf8-7d59-11e7-8e9a-de017c635a1b.png">

When you reload after reacting

<img width="707" alt="screen shot 2017-08-09 at 11 11 31 pm" src="https://user-images.githubusercontent.com/8419333/29135959-6da5244a-7d59-11e7-9ba2-82481817a64e.png">

**Comment by madhavrathi** [comment]
@ashwini0529 Nice of you to point this error, but this is done intentionally. We collect the feedback data on the server and plan to use it for machine learning algorithms. The feature you are suggesting was implemented before but was changed due to the request from mentors.
@rishiraj824 Please correct me if I am wrong. 
Thanks

**Comment by ashwini0529** [comment]
@madhavrathi I get your point but what if the user changes his mind to change the reaction?

**Comment by madhavrathi** [comment]
@ashwini0529 You're right. In that user can select thumbs down and we will collect it on server. Basically we are recording total thumbs up and downs.

**Comment by ashwini0529** [comment]
@madhavrathi right now, user cannot vote the previous messages.

**Comment by ashwini0529** [comment]
It would be even great if we introduce an option wih something like:
`Was this response helpful?`
`Yes`, `No`, `Maybe`
That would help to understand the response even better.

**Comment by ashwini0529** [comment]
@madhavrathi We cannot react in mobile view. It's not storing responses. Please check.
Also, what are your thoughts on the above suggestions? It would be great if you could fix it?

**Comment by madhavrathi** [comment]
@ashwini0529 I will check that out right now. Please propose your ideas on our gitter channel https://gitter.im/fossasia/susi_webchat, so that we can have this reviewed from mentors and proceed. Thanks a lot

**Comment by uday96** [comment]
@ashwini0529 The user can change his feedback only for the most recent response until he makes a new query. Once the message is tagged as a history message, the user cannot change his response.

**Comment by ashwini0529** [comment]
What if a user reacts 👍  first, and then sends the same message and then reacts 👎 
It would actually nullify the overall reaction, as @madhavrathi told that analysis is being done on the basis of `total counts`. Ermm, I guess this needs improvement. 
@uday1201 what are your thoughts on it?

**Comment by madhavrathi** [comment]
@ashwini0529 You must have been confused, I said we collect total number of thumbs ups and downs on the server. The call to the server is made only once. So it does not nullifies the reaction. Hope it is much more clear to you now.

**Comment by ashwini0529** [comment]
I guess it cancels. Please check.

**Comment by uday96** [comment]
@ashwini0529 
> What if a user reacts :+1: first, and then sends the same message and then reacts :-1: It would actually nullify the overall reaction

In this case the server will be storing +1 and -1 and not 0. The positives and negatives are not combined in the server. How this feedback will be used on server side is yet to be properly proposed and implemented. You can propose a better mechanism on the client side as of now for sending the feedback to server if you have any suggestions :smiley:
