### ISSUE TITLE
Custom Setting Under Select Themes doesn't do anything.

### ISSUE THREAD

**Issue by mehuled** [fossasia/chat.susi.ai#719]
**Actual Behaviour**

On selecting `Custom Theme` under Chat Settings > Select Theme, and saving the settings, nothing seems to happen.
The other two options that are `Light` and `Dark` works fine.

**Expected Behaviour**

A pop up should open that should allow the user to select a theme from a set of preloaded themes and then the theme of the web chat should change accordingly.

**Would you like to work on the issue?**

I do not have requisite skills for the technical stack used so please assign this to someone else.

**Comment by isuruAb** [comment]
i'll finish this

**Comment by mehuled** [comment]
Sure!

**Comment by isuruAb** [comment]
@mehuled  Now it is working.could you please check it again.

**Comment by mehuled** [comment]
Sure, I'll just have a look.
