### ISSUE TITLE
Make white secondary menu bar to be more consistent and link functionality of Skill Name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#721]
![screenshot from 2017-08-11 16-03-02](https://user-images.githubusercontent.com/1583873/29219060-2d3b90f6-7eb7-11e7-9b35-a189e187e603.png)

Change the white bar as follows:
* Show "Skill Name" instead of "Enter Skill name" and only show it when the user starts to fill in something (follow the same way as the previous two menu points)
* Implement a functionality link between the first line of the file "::name <Skill_name>" and "Skill Name" field. It needs to show the same thing. Follow Wikipedia here.

**Comment by dynamitechetan** [comment]
I will work on this issue.
