### ISSUE TITLE
Improve Support Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#722]
* Move "Chat with Us* to its own section below
![screenshot from 2017-08-11 18-12-24](https://user-images.githubusercontent.com/1583873/29221870-a712f3fc-7ec0-11e7-9ac4-ca49b5823151.png)
* Change "Browse, Create and Edit your own Skills" to a full width section
   * Change "Create a SUSI Dream / You can easily create a SUSI.AI dream in the SUSI Etherpad at http://dream.susi.ai" to "Test Your SUSI.AI Skills and Create Dreams / You can insert your skill code and test it on the SUSI.AI Etherpad at dream.susi.ai."
   * Add a subsection: "Create and Edit a SUSI.AI skill / You can easily create a skill on the SUSI.AI skills editor at skills.susi.ai."
![screenshot from 2017-08-11 18-11-55](https://user-images.githubusercontent.com/1583873/29221851-92f2205a-7ec0-11e7-9bbc-ff760b02ee18.png)
* Provide an icon in the same color as other icons for SUSI.AI Docs
![screenshot from 2017-08-11 18-03-44](https://user-images.githubusercontent.com/1583873/29221537-70bcbc6c-7ebf-11e7-9f0a-0a7a247c370a.png) and take out "http"
* Take out "http" from all text, but keep the links

**Comment by madhavrathi** [comment]
@mariobehling Will do this.
