### ISSUE TITLE
Fix small design issues 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#723]
* Support and Contact Page have a line that does not go the completely through
![screenshot from 2017-08-11 17-54-02](https://user-images.githubusercontent.com/1583873/29221198-26b509f4-7ebe-11e7-9493-21cd18f9e040.png)

* Please ensure that the description of items on the a) Support b) Contact c) Terms pages uses the same font color as other pages e.g. the overview page
![screenshot from 2017-08-11 17-55-16](https://user-images.githubusercontent.com/1583873/29221235-5a06c96e-7ebe-11e7-8c68-cfcc16c910b5.png)

* Terms page: Use the same style as for the contact and support page and below "Terms of Service" add a line "Thanks for using SUSI.AI."

* Devices page: Change subheading to "SUSI.AI is available on many platforms"
![screenshot from 2017-08-11 18-56-19](https://user-images.githubusercontent.com/1583873/29223434-d14c3ba0-7ec6-11e7-875c-7c23245f8f83.png)

**Comment by madhavrathi** [comment]
@mariobehling Will do this.

**Comment by isuruAb** [comment]
i'll do this
