### ISSUE TITLE
Add pot/po files to the locales folder.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#729]
The following files and folders are to be added based on the locales - en, de.
- In `src/components/Translate/de.json`  & `src/components/Translate/en.json`
Add strings from the following components in the following [format ](https://github.com/fossasia/chat.susi.ai/pull/712/files#diff-04e1039e72ff66083ba183900389d6e7)
- In `src/components/locales/de/LC_MESSAGES/messages.po` add all the strings with German Translations in the following [format](https://github.com/fossasia/chat.susi.ai/pull/712/files#diff-c148968586c08ec4fee3e26d3d43421c)
- In `src/components/locales/messages.pot` add all strings in the following [format](https://github.com/fossasia/chat.susi.ai/pull/712/files#diff-196818c81f733c6e05069f5a9211cd61) 

**Note:- All strings should have a unique key**
Let me know if I missed any component,

```
components/Auth/Login/Login.react
components/Auth/SignUp/SignUp.react
components/Auth/ChangePassword/ChangePassword.react
components/Auth/ForgotPassword/ForgotPassword.react
components/ChatApp/Settings/Settings.react.js
components/ChatApp/Settings/TextToSpeechSettings.react.js
components/ChatApp/MessageSection/MessageSection.react.js
components/ChatApp/HardwareComponent.react.js
components/ChatApp/SearchField.react.js
components/ChatApp/MessageComposer.react.js
```

**Would you like to work on the issue?**

@uday96 @rishiraj824 @madhavrathi @isuruAb  can divide the components among ourselves.

**Comment by rishiraj824** [comment]
I have already added it for the TopBar in #712.
I'll add more for 
```
components/Auth/Login/Login.react
components/Auth/SignUp/SignUp.react
```

**Comment by madhavrathi** [comment]
I will add for : 
components/Auth/ChangePassword/ChangePassword.react
components/Auth/ForgotPassword/ForgotPassword.react

**Comment by uday96** [comment]
I will add for 
components/ChatApp/Settings/Settings.react.js
components/ChatApp/Settings/TextToSpeechSettings.react.js

**Comment by isuruAb** [comment]
okay I will add for
components/ChatApp/MessageSection/MessageSection.react.js
components/ChatApp/HardwareComponent.react.js

**Comment by rishiraj824** [comment]
closing as added via #712
