### ISSUE TITLE
Document all the code files, add relevant comments.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#736]
**Actual Behaviour**

The current files need to have comments and logic wherever necessary.

**Would you like to work on the issue?**

@isuruAb @madhavrathi @uday96 and @rishiraj824 can divide the components and work on it.

**Comment by uday96** [comment]
I'll work on 
 - Auth
 - Message List Items
 - Settings

**Comment by rishiraj824** [comment]
I'll work on 
- `actions`
- `stores`
- `constants`
-  `utils`

**Comment by isuruAb** [comment]
I'll work on 

- chat.susi.ai/src/components/ChatApp/MessageSection/
- chat.susi.ai/src/components/ChatApp/ChatApp.react.js
- chat.susi.ai/src/components/ChatApp/CustomServer.react.js
- chat.susi.ai/src/components/ChatApp/MessageComposer.react.js

**Comment by madhavrathi** [comment]
I'll work on all static pages and static app bar
