### ISSUE TITLE
Add Page "Privacy" and take out "Settings" from Footer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#742]
We need a page for a privacy policy. Use the same style as for "Terms" page. Also do the following:
* Add link "Privacy" in the footer on the right hand side
* Implement the following order: Privacy, Terms, Contact
* Take out "Settings" from footer

![screenshot from 2017-08-19 16-33-48](https://user-images.githubusercontent.com/1583873/29487613-918c4910-84fc-11e7-8071-9dd15ab02e52.png)

**Comment by rishiraj824** [comment]
will do this :+1:
