### ISSUE TITLE
Implement settings page following social media market leaders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#761]
Market leaders like twitter and Facebook are following a more simple approach on their settings page. Please follow this approach. Keep a menu on the left and options on the right.

![screenshot from 2017-08-23 02-04-43](https://user-images.githubusercontent.com/1583873/29592997-ec27c1e4-87a7-11e7-8fb2-60a4c870b84e.png)

**Comment by madhavrathi** [comment]
Will do this

**Comment by mariobehling** [comment]
Please follow up on this and enhance style and functionality: https://github.com/fossasia/chat.susi.ai/issues/796
