### ISSUE TITLE
It shows previously selected theme after selecting a new one.

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#769]
**Actual Behaviour**

It shows previously selected theme after selecting a new one.

**Expected Behaviour**

it should show the selected new one after selecting a new theme.

**Screenshots of the issue**

<img width="177" alt="screen shot 2017-08-25 at 7 43 35 am" src="https://user-images.githubusercontent.com/7692626/29697189-3b2a61f6-896b-11e7-91fc-0ede72696312.png">
<img width="120" alt="screen shot 2017-08-25 at 7 43 41 am" src="https://user-images.githubusercontent.com/7692626/29697190-3b2ee136-896b-11e7-9b98-5dc4c6437c7c.png">

**Would you like to work on the issue?**

yes

**Comment by rishiraj824** [comment]
@isuruAb Are you still working on this?

**Comment by isuruAb** [comment]
@rishiraj824  no you can work on it

**Comment by rishiraj824** [comment]
@isuruAb Ok i will do it

**Comment by Remorax** [comment]
@rishiraj824 Are you working on this issue?

**Comment by rishiraj824** [comment]
@Remorax Not at the moment. You can proceed with the issue.

**Comment by madhavrathi** [comment]
@Remorax Please state what you've tried till now. and we'll try solving this together.

**Comment by madhavrathi** [comment]
You can even change it to have toggle using following code:
```
<RadioButtonGroup
						style={{textAlign: 'center', margin: 20}}
						onChange={this.handleSelectChange}
						name="Theme"
						defaultSelected={this.state.theme}>
      			<RadioButton
							style={{width: '20%', display: 'inline-block'}}
        			value='light'
        			label={<Translate text="Light" />}
      			/>
      			<RadioButton
							style={{width: '20%', display: 'inline-block'}}
        			value='dark'
        			label={<Translate text="Dark" />}
      			/>
    			</RadioButtonGroup>
```
This will look like following: 
![screen shot 2017-09-09 at 11 21 04 pm](https://user-images.githubusercontent.com/22375731/30242538-ba4c48ea-95b5-11e7-821d-1c5ee8269121.png)

**Comment by RMCoder198** [comment]
@Remorax  Are you still working on this issue?

**Comment by RMCoder198** [comment]
@Remorax  ok, you have done it.

**Comment by Remorax** [comment]
@madhavrathi @rishiraj824 Can this issue be closed?

**Comment by isuruAb** [comment]
@mariobehling  this issue can be closed
