### ISSUE TITLE
Implement web result for unknown responses.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#78]
For the responses like **I don't know how to answer this. Here is a web search result:** show the web result or a generate a hyperlink on the query.
![issue1](https://cloud.githubusercontent.com/assets/11540785/26109207/65d76aaa-3a6c-11e7-8706-2cf0ea7dca42.png)

**Comment by isuruAb** [comment]
search result would be good.  but this is something related to skills as i think .

**Comment by rishiraj824** [comment]
@isuruAb I think we can filter the query responses if they have the attribute "actions" type web search.
```
{
query: "find me restaurants",
count: 1,
client_id: "aG9zdF8xNTcuNTEuMTMuMTkx",
query_date: "2017-05-18T19:54:21.358Z",
answers: [
{
data: [
{
0: "find me restaurants",
1: "find me restaurants",
timezoneOffset: "0"
}
],
metadata: {
count: 1
},
actions: [
{
type: "answer",
expression: "I don't know how to answer this. Here is a web search result:"
},
{
type: "websearch",
query: "find me restaurants"
}
]
}
],
answer_date: "2017-05-18T19:54:21.444Z",
answer_time: 86,
language: "en",
session: {
identity: {
type: "host",
name: "157.51.13.191",
anonymous: true
}
}
}
```

**Comment by uday96** [comment]
Should susi make another call to itself with a websearch skill or an external api and give the response?
So there will be two calls in total?

**Comment by betterclever** [comment]
@uday96 as per android client, this needs up to be displayed there in UI itself by calling an external API there. Also check this out, orbiter clear this up here https://github.com/fossasia/susi_android/issues/150

**Comment by uday96** [comment]
@Orbiter I used "search *" for pattern matching while writing a skill using duckduckgo api. Should I change that? fossasia/susi_android#150 has a query "search freedom" so the response is different for the same query now.
@betterclever thanks, but the actions in the above screenshot are different. How to handle those cases with type "websearch"?

**Comment by uday96** [comment]
**Demo Link:** http://susiwebsearch.surge.sh/
**Sample Queries:** 'Germany', 'Marvel', 'artificial Intelligence' etc which give action type websearch

For few queries like 'find me restaurants', even duckduckgo doesnt give any response. How to handle such cases?

@rishiraj824 @isuruAb suggest changes.
