### ISSUE TITLE
Changing the theme while logged in changes the language

### ISSUE THREAD

**Issue by rishirajjain** [fossasia/chat.susi.ai#791]
**Actual Behaviour**
When logged in and trying to change the theme from the themes tab changes the language instead of the theme. Also the buttons 'Done' & 'Save' turn white.

**Expected Behaviour**
It should change the theme of the app.
**Steps to reproduce it**
1)Login 
2)Try to change the theme from the settings bar.

**Screenshots of the issue**

![screenshot_20170912_161615](https://user-images.githubusercontent.com/20815882/30322066-e24b07ec-97d5-11e7-9e95-8638f5a696cb.png)

**Would you like to work on the issue?**
Yes

**Comment by rishirajjain** [comment]
How do I find the request made by the save button ? Can someone please direct me.

**Comment by Remorax** [comment]
I am working on this issue @rishirajjain. I'll let you know if I get something.

**Comment by rishirajjain** [comment]
@Remorax  I'm already working on this.

**Comment by Remorax** [comment]
Oh okay, continue then 👍

**Comment by isuruAb** [comment]
@rishiraj824  it tries to fetch colour values from the server.  but there are no default colour values in server.  you will have to define default colour to show when there is no button colour define in server

**Comment by Remorax** [comment]
@madhavrathi @rishirajjain Are either of you working on this issue? I would like to take it up.

**Comment by rishirajjain** [comment]
Go ahead.

**Comment by isuruAb** [comment]
hello @Remorax  what is the status of this issue ?

**Comment by Remorax** [comment]
I'm working on it.
I changed the currTheme variable to theme, put debuggers in the render function and I saw that the theme does change, for some time, but due to some reason it calls the render function multiple times on clicking on any of the color buttons and in one of the iterations, the theme variable is undefined, which is why it reverts back to the default theme. I checked the server call functions, and the parameters to the AJAX request are correct, so that's not the problem. 
This is where I'm stuck right now. Do you have any idea why this could be happening? Any help is greatly appreciated :)

**Comment by isuruAb** [comment]
@Remorax  please check again. this function is working correctly .

**Comment by Remorax** [comment]
Yes, the theme changes perfectly. However, the moment I type a message, the theme reverts back to the default theme. 
Btw, sorry for the late response. I was actually out on holiday :)

**Comment by isuruAb** [comment]
@Remorax  could you please check this again it works fine for me .

**Comment by Remorax** [comment]
@isuruAb, I checked it after pulling the latest version of the code. It still doesn't work. That is, once the theme has been changed, if I ask Susi a question, the theme reverts back to the blue default theme.

**Comment by isuruAb** [comment]
@madhavrathi  please check this . This works for me but it does not work for @Remorax

**Comment by madhavrathi** [comment]
@isuruAb It works for me as well.

**Comment by akshatnitd** [comment]
Cannot be reproduced.
