### ISSUE TITLE
Fix spelling and syntax mistakes across app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#794]
The app has a lot of spelling and syntax mistakes. See below: The beginning of the sentence is not in capital. There is no full stop. The sentence is formulated in a confusing way.

Please check all interaction dialogues for this kind of issues.

![screenshot from 2017-09-16 04-10-59](https://user-images.githubusercontent.com/1583873/30508350-37ba8786-9a95-11e7-98dc-259e3d3d9225.png)

**Comment by tstreamDOTh** [comment]
I would like to work on this issue. 👍

**Comment by tstreamDOTh** [comment]
@mariobehling The dialogue in the screenshot contains response message of api. Created an issue on susi_server https://github.com/fossasia/susi_server/issues/575 
Also, working on other mistakes in chat.susi.ai .

**Comment by codejockie** [comment]
I'm indicating an interest in working on this issue as I'm new to open source contribution.

**Comment by Rogue00** [comment]
If no one is working on this, I can spend some time on it.

**Comment by anchepiece** [comment]
@mariobehling It would make sense to revisit how the api errors are returned to the user, for example, you could try something like 'An error occurred, please try again: Your current password matches new password'

'An error occurred, please try again: ' + response.message;
