### ISSUE TITLE
Enhance style and functionality of settings page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#796]
Please enhance style and functionality of settings page to make it closer to Twitter and Facebook.

![screenshot from 2017-08-23 02-04-43](https://user-images.githubusercontent.com/1583873/29592997-ec27c1e4-87a7-11e7-8fb2-60a4c870b84e.png)

Please do the following:
* Add save button to each page
* Align text on right side pages on the left and implement similar padding to twitter
* Make left-side bar similar to twitter
* Reduce space between left and middle bar to match twitter
* Make other items more similar to twitter
* Move "theme" to dedicated theme tab

Please also follow colors of skills.susi.ai:
* Make left and middle bar itself white
* Make background light gray as skills.susi.ai

![screenshot from 2017-09-16 04-35-33](https://user-images.githubusercontent.com/1583873/30508511-f7f84210-9a98-11e7-9497-63ee8bfff654.png)

**Comment by tstreamDOTh** [comment]
I would like to work on this issue. 👍

**Comment by tstreamDOTh** [comment]
@mariobehling Anything else required in order to close this issue?
