### ISSUE TITLE
Add Facebook integration

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#798]
The goal of the Facebook integration is, that SUSI.AI has the ability to post to Facebook, contact friends and other things. The first step is to add a Facebook integration to the chat and SUSI Server.

Add the relevant section into a settings tab/section.

**Comment by nileshgulia1** [comment]
@mariobehling  I want to work on this issue.

**Comment by nileshgulia1** [comment]
added facebook section in settings page looking forward to use facebook apis to share data

**Comment by isuruAb** [comment]
hello @nileshgulia1  how is the progress of this issue

**Comment by nileshgulia1** [comment]
hey @isuruAb,  by now i have added facebook section  in settings page and will add facebook post data api s in few days.. 
![screenshot from 2017-10-16 13-24-49](https://user-images.githubusercontent.com/22280901/31600821-749780bc-b275-11e7-87bc-a8a90026f72c.png)

**Comment by sayak119** [comment]
@isuruAb is this issue still open.

**Comment by isuruAb** [comment]
@sayak119  still not completed. user should have ability to post things on facebook using susi chat

**Comment by Remorax** [comment]
@isuruAb Right now, using the Share button, I guess it is possible to post things on Facebook. Can you please clarify what exactly needs to be done? Thank you 😄

**Comment by nileshgulia1** [comment]
Hello @Remorax, I was previously working on this issue ,and also made a PR already which is closed for now,you can check the code if u want and regarding facebook share ,there u have to use facebook share apis (javascript sdk if u want) have a look at it:https://developers.facebook.com/docs/web

**Comment by Remorax** [comment]
No @nileshgulia1, I was asking what exactly needs to be done because @sayak119 has solved this issue completely imo, and not how to do it, but thanks anyway 😄
