### ISSUE TITLE
Support for embed and display of youtube links

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/chat.susi.ai#8]
@Orbiter Can we use something from the youtube parser's data for this ? Like maybe the user can ask questions like

`Show me the best youtube video of Linkin park`
It should provide the link of Linkin park videos sorted by the likes they have, Is this possible already ?

**Comment by daminisatya** [comment]
No this is not yet integrated

**Comment by daminisatya** [comment]
@sudheesh001 If you are interested with integrating the youtube this issue must be in the server.
