### ISSUE TITLE
The app is not responsive. https://ibb.co/cjsb15, may be checked for reference. 

### ISSUE THREAD

**Issue by DeveloperAlfa** [fossasia/chat.susi.ai#800]
https://ibb.co/cjsb15

I can work with the issue

**Comment by DravitLochan** [comment]
@DeveloperAlfa Please solve the issue and send a pr.

**Comment by DeveloperAlfa** [comment]
Thankyou very much. I am new to Open Source contributions. Please help me get started with more tips. I will send the necessary pull request asap :)

**Comment by DeveloperAlfa** [comment]
Pull Request Sent. Issue may be closed after necessary review

**Comment by madhavrathi** [comment]
Fixed via https://github.com/fossasia/chat.susi.ai/pull/806
