### ISSUE TITLE
undefined as response to get

### ISSUE THREAD

**Issue by DeveloperAlfa** [fossasia/chat.susi.ai#802]
**Actual Behaviour**

whenever a command starting with get is given, undefined is returned

**Expected Behaviour**

Analyse and respond to it

**Steps to reproduce it**

Write get water, get (gibberish-words) and the chatbot replies undefined

**Screenshots of the issue**

https://ibb.co/ivCG3k

I can solve the issue with some assisstance in Language Processing

**Comment by tabesin** [comment]
Example: 
get me a horse
could fall back to "show me horse"

**Comment by DeveloperAlfa** [comment]
In most cases. This could be a good strategy :+1: 

Great thought.

**Comment by tabesin** [comment]
Get me out = close app

**Comment by DeveloperAlfa** [comment]
get me registered opens the signup page?
