### ISSUE TITLE
get me a meme is problematic

### ISSUE THREAD

**Issue by DeveloperAlfa** [fossasia/chat.susi.ai#803]
Actual Behaviour

get me a meme request sends [not clickable]path/link of the meme

Expected Behaviour

show the meme as an image

Screenshots of the issue

https://ibb.co/nrwFw5

I can work on the issue

**Comment by tabesin** [comment]
Is that a server skill related ("get me a meme") or a client rendering issue?

get me a dog 
get me a horse
responds with "undefined".

**Comment by DeveloperAlfa** [comment]
@tabesin refer #802, get is a special keyword. Get me a meme should return a meme. Thanks :smile:
