### ISSUE TITLE
Enhancement : Make the user choose background for the Chatbot using the Unsplash API

### ISSUE THREAD

**Issue by DeveloperAlfa** [fossasia/chat.susi.ai#807]
https://unsplash.com/developers

I can work on this.

**Comment by zamhaq** [comment]
@madhavrathi can I work on this one if @DeveloperAlfa is not already working?

**Comment by madhavrathi** [comment]
@zamhaq please proceed. Thanks

**Comment by zamhaq** [comment]
@madhavrathi @rishiraj824 @mariobehling is this issue relevant? since there is already a way to change background https://github.com/fossasia/chat.susi.ai/issues/868.
