### ISSUE TITLE
Create Test Cases for the App

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#81]
Currently, there are no test cases for all the issues. As the App is being made one needs to keep track of all the changes and run proper tests to ensure everything is working.

**Comment by isuruAb** [comment]
what is the test frame work we can use with this ? I found jest ( https://facebook.github.io/jest/ ) in web.is this the only and best solution for this ?

**Comment by rishiraj824** [comment]
@isuruAb Yes, the best would be Jest. as it's built for ReactJS itself.

**Comment by isuruAb** [comment]
working on this
