### ISSUE TITLE
Enhancements in Search chat function

### ISSUE THREAD

**Issue by hkedia321** [fossasia/chat.susi.ai#812]
**Actual Behaviour**

- On clicking the search icon, the input field doesn't get focused automatically.
- When there is no result for a search query, no indication is shown
- The search icon stays visible when the search is open 

**Expected Behaviour**

- On clicking the search icon, the input field should get focused automatically.
- When there is no result for a search query, a message must be shown
- The search icon should hide when the search is open

**Steps to reproduce it**
Click on the search icon on the top.

**Screenshoot**
![image](https://user-images.githubusercontent.com/17807257/30597739-84a7738c-9d75-11e7-85d7-962d71632dc8.png)

**Would you like to work on the issue?**
Yes, I would like to work on it.

Also, I would try to add any other enhancement in this search function, if I find. I would request others to suggest any other enhancements in this search function.

**Comment by mariobehling** [comment]
Not yet working on live site.

**Comment by madhavrathi** [comment]
@mariobehling are these features not working even now ? If yes, we can close the issue. Please take a look. Thanks
