### ISSUE TITLE
Remove SUSI.AI legacy susi.ai/chat

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#815]
While a running installation is at https://chat.susi.ai a Google Search points to an older sysfunctional incarnation of Susi.ai https://susi.ai/chat

1) pull the outdated install
2) pin https://susi.ai/chat traffic to https://chat.susi.ai

**Comment by Remorax** [comment]
@tabesin, the issue is not clear. Could you please elaborate, and post a screenshot or something?

**Comment by tabesin** [comment]
Follow the two links, if there are still questions, find someone who explains you.

**Comment by abishekvashok** [comment]
@tabesin I think this is fixed now,
https://susi.ai/chat points to https://chat.susi.ai
