### ISSUE TITLE
Copy previous message in chat on pressing the "up" key

### ISSUE THREAD

**Issue by hkedia321** [fossasia/chat.susi.ai#818]
**Actual Behaviour**

Nothing happens on pressing the "up" or the "down" key in chat

**Expected Behaviour**

On pressing the "up" key the previous message should be copied. And on pressing the "down" key, the following message should be copied.
Often the user wants to copy the previous message. This would enable the user to easily send previous messages with little or no modification to the message. 

**Steps to reproduce it**

Open the chat, and press the "up" or "down". Nothing happens.

**Would you like to work on the issue?**

Yes, I would like to work on this feature.

**Comment by gabru-md** [comment]
@hkedia321 what is the progress on this issue ?

**Comment by hkedia321** [comment]
@gabru-md I will be able to start with this in few days. You may work on this, if you would like.
Thanks.

**Comment by gabru-md** [comment]
Thanks ! I will start working on this.
Will get in touch if any problem occurs 
:D
