### ISSUE TITLE
Bottom text field disappears when search box on top is activated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#823]
The bottom text field disappears when search box on top is activated. 

Expected: Bottom field should always stay.

![screenshot from 2017-09-23 16-07-48](https://user-images.githubusercontent.com/1583873/30773850-8500b788-a079-11e7-967a-1998d42b0ea3.png)

**Comment by RMCoder198** [comment]
@mariobehling  I would like to work on this issue.
  Will you guide me how can i find the file from which i can fix this issue.
I am new to open source contribution.

**Comment by madhavrathi** [comment]
@RMCoder198 https://github.com/fossasia/chat.susi.ai/blob/master/src/components/ChatApp/SearchField.react.js This is the file you should look for. This was initially intended as a feature. you can disable the hiding of text box in this file. Cheers!

**Comment by RMCoder198** [comment]
@madhavrathi  Thanks .
