### ISSUE TITLE
TextArea is too white

### ISSUE THREAD

**Issue by gabru-md** [fossasia/chat.susi.ai#824]
**Actual Behaviour**

The Text-Box has almost White Text, barely visible to eyes.

**Expected Behaviour**

Should have black color for the textfield.

**Steps to reproduce it**

Changing some CSS will do.

**Would you like to work on the issue?**

Yes I would like to o it.

**Comment by ms10398** [comment]
Can you provide a screenshot of which textarea you are talking about.

**Comment by gabru-md** [comment]
![susi](https://user-images.githubusercontent.com/25414121/30775098-dcf76480-a085-11e7-8d14-7a111f4698b7.png)

**Comment by ms10398** [comment]
Is it showing white only for you

![screenshot from 2017-09-23 22-11-40](https://user-images.githubusercontent.com/26259547/30775168-74830f5e-a0ac-11e7-825d-087817028630.png)

**Comment by gabru-md** [comment]
wow!
okay Thanks @ms10398 
I can close this issue
