### ISSUE TITLE
Colour of arrow turns too much white

### ISSUE THREAD

**Issue by RMCoder198** [fossasia/chat.susi.ai#825]
**Actual Behaviour**
After changing the theme, colour of arrow for sending the message turns too much white .

**Expected Behaviour** 
It should be blue .

**Steps to reproduce**
1. Log in
2.Change the theme

**Screenshots of the issue**

![screenshot from 2017-09-23 22-15-34](https://user-images.githubusercontent.com/26675957/30775273-f38a2b1a-a0ad-11e7-80a0-5e420de80708.png)

**Would you like to work on the issue?**
Yes.

**Comment by ms10398** [comment]
I think you should check it again because it shows blue for me.
![screenshot from 2017-09-23 22-32-48](https://user-images.githubusercontent.com/26259547/30775357-721dc56c-a0af-11e7-85a1-dde2ec63c82c.png)

**Comment by RMCoder198** [comment]
@ms10398  
Not after changing theme.

**Comment by RMCoder198** [comment]
You can change theme after login .

**Comment by ms10398** [comment]
For which theme its not showing the arrow

**Comment by RMCoder198** [comment]
Its showing the arrow but its too much white.

**Comment by ms10398** [comment]
Yes sure go ahead!!
