### ISSUE TITLE
SUSI doesn't respond to gibberish text. 

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/chat.susi.ai#826]
**Actual Behaviour**

If somebody sends gibberish text on chat like "dgfjnhdsg" and press enter, either there is a very late miscellaneous response / undefined / takes infinite time to respond. 
An api call is made unnecessarily and adds load to the server. Also in future, such texts are irrelevant if any learning model is applied over SUSI.

**Expected Behaviour**
Identify gibberish text on client and respond gracefully with a message like "Sorry?", "Try again maybe?", "Uh?". Instead of sending a request to the server to respond, it must be managed on the client side using gibberish classification algorithm. 

**Screenshots of the issue**

![screen shot 2017-09-24 at 11 44 31 pm](https://user-images.githubusercontent.com/11137394/30785332-250de7c8-a183-11e7-851d-e630154d9270.png)

**Would you like to work on the issue?**

Yes I would like to.

**Comment by proishan11** [comment]
Can I work on this?
Can we use npm packages like gibberish-detector?

**Comment by tstreamDOTh** [comment]
@proishan11  Already working on it. Also, gibberish-detector doesn't give good results. I have tried it. It is giving unreliable results.

**Comment by proishan11** [comment]
@tstreamDOTh I thought this issue isn't assigned to anyone. Keep up the good work.

**Comment by flaredragon** [comment]
Is it done? can I work on it? I think there can be a time based call on it(after certain seconds of searching if not found default is returned) OR If some results are found somewhat relevant from a search engine a link can be provided for the result.

**Comment by tstreamDOTh** [comment]
@flaredragon The problem to solve is identifying the gibberish text

**Comment by tstreamDOTh** [comment]
This has to be done on the server side.
