### ISSUE TITLE
the language of the options in menu list button(on right side top) changes after login and changing of theme colors

### ISSUE THREAD

**Issue by nileshgulia1** [fossasia/chat.susi.ai#828]
**Actual Behaviour**

the languages are changed .

**Expected Behaviour**

The language should be english

**Steps to reproduce it**

1.Login
2.change theme colors multiple times and see the menu options

![screenshot from 2017-09-25 01-51-48](https://user-images.githubusercontent.com/22280901/30786491-312e2570-a194-11e7-9f6e-806e3d1e0995.png)
 #####  may be I can fix the issue.can i work on this?

**Comment by madhavrathi** [comment]
We have similar issue already: https://github.com/fossasia/chat.susi.ai/issues/791
Please provide your inputs there. Thanks
