### ISSUE TITLE
Custom server element should come to center of the dialog

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#829]
**Actual Behaviour**

Custom server element has misaligned 

**Expected Behaviour**

Custom server element should come to center of the dialog

**Screenshots of the issue**

<img width="459" alt="screen shot 2017-09-25 at 4 59 24 pm" src="https://user-images.githubusercontent.com/7692626/30806380-3412d220-a213-11e7-9ebf-bb26e8d6c45c.png">

**Would you like to work on the issue?**

no

**Comment by RMCoder198** [comment]
@isuruAb 
![custom](https://user-images.githubusercontent.com/26675957/30811508-0f0f5d8c-a226-11e7-880d-1baefa42be0e.png)
its looking good.

**Comment by isuruAb** [comment]
@RMCoder198  zoom out it some more. you will see the issue.

**Comment by Remorax** [comment]
Is this fine @isuruAb?
![screen shot 2017-09-25 at 11 38 41 pm](https://user-images.githubusercontent.com/26062692/30823695-b91ee9fe-a24a-11e7-927d-ff9f0f54fe98.png)

**Comment by isuruAb** [comment]
@Remorax that's good .check it in different screen sizes as well

**Comment by Remorax** [comment]
Here are screenshots in 2 other sizes:
![screen shot 2017-09-25 at 11 55 52 pm](https://user-images.githubusercontent.com/26062692/30824532-73692ffc-a24d-11e7-938a-2feaf611fbed.png)
![screen shot 2017-09-25 at 11 58 26 pm](https://user-images.githubusercontent.com/26062692/30824533-736c5290-a24d-11e7-807c-ee75ef75badc.png)
It seems to work fine. Can I make a pull request?

**Comment by isuruAb** [comment]
@Remorax  sure do it
