### ISSUE TITLE
Some appearance changes in the 'Connect to SUSI Hardware' tab in Settings

### ISSUE THREAD

**Issue by Remorax** [fossasia/chat.susi.ai#830]
**Actual Behaviour**

In the Connect to SUSI Hardware tab in Settings, the 'Add address to connect to hardware' is too much to the left and is in caps, just like the title. Also, on clicking it, the popup has a different font for the title than the rest of the site, and the 'connect' button needs to be given some padding.
![screen shot 2017-09-26 at 1 22 09 am](https://user-images.githubusercontent.com/26062692/30827863-35cb39d6-a259-11e7-834a-c5c6323a5327.png)
![screen shot 2017-09-26 at 1 22 20 am](https://user-images.githubusercontent.com/26062692/30827868-3c0361e8-a259-11e7-8fe4-a84bf8ef4836.png)

**Expected Behaviour**

The styling should be done as given in the following two screenshots:
![screen shot 2017-09-26 at 12 58 41 am](https://user-images.githubusercontent.com/26062692/30829347-28f573de-a25e-11e7-9174-8d2ac57e33dd.png)
![screen shot 2017-09-26 at 1 13 19 am](https://user-images.githubusercontent.com/26062692/30829358-32b0098e-a25e-11e7-9ccd-c868861854dd.png)

**Steps to reproduce it**

1. Go to Settings
2. Go to Connect to SUSI Hardware tab.
The 1st issue is evident here.
3. Click on the 'Add address to connect to hardware' link
The 2nd issue can be seen in the dialog box.

**Would you like to work on the issue?**

Yes, I would like to work on it. Please check the screenshots, and let me know if it can be made better.

**Comment by Remorax** [comment]
@madhavrathi @isuruAb Please review.

**Comment by rishiraj824** [comment]
closing as fixed via #834
