### ISSUE TITLE
App returns redundant pages

### ISSUE THREAD

**Issue by anshumanv** [fossasia/chat.susi.ai#837]
**Actual Behaviour**

For queries when susi has to scrape the web and aggregate links, It sometimes returns redundant pages which have different links.

**Expected Behaviour**
No redundant pages should be displayed

**Steps to reproduce it**
Type in 'Cristiano Ronaldo'

**Screenshots of the issue**

![susi](https://user-images.githubusercontent.com/21009455/30950099-302ff9fe-a438-11e7-9a6a-871b3cb73b53.PNG)

**Would you like to work on the issue?**

Should be assigned to anyone who wishes to fix this.

**Comment by newbazz** [comment]
i would like to work on this..

**Comment by anshumanv** [comment]
Please send a PR.

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/31252272-33a3f530-aa10-11e7-9f72-a2849acbaa74.png)
It displays the given error...

**Comment by zamhaq** [comment]
@newbazz @anshumanv I would like to work on it if you are not.

**Comment by newbazz** [comment]
@zamhaq u can continue I am busy with my exams presently

**Comment by anshumanv** [comment]
@zamhaq please go ahead 👍

**Comment by zamhaq** [comment]
@anshumanv  @newbazz Putting this issue on hold for now since `web search` type responses are down.
