### ISSUE TITLE
Avoid unnecessary API calls

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#838]
Loading the web UI shows that the Google Translate API gets called. Please avoid an integration with other services and take out the API call.

Also avoid calling Google web fonts. Instead add fonts locally.

Check out if any other external API calls are made for no reason and remove them.

**Comment by zamhaq** [comment]
@mariobehling I would like to work on this.

**Comment by zamhaq** [comment]
@madhavrathi @mariobehling can anyone help with deployment to surge? I tried deploying at hallowed-branch.surge.sh but this gives 404.

**Comment by madhavrathi** [comment]
@zamhaq set your upload path to build folder. That should do the thing. Pls send screenshot if error still persists.

**Comment by isuruAb** [comment]
@zamhaq  can we close this issue ?

**Comment by zamhaq** [comment]
@isuruAb I removed the calls the `gtranslate` but I could not find the source calling `web fonts`.
