### ISSUE TITLE
SUSI does not show the answer until we ask another question 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#84]
I have tried with several questions.it does not show the answers until we ask another question.
<img width="781" alt="screen shot 2017-05-19 at 9 50 31 pm" src="https://cloud.githubusercontent.com/assets/7692626/26257190/4d258226-3cdd-11e7-8b80-8d1b0d6540ff.png">
 
after we ask another question it suddenly show the answer for previous question like this.
<img width="819" alt="screen shot 2017-05-19 at 9 52 42 pm" src="https://cloud.githubusercontent.com/assets/7692626/26257265/8f1da3ca-3cdd-11e7-94e0-0377e808a966.png">

**Comment by rishiraj824** [comment]
Will work on this :+1:
