### ISSUE TITLE
Restructure settings area, avoid popups, ensure same colors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#840]
The settings area has grown organically. It is time to align it closer to other existing services.

* Please re-arrange items in the settings tab following the Twitter settings page structure, e.g. add a tab "Password" and a tab "Account" that shows the email of the user.
* Ensure all buttons use the same blue color, e.g. in theme tab
* If "Dark" theme or other theme options are chosen, please also use it in the settings area.

![screenshot from 2017-09-28 10-36-32](https://user-images.githubusercontent.com/1583873/30957108-8e3af7d2-a439-11e7-99ab-0453e0408671.png)

**Comment by hkedia321** [comment]
I will work on it :+1:

**Comment by isuruAb** [comment]
@hkedia321 how is the progress of this issue ?

**Comment by hkedia321** [comment]
@isuruAb I am working on this, restructuring is done. Changing color is left. Will send a PR in a day 👍
