### ISSUE TITLE
Bugs in Settings after saving the state

### ISSUE THREAD

**Issue by Remorax** [fossasia/chat.susi.ai#841]
**Actual Behaviour**

There are two main issues with the save button and the settings page:
1. On pressing save, the user is not redirected to the home page
2. The option being changed, although updated internally, is not reflected when I hit save. For example. if I change the theme to "dark", even after pressing the save button, the "light" radio button is selected.  This issue of the old state being shown happens for ALL the tabs in Settings, not just the theme tab. The only way for the user to actually verify that the change has taken place is to go to the homepage manually. Sometimes, in some cases, refreshing the Settings page, shows the new value but not by default.

**Expected Behaviour**

1. The user should be redirected to the homepage.
2. The changed state should be reflected on clicking save.

**Steps to reproduce it**

1. Go to Settings
2. Click on say, the Theme tab or the ChatApp Settings Tab.
3. Change the value and click Save.
4. The user is not redirected to the homepage and the old values are being displayed.

**Screenshots of the issue**

Initial State:
![before](https://user-images.githubusercontent.com/26062692/31032998-1b0d5752-a57c-11e7-9293-6827cd9e473e.PNG)

Just before clicking the Save button:
![middle](https://user-images.githubusercontent.com/26062692/31033007-1f4fd48e-a57c-11e7-8f28-a8c2a09fb6c7.png)

After clicking save:
![final](https://user-images.githubusercontent.com/26062692/31033019-3020757a-a57c-11e7-8d83-9fd632f39b07.PNG)

**Would you like to work on the issue?**

Yes, I would like to work on the issue, but since it is a relatively big issue, I would be requiring some guidance. Thanks :)

**Comment by hkedia321** [comment]
The user remains on the settings page, this is a feature recently added(see #836 ).
 These bugs are known and will be fixed in #840.

**Comment by isuruAb** [comment]
hello @Remorax , how is the progress of this issue ?

**Comment by Remorax** [comment]
I thought @hkedia321 was handling this?
