### ISSUE TITLE
SUSi doesn't respond to some basic words with obvious answers.

### ISSUE THREAD

**Issue by lavi061997** [fossasia/chat.susi.ai#844]
**Actual Behaviour**

I entered 'date' in the text field and it responded with some images from the internet that are irrelevant.

**Expected Behaviour**

it should display today's date.

**Steps to reproduce it**
Enter "date","time" in chat.

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by rishiraj824** [comment]
@lavi061997 Thank you for you to point this out. This issue can be worked out on this skill https://skills.susi.ai/Productivity/calendar/en It would be great if you could add the queries there. Thank You.

**Comment by rishiraj824** [comment]
closing as not a part of the client.
