### ISSUE TITLE
Can we use Semantic UI for this project

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#85]
Semantic UI already has a lot of components we could use. Please check if we can use it.

https://semantic-ui.com/

**Comment by rishiraj824** [comment]
@mariobehling I think we can, but the components will look similar to the current one on http://chat.susi.ai/chat
We can definitely proceed with this if there's no problem with that. Or the second option can be the Android UI mentioned at https://github.com/fossasia/chat.susi.ai/issues/69

**Comment by isuruAb** [comment]
Semantic UI is good but it's components are just like normal UI elements. here they compare bootstrap , material ui and semantic web https://stackshare.io/stackups/bootstrap-vs-material-ui-vs-semantic-ui
here they have compared material UI and semantic UI:  https://www.slant.co/versus/520/521/~semantic-ui_vs_materialize

**Comment by BrainBuzzer** [comment]
Semantic UI comes with great theming support. You can customize almost every single bit of a semantic UI theme. Leave that to me.

**Comment by isuruAb** [comment]
this can be closed because now we are using material-UI as our UI library
