### ISSUE TITLE
Slider not smooth 

### ISSUE THREAD

**Issue by harsh-98** [fossasia/chat.susi.ai#850]
When the AI searches for the query on web and outputs the result in slider. The slider is not smooth when it comes to the end of the list it kind of jiggles.And in the light theme, the buttons for the slider are not of the best color to be visible.

I would like to work on this issue.

**Comment by shreyanshdwivedi** [comment]
@harsh-98 can I work on this?

**Comment by harsh-98** [comment]
@shreyanshdwivedi  proceed

**Comment by shreyanshdwivedi** [comment]
@harsh-98 can you please provide methods to reproduce it or any small video?
