### ISSUE TITLE
Make map zoomable only after clicking

### ISSUE THREAD

**Issue by nifey** [fossasia/chat.susi.ai#856]
**Actual Behaviour**

When we are scrolling the messages container using the mouse scroll wheel, if there is a map element in between the map starts zooming instead of scrolling the messages container.

**Expected Behaviour**

It could be better if the map zooms after we click on it. After the mouse cursor moves out of the map, the zooming of the map should stop and instead the message container should be scrolled.

**Would you like to work on the issue?**

No

**Comment by nileshgulia1** [comment]
hey @nifey , When After the mouse cursor moves out of the map, the zooming is normal.but when  it hovers on the map ,the map itself starts zooming in and out.I think it is initially made good.still it needs improvement?

**Comment by nifey** [comment]
@nileshgulia1 for times when we want to scroll to the very top , if there is a map in between , it slows down the scrolling. Every time there is a map message we have to move the cursor out of the map and continue scrolling to reach the top.

**Comment by nileshgulia1** [comment]
@nifey .So u are telling when we scroll through the messages, onhovering mouse on map it zooms automatically.fine, I think it needs some more discussion by members because i find it the initial UX proposed on chat.

**Comment by tstreamDOTh** [comment]
I would like to work on this
