### ISSUE TITLE
First time view have not  welcome message or introduction

### ISSUE THREAD

**Issue by lwinkyawmyat** [fossasia/chat.susi.ai#859]
## **Actual Behaviour**

For the first time visitors can't found welcome message or introduction message.

## **Expected Behaviour**
Should add some message for first time visitors on message board.

## **Screenshots of the issue**
![screenshot-2017-10-15 web chat with susi ai - open source personal assistant](https://user-images.githubusercontent.com/13135332/31581784-f5316c98-b198-11e7-87c8-7d39747f0890.png)

## **Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by nileshgulia1** [comment]
Hey @ubatin  , I don't understand the issue ,shall we add a popup window showing welcome message or a introduction tag in menu?please elaborate it.

**Comment by VibhorCodecianGupta** [comment]
I think the issue here is that there should be a welcome message for a first time user. Something like 'Ruuh' does when you initiate a conversation with her.

**Comment by lwinkyawmyat** [comment]
I would like to work when I'm free.

**Comment by xprilion** [comment]
Hi! Can I work on the issue?

**Comment by isuruAb** [comment]
working on it
