### ISSUE TITLE
UI improvements in Login screen

### ISSUE THREAD

**Issue by hkedia321** [fossasia/chat.susi.ai#861]
**Proposed changes**
- Change the font of "Login to SUSI"
- Change the input type of email field from `text'` to `email`
- Remove the default orange background of text fields in Chrome browser
- Show loading status while logging in.
**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/17807257/31587788-54f7325e-b205-11e7-8d9b-1f5608c92fc8.png)

**Would you like to work on the issue?**
 Yes

**Comment by hkedia321** [comment]
@mariobehling @isuruAb @rishiraj824  Anything more required in order to close this issue?

**Comment by rishiraj824** [comment]
closing via #876
