### ISSUE TITLE
Dark theme does not show it's background colour

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#862]
**Actual Behaviour**

Dark theme does not show it's background colour

**Expected Behaviour**

It should show It's background colour 

**Screenshots of the issue**

<img width="1280" alt="screen shot 2017-10-16 at 10 27 47 am" src="https://user-images.githubusercontent.com/7692626/31596001-20d4c772-b25d-11e7-9858-a7413be9816e.png">

**Would you like to work on the issue?**

anyone can get this

**Comment by zamhaq** [comment]
@isuruAb I would like to work on this.

**Comment by saurabh30** [comment]
@zamhaq are you still working on  this issue?

**Comment by zamhaq** [comment]
@isuruAb @madhavrathi @rishiraj824 how can I find which functions are registered for a dispatcher? I want to find the function registered for chatappdispatcher which waits for the settingsChanged payload

**Comment by zamhaq** [comment]
@isuruAb I tried to find where the default settings for themes is defined. In the settings component, it only chooses between `dark` or `light` theme which then calls implementsettings to implement the change settings. But where are the settings defined for `dark` or `light` theme? I could not find that settings if we do custom theming then we are able to change `body` colour. But that component shows as `DialogInline` and I could not find any dialogInline components. Please guide me on where do I find the theming settings.

**Comment by Remorax** [comment]
I'm working on this due to inactivity. Should fix #889 also :)

**Comment by ParthS007** [comment]
@Remorax #889 is for GCI students, You can work on other Open Issues 👍

**Comment by ParthS007** [comment]
@isuruAb Please close this issue as It will be resolved in #889

**Comment by Remorax** [comment]
Um, okay cool @ParthS007. Its' just there are three issues on the same bug, and they've been inactive for over a month now.
