### ISSUE TITLE
Enable Theming Personalization/Branding of the chat interface for a persona

### ISSUE THREAD

**Issue by Orbiter** [fossasia/chat.susi.ai#866]
**Actual Behaviour**

The chat interface is branded as "SUSI".

**Expected Behaviour**

For special situations, we want to have the front-end branded with custom icons and other things (headlines, description etc)

**Steps to reproduce it**

A test persona is available currently only as a susi dream, especially as the nefertiti dream.
To activate this, call https://api.susi.ai/susi/chat.json?timezoneOffset=-120&q=dream+nefertiti

Then, the json response has a new `persona` object inside the`answers` array:

```
"answers": [{
    "data": [...],
    "actions": [...],
    "skills": ["/susi_server/file:/nefertiti"],
    "persona": {"skill": {
      "image": "http://nefertitihack.alloversky.com/img/Nefertiti-front-3D-wweb.jpg",
      "skill_name": "Nefertiti",
      "author": "Jan Nikolai Nelles, Nora Al-Badri",
      "author_url": "http://nefertitihack.alloversky.com/",
      "dynamic_content": false
    }}
  }],
```

The `persona` object will carry numerous objects inside in the future, i.e. also the current emotional state of the bot. But right now, there is only a `skill` object. That skill object has optionally an image link inside. If it is there, the image must be rendered .. somehow.

**Comment by Orbiter** [comment]
@mariobehling we must clarify how this should look like in detail. You can see in the persona.skill object which kind of information is now there available.

**Comment by mariobehling** [comment]
@Orbiter I think we need a complete theming. We already have that except for the logo.
