### ISSUE TITLE
Images are not persistently saved in theme

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#868]
On the right hand dropdown there is an option "themes". Filling in image links works, but as soon as the user chats again, the image disappears.

![screenshot from 2017-10-20 19-25-18](https://user-images.githubusercontent.com/1583873/31834134-46925916-b5cd-11e7-881d-6a141fa0528a.png)

**Comment by akshatnitd** [comment]
Working on it :+1:
