### ISSUE TITLE
Improve themes area interaction

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#869]
Please change as follows:
* Change all text from "Change color of.." to "Color of..."
* If color of an area becomes too bright automatically change color of font to dark gray color (and if color becomes too dark automatically change it to white)
* In front of "Save" button add "Reset" to set colors to standard colors of SUSI.AI
* Delete "Done" button

![screenshot from 2017-10-20 19-25-18](https://user-images.githubusercontent.com/1583873/31835359-8a2ed6b4-b5d1-11e7-8334-89d82cd55048.png)

**Comment by tstreamDOTh** [comment]
I would like to work on this
