### ISSUE TITLE
"Connect to SUSI Hardware" and "Mobile" titles interchanged in Settings

### ISSUE THREAD

**Issue by Remorax** [fossasia/chat.susi.ai#873]
**Actual Behaviour**

When the user goes to Settings and clicks on the Mobile tag after clicking the connect to SUSI Hardware tab or vice versa, the title of the previous tab remains.

**Expected Behaviour**

The title of the selected tab should be shown.

**Steps to reproduce it**

1. Go to Settings.
2. Click on the Mobile tab. Works fine.
3. Now, click on the Connect to SUSI Hardware tab. The title is still "Mobile" only.
4. Clicking on some other tab apart from these two, and then clicking the "Connect to SUSI Hardware tab" makes it alright.
5. This bug is also there when one clicks on the "Connect to SUSI Hardware" tab first and mobile later.

**Screenshots of the issue**

![screen shot 2017-10-21 at 4 00 45 pm](https://user-images.githubusercontent.com/26062692/31850917-21df9776-b679-11e7-8f99-dd13d3a9e4d3.png)
![screen shot 2017-10-21 at 4 00 53 pm](https://user-images.githubusercontent.com/26062692/31850918-221548da-b679-11e7-859a-e19671a90903.png)
![screen shot 2017-10-21 at 4 01 00 pm](https://user-images.githubusercontent.com/26062692/31850919-2248e5f0-b679-11e7-99f1-8cda21356b37.png)
![screen shot 2017-10-21 at 4 01 08 pm](https://user-images.githubusercontent.com/26062692/31850920-227c4b5c-b679-11e7-85f3-be6d61600490.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by anshumanv** [comment]
@Remorax are you still working on this?
If not, I'd like to fix this.

**Comment by Remorax** [comment]
I'm working on this again @anshumanv. I'll be making a PR shortly :)

**Comment by anshumanv** [comment]
Okay cool, GFI @Remorax :smile:
