### ISSUE TITLE
"Get me a MEME" produces no image

### ISSUE THREAD

**Issue by gabru-md** [fossasia/chat.susi.ai#878]
**Actual Behaviour**

Gives answer instead of image.

**Expected Behaviour**

Should produce image as an answer
**Steps to reproduce it**

- Go to chat.susi.ai
- Enter "show me a meme"
- See the result

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![sm](https://user-images.githubusercontent.com/25414121/32140640-e2d9c3c4-bc8d-11e7-8524-b74f9692b290.JPG)

**Would you like to work on the issue?**

No as of now. This issue is free for anyone to claim.

**Comment by engrravijain** [comment]
i would like to work on the issue. can i start working with it ?

**Comment by gabru-md** [comment]
Yes you may

**Comment by engrravijain** [comment]
sure, i'll start working on it then @gabru-md

**Comment by aashutoshrathi** [comment]
Isn't this issue a duplicate of #803

**Comment by gabru-md** [comment]
I had no idea that this issue was already present. Thanks for bringing to my notice. Closing this then

**Comment by anshumanv** [comment]
Good find @aashutoshrathi :smile:
