### ISSUE TITLE
Custom theme colours do not change to default colours when user clicks the close button

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#879]
**Actual Behaviour**

Custom theme colours do not change to default colours when user clicks the close button

**Expected Behaviour**

It should change to previously selected colour theme when user clicks on the close button (when user does not need to save selected theme information)

**Steps to reproduce it**

login > select custom theme colours > click close button of custom theme colour dialog box

**Would you like to work on the issue?**

anyone can get it

**Comment by hkedia321** [comment]
I would like to work on this :+1:
