### ISSUE TITLE
Need improvement in Login Popup

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#882]
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/21199234/32361397-e2098f46-c085-11e7-837f-678dc9aa060c.png)

**Expected Behaviour**

We need proper spacing around `signup or chat anonymously` block.

**Steps to reproduce it**

We need to make changes in Login.react.js and fix proper spacing and margins.

**Would you like to work on the issue?**

No

**Comment by saurabh30** [comment]
@aashutoshrathi  I would like to work on this issue.

**Comment by aashutoshrathi** [comment]
GFI @saurabh30

**Comment by anshumanv** [comment]
@aashutoshrathi Update in issue body (last sub-heading) that you are not working so you don't get assigned by mistake.

**Comment by saurabh30** [comment]
@aashutoshrathi  please review and guide me further.I'm first-timer.

**Comment by aashutoshrathi** [comment]
Solved
