### ISSUE TITLE
Table response not displaying data

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/chat.susi.ai#883]
**Actual Behaviour**

Table response not working

**Expected Behaviour**

Show table

**Steps to reproduce it**

Ask "Universities in malaysia" 

**Screenshots of the issue**

![screen shot 2017-11-03 at 9 01 07 pm](https://user-images.githubusercontent.com/11137394/32382018-4285e6f4-c0da-11e7-9551-b672c80da1e8.png)

**Would you like to work on the issue?**
Yes

**Comment by shreyanshdwivedi** [comment]
@tstreamDOTh I would like to work on this. Can I?

**Comment by saurabh30** [comment]
@tstreamDOTh  please close this issue this has been fixed. There was problem in skill defination which I had corrected.
Screenshot
![image](https://user-images.githubusercontent.com/13045373/34945277-ce4faddc-fa28-11e7-8781-3f8dd8357871.png)

**Comment by tstreamDOTh** [comment]
Resolved 👍
