### ISSUE TITLE
Enhance dark theme

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/chat.susi.ai#889]
**Actual Behaviour**
Dark theme is not implemented correctly. There are bugs in it.

**Expected Behaviour**

1. Apply dark theme properly in the settings page.
2. Button colours must match the theme.
3. The active state of a link must have a suitable colour.
4. Make cursor type pointer for "Save changes" button. Currently, it looks like a disabled button.
5. Make table response suit the dark theme.

**Screenshots of the issue**
![screen shot 2017-11-04 at 10 39 34 pm](https://user-images.githubusercontent.com/11137394/32412208-635e941a-c216-11e7-9f64-bf5d62b587ba.png)

**Would you like to work on the issue?**
Yes

**Comment by ParthS007** [comment]
Any updates @tstreamDOTh. Can I start working on this?

**Comment by tstreamDOTh** [comment]
@ParthS007  putting this for GCI task

**Comment by jajodiaraghav** [comment]
Can this issue be claimed by a non GCI participant?

**Comment by ParthS007** [comment]
@rishiraj824 Please add a GCI label to this task and close other Dark Theme related Issue. Thanks 👍

**Comment by rishiraj824** [comment]
okay @ParthS007
