### ISSUE TITLE
SUSI doesn't respond to messages that it doesn't understand

### ISSUE THREAD

**Issue by ArmenGabrielyan16** [fossasia/chat.susi.ai#891]
**Actual Behaviour**

SUSI doesn't respond to messages that it doesn't understand. This includes not only unmeaningful texts like "sagggdshdfh", but also meaningful texts like "universities in us".

**Expected Behaviour**

SUSI should give some response.

**Steps to reproduce it**

Please, try the cases mentioned in screenshots.

**Screenshots of the issue**

![issue2](https://user-images.githubusercontent.com/25867263/32414872-f209bb22-c248-11e7-9dfc-51de7e19ae0b.png)
![issue](https://user-images.githubusercontent.com/25867263/32414873-f2300688-c248-11e7-854b-c5d3fa108390.png)

**Would you like to work on the issue?**

Yes. I would appreciate guidance from maintainers.

**Comment by mariobehling** [comment]
This issue should be solved on the server.
