### ISSUE TITLE
Add Armenian Localization

### ISSUE THREAD

**Issue by ArmenGabrielyan16** [fossasia/chat.susi.ai#892]
I think translating SUSI into other languages will make it more popular. As Armenian is my native tongue, I will add Armenian Localization.

**Would you like to work on the issue?**

Yes

**Comment by daminisatya** [comment]
@ArmenGabrielyan16 Assigned the issue to you

**Comment by anshumanv** [comment]
Merged in #897, this can be closed now. :smile:
