### ISSUE TITLE
Globalise the translate function based on the text language selection

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/chat.susi.ai#895]
**Actual Behaviour**

Currently new language files(json files) inside the Translate folder cannot be used in the SUSI Web Chat.

**Expected Behaviour**

Make a global function to choose the language file according to the text language setting.

**Steps to reproduce it**

In Translate.react.js, the search method is hardcoded for only German language, one needs to add support for the selected language to make sure all language files are fetched accordingly as per the selection and the corresponiding text is returned.
```
if(defaultPrefLanguage!=='en-US'){
      for (let key=0;key<arrDe.length;key++) {
          if (arrDe[key]===text) {
              this.changeLanguage(de[arrDe[key]]);
          }
        }
    }
```

**Would you like to work on the issue?**
Anyone can take it up. Can be done as a GCI Task too.

**Comment by tstreamDOTh** [comment]
Would like to work on it

**Comment by arnav-mandal1234** [comment]
can I take this issue?

**Comment by Remorax** [comment]
I would like to work on this, I'll be making a PR soon :)

**Comment by 0x48piraj** [comment]
Please close this issue @rishiraj824

**Comment by akshatnitd** [comment]
We already have a translate function.
