### ISSUE TITLE
Closing Custome Theme Modal switches dark theme back to light theme

### ISSUE THREAD

**Issue by zamhaq** [fossasia/chat.susi.ai#896]
**Actual Behaviour**
When in Dark Theme, Closing the custom theme modal results in switches back into the light theme.

**Expected Behaviour**
Should not switch light theme and stay in dark theme since no settings were changed.

**Steps to reproduce it**
1. Choose dark theme.
2. Open the dropdown from chatapp home and select theming for custom theme modal to appear.
3. Once modal is opened, close the modal.

**Screenshots of the issue**
![chat susibug](https://user-images.githubusercontent.com/20766601/32511690-861a9dd6-c41a-11e7-9d1b-29d909b2eeb1.gif)

**Would you like to work on the issue?**
Yes.

**Comment by ParthS007** [comment]
any updates @zamhaq?

**Comment by ParthS007** [comment]
I think it will be covered in #889

**Comment by zamhaq** [comment]
@ParthS007 if it does, then great. Otherwise, I am working on this one.

**Comment by Remorax** [comment]
Working on this due to inactivity.
