### ISSUE TITLE
Thumbs up and down UI improvement

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#898]
**Actual Behaviour**

Its buggy and doesn't work sometimes, also we the color of both are blue as defined in README

**Expected Behaviour**

We can fix its working and also color can be changed as in screenshots

**Steps to reproduce it**

Change color code for the dislike button to red and fix, not working problem and also add color entry to README.

**Screenshots of the issue**

![red-b](https://user-images.githubusercontent.com/21199234/32629407-1a412318-c5bf-11e7-9652-b20a7d25e79e.JPG)
![blue-b](https://user-images.githubusercontent.com/21199234/32629408-1a887358-c5bf-11e7-90b6-88b002eb5a80.JPG)

**Would you like to work on the issue?**

No

**Comment by ParthS007** [comment]
I want to work on this @aashutoshrathi

**Comment by aashutoshrathi** [comment]
GFI @ParthS007 make sure you fix it.

**Comment by ParthS007** [comment]
I am new to it , will try my best and let you know if I am facing any difficulty .

**Comment by aashutoshrathi** [comment]
👍 Ping here or PM on Gitter in case some help is needed 😄
