### ISSUE TITLE
Add Back button to forgot password window

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#899]
**Actual Behaviour**

Once you click forgot password, there is no going back (Screenshot)

**Expected Behaviour**

Add a back button which leads back to login menu from forgot password panel

**Steps to reproduce it**

Add a back button and give it form link

**Screenshots of the issue**

![fg-bug](https://user-images.githubusercontent.com/21199234/32642543-f8bce4a2-c5fa-11e7-99f2-3ce0d7b17049.JPG)

**Would you like to work on the issue?**

No

**Comment by anshumanv** [comment]
Working on this.

**Comment by aashutoshrathi** [comment]
Already an issue? @anshumanv

**Comment by anshumanv** [comment]
Fixed in #901
