### ISSUE TITLE
Using the Telegram chat services into Susi

### ISSUE THREAD

**Issue by daminisatya** [fossasia/chat.susi.ai#9]
## The current feature list supported by Susi

The current template is being developed using Handlebars and JQuery. It as a pretty good User Interface with the following features.
- The words are broken according to the text length and there is no overflow out of the message bubbles. 
- The keyboard events are triggered well with `enter` and `shift+enter`.
- There is not problem with getting the responses quickly - The interface is loading quickly. 
## What is lacking with the current template?
- The User Interface is not responsive to device and this requires a lot of effort to make it work on all browsers. 
- Currently it does not support `Emojis`, other keyboard events like `scroll up` and `scroll down`. 
- It doesn't support other media like videos, photos, and other files. 
## What improvements we can make on using Telegram. (which are useful for Susi)
- The UI is perfect and has two optional view which are for mobiles as well as desktop. 
- It has some necessary options like desktop notifications 
- Creating groups 
- Emoji support, deleting the messages. 
- This can be easily integrated with loklak_depot in future because of the technology stack(AngularJS)
## What can we do with the current template?
- We can integrate Susi by muting few features. We must make the contact addition one way and by default Susi will be in the contact.

**Comment by mariobehling** [comment]
How about all those account features? The goal define by @Orbiter is also to add accounts to Susi. How could we integrate this with loklak_depot?

**Comment by daminisatya** [comment]
Currently Telegram supports login through phone numbers, In place of that we can have the loklak_depot and them redirect to the asksusi page. 
![selection_218](https://cloud.githubusercontent.com/assets/6227784/17019647/fca7065a-4f5a-11e6-999e-1df83587abdf.png)

Another advantage is the code base is in Angular which syncs up with the loklak_depot code. 
This is what i had interpreted. For the thorough implementation of accounts part, I need to go through the code once.

**Comment by mariobehling** [comment]
@daminisatya A clear idea how to connect with the Angular accounts part is important as we would meet this question later anyways. If this would have complications, it might be a reason to consider implementing AskSusi with Angular as well and work on the same stack.

**Comment by daminisatya** [comment]
@sudheesh001 @mariobehling @Orbiter @shivenmian  I initially denied on converting the whole structure to Telegram. If porting to angularJS is importing, I need someone to help me to get this done. Telegram has a very vast codebase, which eventually leading to a slower progress. It highly convoluted, and cannot be done all alone, forming a team and breaking down the code into pieces can make it easier to explore and make the changes. 

* It has many modules like adding contact, contact details, blocking contact, importing contacts in bulk, self profile details which are connected to the login cred. 
* When coming to messaging pattern, we can delete, mark it as read, unread, archive, send emojis and all. All these are inter connected for a two way communication, where we need to block the other side and make Susi as the only contact . Not only that the plan was to have a group creation and group chat, which means we have multithread handling with the other added contacts. 
* Integrating Susi is easy and straight forward for the existing template, but we need to make sure the connections are not overlapping with the susi's in telegram. Making the UI changes is quite easy but adding the functionality is difficult that too from the existing code base.

**Comment by mariobehling** [comment]
It seems like using Telegram as a basis for the chat client is not useful therefore. It is too much work in the short time left. We would have expected this kind of insight 2 weeks ago.
