### ISSUE TITLE
react-hljs@1.0.0: Deprecated!

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#903]
**Actual Behaviour**

react-hljs is deprecated

**Expected Behaviour**

Replace it with alternatives

**Steps to reproduce it**

Use one of the countless alternatives instead:

https://github.com/bvaughn/react-highlight.js
https://github.com/akiran/react-highlight
https://github.com/chili-labs/react-fast-highlight
https://github.com/DylanPiercey/Syntux
https://github.com/conorhastings/react-syntax-highlighter

**Would you like to work on the issue?**

No.

**Comment by anshumanv** [comment]
I don't think that module is used anywhere in the code, I'll do this.

**Comment by aashutoshrathi** [comment]
@anshumanv we need to remove react-hljs anyway.
https://github.com/fossasia/chat.susi.ai/blob/adfc3064845f18578c25ca9ae3d4afe9f49888de/package.json#L36

**Comment by anshumanv** [comment]
By `I'll do this` I meant I'm gonna remove it. :smile:

**Comment by aashutoshrathi** [comment]
You are mentor, do whatever you like 😉 😛
