### ISSUE TITLE
Non functional 'Back to Login' button on the ForgotPassword dialog once opened from 'About' Page

### ISSUE THREAD

**Issue by anshumanv** [fossasia/chat.susi.ai#911]
**Actual Behaviour**

'Back to Login' button in https://chat.susi.ai/overview is not working

**Expected Behaviour**

The button should be functional.

**Steps to reproduce it**

Goto https://chat.susi.ai/overview and open ForgotPassword Dialog and click 'Back to Login' button.

**Would you like to work on the issue?**

Yes

**Comment by aashutoshrathi** [comment]
Please provide screenshot or GIF, about how it is not functional

**Comment by anshumanv** [comment]
I've given the steps to reproduce and that should suffice.

**Comment by aashutoshrathi** [comment]
Gotcha, nice catch!

**Comment by ParthS007** [comment]
any updates @anshumanv ?

**Comment by anshumanv** [comment]
I'm occupied in institute exams presently, I'll need more time.

**Comment by Remorax** [comment]
Taking this issue and making a PR due to inactivity :)

**Comment by anshumanv** [comment]
Was planning to add this as a GCI task. :sweat_smile: 
Thanks anyways @Remorax :smile:
