### ISSUE TITLE
Reset Password form improvements

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#912]
**Actual Behaviour**

Reset Password form have some bug regarding Email field, the Email is written as a test in the field.

![capture](https://user-images.githubusercontent.com/21199234/32838134-f734ad56-ca35-11e7-9af1-475364eecacc.JPG)

**Expected Behaviour**

Email should be the label of that field, not text.

**Would you like to work on the issue?**

No

**Comment by anshumanv** [comment]
Claiming

**Comment by akshatnitd** [comment]
@anshumanv Are you working on it ?

**Comment by anshumanv** [comment]
Yes @akshatnitd, I'll send a PR right after I'm done with my exams(in a few days).

**Comment by jajodiaraghav** [comment]
Can I work on this issue?

**Comment by anshumanv** [comment]
I'm working on this @jajodiaraghav :sweat_smile:
