### ISSUE TITLE
language translation is not working in chat.susi.ai

### ISSUE THREAD

**Issue by ParthS007** [fossasia/chat.susi.ai#913]
**Actual Behaviour**
Languages are not present in text language settings and when changing to Deutch it is showning mixed languages i.e Hindi & English.

**Expected Behaviour**

Languages which are added in chat.susi.ai should be there in translations and for e.g if we select Deutsch, it should be translated.

**Steps to reproduce it**

Change translation to Deutsch

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/24358501/32985126-8763d1d6-ccd9-11e7-9a96-8a53be745d81.png)

![image](https://user-images.githubusercontent.com/24358501/32985149-053aadd2-ccda-11e7-82bd-80c0a9ee5f92.png)

**Would you like to work on the issue?**
NO

**Comment by ParthS007** [comment]
I want to work on it but Please tell me how to proceed?

**Comment by akshatnitd** [comment]
I am working on it
