### ISSUE TITLE
Right Click works same as Left Click on Back to Login Button

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#920]
**Actual Behaviour**

When we right-click on Back to Login button in Forgot password area, it works same as left click, i.e. takes you back to login

**Expected Behaviour**

Right-click on that button should give normal right-click option, as on any element of webpage

**Steps to reproduce it**

- Click on Login
- Click on `Forgot Password?`
- Right click on `Back to Login` Button

**Would you like to work on the issue?**

No.

**Comment by anshumanv** [comment]
@aashutoshrathi please check the screenshot, I think it works fine for me?
If not, then I'd like to fix this.

![image](https://user-images.githubusercontent.com/21009455/33023711-0c4bbf66-ce2f-11e7-979c-52c6dad73f5a.png)

**Comment by anshumanv** [comment]
Ah, I got it. It happens when you do consecutive right clicks on it on short intervals. :smile:
