### ISSUE TITLE
Create `docs/deployment.md` to improve Deploy Documentation

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/chat.susi.ai#926]
**Actual Behaviour**

In the `docs`, no **Deploy Documentation** is there.

**Expected Behaviour**

Should have one!:smile:

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/5800726/33426215-14234fbe-d5e7-11e7-8e8c-8fb13e80ce0b.png)

**Would you like to work on the issue?**

**Yes!** _(It's a GCI task)_

**Comment by zamhaq** [comment]
@0x48piraj I think there is already this one on how to deploy to [surge](https://github.com/fossasia/chat.susi.ai/blob/master/README.md#how-to-deploy)?

**Comment by 0x48piraj** [comment]
Yes @zamhaq. There is a minimal "how-to".
But, the task says :

> Document deployment process in /docs folder in the project. Open an issue to create or improve documentation. First steps are to create text documentation, then students who are claiming this task after that are expected to improve it step by step, e.g. by adding screenshots, add screenshots, creating screencasts of the setup or making an asciinema for re* Share the link of youtube video of Project working locally.

**Comment by zamhaq** [comment]
@0x48piraj oh, ok then go ahead ☺️

**Comment by 0x48piraj** [comment]
@dynamitechetan @isuruAb @ParthS007 @anshumanv
I have done it 5 days ago :wink:

**Comment by 0x48piraj** [comment]
Closing this :+1:
