### ISSUE TITLE
Unnecessary console logs

### ISSUE THREAD

**Issue by DeveloperAlfa** [fossasia/chat.susi.ai#929]
**Actual Behaviour**

Unnecessary console logs (1 for each message by the user)

**Expected Behaviour**

No unnecessary console.logs

**Steps to reproduce it**
Open Inspector and start talking to susi. logs appear aas you send messages

**Screenshots of the issue**

https://ibb.co/mMeACw
https://ibb.co/fUtgKb

**Would you like to work on the issue?**

Yes assign to @developeralfa

**Comment by DeveloperAlfa** [comment]
Commit #931 fixes this, sent by @developeralfa

**Comment by rishiraj824** [comment]
closing as fixed
