### ISSUE TITLE
Only one of the talk by susi can be liked

### ISSUE THREAD

**Issue by DeveloperAlfa** [fossasia/chat.susi.ai#930]
**Actual Behaviour**

You can like only one message sent by susi(most recent only)

**Expected Behaviour**

The feature should also allow the user to like/dislike old messages

**Steps to reproduce it**

Talk to susi and send her about 2-3 messages. Try liking/disliking each of them

**Would you like to work on the issue?**
I might need assistance, but I will work on the issue.
Issue be assigned to @developeralfa

**Comment by abishekvashok** [comment]
Working on it, as @DeveloperAlfa is not doing it.
