### ISSUE TITLE
Document deployment to surge.sh

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/chat.susi.ai#932]
**Actual Behaviour**

SUSI AI can be deployed easily to surge.sh
The documentation is in the readme.md file.
Screenshots and other features are missing.

**Expected Behaviour**

Screenshots and additional documentation should be present.
Additionally the documentation cn be moved to a separate .md
file in /doc folder as it will be enhanced with screenshots, ascinema etc
by GCI students.

**Would you like to work on the issue?**

Yes, taking it up

**Comment by abishekvashok** [comment]
Wokring on it as part of GCI

**Comment by 0x48piraj** [comment]
@abishekvashok Good job!
I have also done it :+1: 
https://github.com/fossasia/chat.susi.ai/issues/926
It's a step-by-step task :wink:

**Comment by abishekvashok** [comment]
Fixed in #950
