### ISSUE TITLE
Allowing login through Facebook and Gmail credentials

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/chat.susi.ai#935]
**Actual Behaviour**

Only possible login is through credentials of susi.ai 

**Expected Behaviour**

To allow signing via facebook,google credentials

**Steps to reproduce it**
Facebook , google login API's

**Would you like to work on the issue?**

Yes.

**Comment by VibhorCodecianGupta** [comment]
What's the status of this issue? I'd like to work on this!

**Comment by stealthanthrax** [comment]
@VibhorCodecianGupta ,since this is the first time I am contributing to chat.susi.ai, I was trying to understand the code first.Now I will make PR resolving this issue soon 😄

**Comment by akshatnitd** [comment]
@stealthanthrax I am working on integrating Google login

**Comment by stealthanthrax** [comment]
@akshatnitd, I was working on it was just waiting for the reviewers to give their feedbacks on Facebook pr :smile:

**Comment by mariobehling** [comment]
Currently out of scope.
