### ISSUE TITLE
Dead Code in files of  chat.susi.ai/src/components/ChatApp 

### ISSUE THREAD

**Issue by garuna-m6** [fossasia/chat.susi.ai#945]
**Actual**

dead and repeated set of code present.

**Expected**
deletion of repeated code and careful removal of dead code ,  also rewriting sections (like theme, only two choices possibility , re-frame it for future purpose )

**Reference**
[Antipattern.pdf](https://github.com/fossasia/chat.susi.ai/files/1536200/Antipattern.pdf)

**Would you like to work on the issue?**

open

**Comment by Remorax** [comment]
I would like to work on this. Please assign it to me :)

**Comment by Remorax** [comment]
@garuna-m6 This issue looks a bit too general to me. Can you give any examples of dead code that you must have found before you opened this issue?

**Comment by garuna-m6** [comment]
@Remorax  yes the issue is a bit general , no specific path to solution but surely refactoring is needed .

**Instances selected**
![error2](https://user-images.githubusercontent.com/23234342/33773953-aac09bec-dc5f-11e7-8598-8638648b7fc6.png)
![error1](https://user-images.githubusercontent.com/23234342/33773954-ab38b6d6-dc5f-11e7-828c-c4400bdf6220.png)

- in error1 image , the code is just meant for 2 themes possible, thinking of future perspectives i believe that multiple themes may exist.
- in error2 image the code (as i interpreted it ), it means to get input from the user for the desired color but in theme preference only two options are there .
