### ISSUE TITLE
Move images in public folder into "images" in src folder

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#948]
All source files including images should be in the src folder.

**Comment by Remorax** [comment]
I would like to take this up :)

**Comment by marvin08** [comment]
@mariobehling I will do it. :+1:

**Comment by marvin08** [comment]
@Remorax May I create a PR as I am done with it?

**Comment by marvin08** [comment]
@Remorax May I create a PR as I am done with it?

**Comment by Remorax** [comment]
Oh, I didn't notice your comment. I was in the process of creating a PR myself :P

**Comment by marvin08** [comment]
@Remorax :+1:

**Comment by anshumanv** [comment]
@Remorax will you be sending another PR or can I send one? :smile:

**Comment by Remorax** [comment]
Sure, go ahead @anshumanv :)

**Comment by anshumanv** [comment]
Alright, thanks @Remorax :+1:

**Comment by anshumanv** [comment]
@mariobehling the scaffolding tool we use is create-react-app which has some restrictions attached. They expect all of the static files(which are copied directly while bundling the app) like favicon etc in the public folder and once we run `npm run build` to package a production build these files are directly copied to the `build` folder that is generated. So moving favicon to `src/images` isn't possible with the current version of CRA. For reference please see - https://github.com/facebookincubator/create-react-app/issues/585

**Comment by abishekvashok** [comment]
@anushmanv we could have pre compile script that we should run before npm install in the appjson which copies images to public folder for us and at last cleans up the folder, what do you think?

**Comment by anshumanv** [comment]
We can always go for such workarounds, but I'd suggest sticking to the one suggested by cra.

**Comment by abishekvashok** [comment]
> cra.

???

**Comment by anshumanv** [comment]
Create React App.

**Comment by abishekvashok** [comment]
@mariobehling status on this

**Comment by 0x48piraj** [comment]
I can work on this, the other way. **(Workaround)**
