### ISSUE TITLE
Add fallback reply whenever susi does not respond

### ISSUE THREAD

**Issue by xprilion** [fossasia/chat.susi.ai#951]
**Actual Behaviour**

Often Susi does not reply anything and the loading animation goes on indefinitely.

**Expected Behaviour**

Susi should reply something to keep the conversation going on. (like any human would when she fails to understand the talk)

**Steps to reproduce it**

Randomly Susi goes blank in the chat. Keep hitting messages and once it will.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/7047208/33808998-97f70552-de15-11e7-9b2c-e2d26d030a27.png)

**Would you like to work on the issue?**

Yes I will like to work on the issue.

**Comment by smokingwheels** [comment]
Cool.  
Could you incorporate processing power into fallback time equation?
[http://www.binarytides.com/linux-cpu-information/](http://www.binarytides.com/linux-cpu-information/)

**Comment by xprilion** [comment]
I guess an easier solution would be:

let T = fallback time = 5s initially.

1. When the user starts chatting, if the first reply hangs, we do a fallback response after time T
2. With each response the user gets, we average the time taken for each response and reduce/increase T gradually (depending on if the user is getting quick replies or late replies (slow connection))
