### ISSUE TITLE
Implement info/error page for users of Internet Explorer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#959]
Users of Internet Explorer are seeing a blank page on http://chat.susi.ai/overview. Please implement an error page that only shows up for users of Internet Explorer.

**Comment by maxswjeon** [comment]
Should http://chat.susi.ai/overview return 404? In Chrome, it is a well-served page. But in Network it says it returned 404. It can be the problem of this I think

**Comment by Remorax** [comment]
I would like to work on this :)

**Comment by abishekvashok** [comment]
@Remorax can I work on it? Or are u working.

**Comment by Remorax** [comment]
No, go ahead @abishekvashok

**Comment by arnav-mandal1234** [comment]
can I take this? @abishekvashok

**Comment by abishekvashok** [comment]
This hting is passing out, if u want sure then go ahead @arnav-mandal1234

**Comment by 0x48piraj** [comment]
@mariobehling 
As A week has past till last activity, I'm starting to solve this :+1: 

I found that not only overview but our main website also fails to load.
Going to redirect to a 404 Page :+1:

**Comment by 0x48piraj** [comment]
@mariobehling After researching and reading the following thread _(in reference)_ I have decided to build a 403 Page. :+1: :100: 

> **_Reference : https://stackoverflow.com/questions/19795982/http-status-code-for-unsupported-browser_**

**Comment by arnav-mandal1234** [comment]
@0x48piraj this task was assigned to me, I was going to make the PR tonight.Please ask before taking the task without asking others.

**Comment by 0x48piraj** [comment]
Sorry @arnav-mandal1234 but an issue is assigned only for a week, and it's GCI going on.
As the issue was staling, I decided to pick it up :+1:
