### ISSUE TITLE
Text is shifting out of the "skill" div in susi chat / upload image

### ISSUE THREAD

**Issue by chaloner** [fossasia/chat.susi.ai#962]
Using susi chat is great in getting many information simply by asking questions.

I noticed little bug at skill div.

The text in that div is moving left away from its position.

I have images and gift to show the bug.
And to reproduce it simply click on main menu, click on skill, click on addition, behold the bug.... Next click on upload image and notice the image moving away also.

Steps in images.
Click on menu then click on skill
![Screenshot_20171215-013750.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513298652/vjomy2cyimyhsj6rzolt.png)
Click on addition (cross)
![Screenshot_20171215-013806.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513298681/skyxadimvwo9oausos1w.png)
We have the bug here!
![Screenshot_20171215-013822.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513298731/w89wak9yo4yx6lcnjk77.png)

Upload image...
![Screenshot_20171215-013912.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513298765/wjxi8lbcdfuppqso6hl2.png)

So we believe the programmers will take charge.
Also see the gift.
![20171215_012550.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513298814/uuxn06rfzvt5mlwscruo.gif)

This happens on chrome using android phone.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@drigweeu/text-is-shifting-out-of-the-skill-div-in-susi-chat-upload-image">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by rishiraj824** [comment]
@chaloner Thanks for you to pointing it out. lease open it as an issue in https://github.com/fossasia/susi_skill_cms/issues
