### ISSUE TITLE
To add a feature of music player

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/chat.susi.ai#964]
A feature request

**Expected Behaviour**

To have a feature that plays music from the a soundcloud playlist accesible like the search icon

**Steps to reproduce it**

Through the soundcloud API

**Would you like to work on the issue?**

Yes

**Comment by stealthanthrax** [comment]
@madhavrathi @rishiraj824 @isuruAb @mariobehling  , can I add this feature?

**Comment by rishiraj824** [comment]
@stealthanthrax You can try to implement it as a skill rather than a single client feature, all other SUSI clients, bots should be synonymous and follow the same features. That's the aim!

**Comment by stealthanthrax** [comment]
@rishiraj824 ,I was suggesting a playback feature while talking to susi.

**Comment by stealthanthrax** [comment]
I am closing this issue and will be opening a relevant one in susi skills
