### ISSUE TITLE
Unable to preview the video in the about section

### ISSUE THREAD

**Issue by DNS-404** [fossasia/chat.susi.ai#965]
**Actual Behaviour**

On https://chat.susi.ai/overview , we have an option to watch a video to see susi in action.
The link to that video doesn't seem to work. It just opens up a blank window.

**Expected Behaviour**

The video should be played in place of this white blank window(2nd screenshot)
<img width="500" alt="screen shot 2017-12-17 at 9 35 46 pm" src="https://user-images.githubusercontent.com/31174685/34081609-82d17378-e375-11e7-8b43-995c922e1c26.png">
This shows the overview page on susi.ai
<img width="500" alt="screen shot 2017-12-17 at 9 36 05 pm" src="https://user-images.githubusercontent.com/31174685/34081616-ac4388b8-e375-11e7-93f8-576365340b29.png">
This "blank white screen" appears in place of a video after clicking the "Watch" button in blue.

**Would you like to work on the issue?**

Yes, I would love to work on this issue!

**Comment by yashNadun** [comment]
It's still the same, @DNS-404 are there any updates?
