### ISSUE TITLE
All the custom background and themes are restored to default on refreshing the page

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/chat.susi.ai#967]
**Actual Behaviour**

The applied themes and the background are removed on refresh

**Expected Behaviour**

To apply it again with logged in state

**Steps to reproduce it**

Choose a theme and then refresh the page

**Would you like to work on the issue?**

Yes

**Comment by arnav-mandal1234** [comment]
Can I get on this?

**Comment by stealthanthrax** [comment]
This,issues is assigned to me

**Comment by stealthanthrax** [comment]
This issue is assigned to me

**Comment by stealthanthrax** [comment]
Will be making a PR in 3-4 days
