### ISSUE TITLE
To add a reset to default button on the custom themes page

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/chat.susi.ai#968]
**Actual Behaviour**

If the user messes up with the color combination, then the user needs to rely on his memory to change the color of susi

**Expected Behaviour**

To add a button that removes theme profiles and resets it to default

**Would you like to work on the issue?**

Yes

**Comment by Remorax** [comment]
@stealthanthrax There already is a reset button. Just click on the Themes tab, and there are two options: Save and Reset.

**Comment by stealthanthrax** [comment]
sorry @Remorax , saw it just now
