### ISSUE TITLE
Improving Surge deployment documentation

### ISSUE THREAD

**Issue by kartikeya23** [fossasia/chat.susi.ai#972]
**The issue**

* The document is not in a chronological manner. 
* A lot of repeated steps (all similar screenshots need to brought together).

**Screenshots of the issue**

![repeated content](https://user-images.githubusercontent.com/24318731/34371062-dc94f796-eaef-11e7-9e12-e8abbcaa466e.png)

**Would you like to work on the issue?**

Yes!

**Comment by ParthS007** [comment]
@kartikeya23 Can you please be more specific and add the more clear screenshot.

**Comment by kartikeya23** [comment]
@ParthS007 I've created a PR actually, you can see the changes I've done there if you don't mind.
#973

**Comment by ParthS007** [comment]
@kartikeya23 Please close this if resolved 👍
