### ISSUE TITLE
Login to susi.ai unsuccessful

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [fossasia/chat.susi.ai#974]
**Actual Behaviour**

'Login failed. Try Again' message displayed in the login modal of susi.ai. Tried to login multiple times, with different accounts, but the same result. Registering with the same e-mail renders the correct response though, saying that the id is already used.

 Behaviour is same for localhost as well as on surge

**Expected Behaviour**

Successful login to susi.ai

**Steps to reproduce it**

Try logging in normally. The sample surge deploy is at: http://level-spiders.surge.sh/

**Screenshots of the issue**

![screen shot 2017-12-27 at 3 13 20 pm](https://user-images.githubusercontent.com/29275810/34381801-c7dcf7b8-eb30-11e7-8988-087e969d17c0.png)

![screen shot 2017-12-27 at 3 13 45 pm](https://user-images.githubusercontent.com/29275810/34381723-53f736ce-eb30-11e7-9f3a-622146b60401.png)

**Comment by anshumanv** [comment]
I'm able to login just fine, can you please try resetting your password and trying again?

**Comment by VibhorCodecianGupta** [comment]
Yes, did that. Used the forgot password as well. It works fine, except the login still doesn't work

**Comment by Remorax** [comment]
I am able to login normally too.

**Comment by VibhorCodecianGupta** [comment]
@anshumanv I seem to encounter the same issue at skills_susi_cms. It absolutely refuses to log in, I have tried every workaround including the change password.
I use OSX 10.11.6 (El Capitan)

**Comment by anshumanv** [comment]
I'm not sure then, please let other's see if they can reproduce this bug, since me and @Remorax can't. :smile:
