### ISSUE TITLE
Settings sidebar overflows

### ISSUE THREAD

**Issue by isuruAb** [fossasia/chat.susi.ai#975]
**Actual Behaviour**

Sidebar of the settings page overflows from items.

**Expected Behaviour**

Settings list should be fit to the sidebar

**Screenshots of the issue**

<img width="359" alt="screen shot 2017-12-29 at 6 33 21 am" src="https://user-images.githubusercontent.com/7692626/34426981-903c5460-ec62-11e7-98f6-e054e2efb8d3.png">

**Would you like to work on the issue?**

anyone can get it

**Comment by naveentherocker** [comment]
Can I work on it?

**Comment by isuruAb** [comment]
@naveentherocker  yes you can 👍

**Comment by naveentherocker** [comment]
Yeah Sure.
