### ISSUE TITLE
Adding Sinhala language for SUSI Web Chat Components using Weblate

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/chat.susi.ai#981]
**Actual Behaviour**

There is no Sinhala Language yet.

**Expected Behaviour**

Add it using using Weblate

**Would you like to work on the issue?**

I am working!

**Comment by isuruAb** [comment]
how is the progress of this issue ?

**Comment by STEdirisuriya** [comment]
https://hosted.weblate.org/projects/susi-ai/chat/si/ - It finished now.

**Comment by ParthS007** [comment]
@STEdirisuriya Please close this if resolved 👍
