### ISSUE TITLE
Error sharing on facebook

### ISSUE THREAD

**Issue by nileshgulia1** [fossasia/chat.susi.ai#982]
#798 **Actual Behaviour**
Doesn't share on facebook throwing this error:
![screenshot from 2017-12-30 21-48-05](https://user-images.githubusercontent.com/22280901/34455729-39f44730-edab-11e7-9e92-7eef09725a7c.png)

**Expected Behaviour**

Should open facebook sharing page asking user to share or not.
**Steps to reproduce it**
1.Open settings
2.click on share on facebook
3.click share

**Would you like to work on the issue?**
yes,need some discussion from the members

**Comment by nileshgulia1** [comment]
#798

**Comment by nileshgulia1** [comment]
#798

**Comment by Remorax** [comment]
It works perfectly fine for me, on both Chrome and Firefox.
Please check it again.

**Comment by nileshgulia1** [comment]
@Remorax did u try after logging in into susi.ai ?

**Comment by nileshgulia1** [comment]
@Remorax  its not working .can u confirm with other members? :)
![screenshot from 2017-12-30 23-16-47](https://user-images.githubusercontent.com/22280901/34456236-b5a622ac-edb7-11e7-8dff-c05bc28c99df.png)

**Comment by Remorax** [comment]
It doesn't work on localhost, but it works on http://chat.susi.ai and ultimately the user is gonna use it from there only, so I feel this issue can be closed 😄

**Comment by nileshgulia1** [comment]
yeah,works fine in production,thanks and good job!! :+1:
