### ISSUE TITLE
Very long table is embedded into chat

### ISSUE THREAD

**Issue by AnshulMalik** [fossasia/chat.susi.ai#99]
Currently, if we search for `universities in india`, we get a huge table lying in the chatbox.
Adding a lot of irrelevant content. 

Another approach I would suggest is, to show first few results, let's say 5.
And add a button to show more, and may be can show them separately in a sidebar.

**Comment by isuruAb** [comment]
if we can add a data table with paging and sorting functions it would be really nice.

**Comment by rishiraj824** [comment]
@AnshulMalik Yes this would be nice.

**Comment by uday96** [comment]
But it would be difficult in a mobile screen if we display in sidebar right?

**Comment by rishiraj824** [comment]
Yes, a sidebar won't suffice the issue, we can directly expand the table in the chat section. What do you think? @AnshulMalik @isuruAb @uday96

**Comment by uday96** [comment]
data table with paging sounds good. Like show each page of fixed max rows and user can scroll to the right to see more results in next page. Is this what you meant @isuruAb ?

**Comment by AnshulMalik** [comment]
Hmm, if we expand the table inside the chat area, then user should be able to collapse it otherwise it's the same thing. 

And paging inside chat app, it looks weird to me, another solution I can suggest is, to display it in a modal like component on small screens and as a sidebar on large enough screens.

**Comment by uday96** [comment]
@mariobehling  This can be closed now as we are now using ```count``` attribute from the response to show limited number of rows.

Refer : https://github.com/fossasia/chat.susi.ai/pull/197
